'use strict';
const test=require('node:test'),a=require('node:assert/strict');
const {safeMarkdown:m,safeMarkdownURL:u}=require('../src/modules/markdown.js');
for(const [name,source,pattern] of [
 ['heading','# Title',/<h2>Title<\/h2>/],['all levels','###### Six',/<h6>Six<\/h6>/],['bold','**bold**',/<strong>bold<\/strong>/],['italic','*word*',/<em>word<\/em>/],['strike','~~old~~',/<del>old<\/del>/],['inline code','`**unchanged**`',/<code>\*\*unchanged\*\*<\/code>/],['code block','```js\n<script>evil()</script>\n```',/&lt;script&gt;evil\(\)&lt;\/script&gt;/],['tilde fence','~~~\ncode\n~~~',/<pre/],['unclosed fence','```\ncode',/<\/code><\/pre>$/],['quote','> Context',/<blockquote><p>Context<\/p><\/blockquote>/],['ordered','3. three\n4. four',/<ol start="3"><li>three<\/li><li>four<\/li><\/ol>/],['list','- a\n- b',/<ul><li>a<\/li><li>b<\/li><\/ul>/],['nested list','- a\n  - b',/<li>a<ul><li>b<\/li><\/ul><\/li>/],['checklist','- [x] done\n- [ ] pending',/aria-label="Выполнено"/],['table','| A | B |\n| --- | ---: |\n| 1 | 2 |',/<th scope="col" class="md-align-right">B/],['escaped pipe','| A | B |\n| --- | --- |\n| a\\|b | c |',/a\|b<\/td>/],['table code','| A | B |\n| --- | --- |\n| `a|b` | c |',/<code>a\|b<\/code>/],['escaped markdown','\\*literal\\*',/\*literal\*/],['balanced URL','[a](https://example.com/a_(b))',/href="https:\/\/example.com\/a_\(b\)"/],['title attribute','[a](https://example.com "title")',/title="title"/],['raw HTML','<img src=x onerror=alert(1)>',/&lt;img/],['breaks','one\ntwo',/one<br>two/],['rule','---',/^<hr>$/],['CRLF','# H\r\n\r\nP',/<h2>H<\/h2><p>P<\/p>/]])test('renderer: '+name,()=>a.match(m(source),pattern));
test('empty, null and whitespace do not manufacture a document',()=>{for(const v of ['',null,undefined,'  \n\n'])a.equal(m(v),'')});
test('no double parsing inside code / URL / title',()=>{const s=m('`[x](https://example.com)` [**x**](https://example.com/a?x=1&y=2 "<b>")');a.equal((s.match(/<a /g)||[]).length,1);a.match(s,/title="&lt;b&gt;"/);a.match(s,/<strong>x<\/strong>/);a.match(s,/&amp;y=2/)});
const bad=['javascript:alert(1)','java\nscript:alert(1)','data:text/html,x','vbscript:a','http://example.com','//example.com','file:///tmp/file','blob:https://example.com/x','https://user:pass@example.com','https:\\evil','https://x.com/\u0000','https://x.com/ x','javascript&#58;alert(1)'];
for(const url of bad)test('URL rejected: '+JSON.stringify(url),()=>{a.equal(u(url),null);a.doesNotMatch(m(`[x](${url})`),/<a /)});
test('allowed URL scheme normalized and escaped',()=>{a.equal(u('HTTPS://example.com'),'https://example.com/');a.equal(u('#details'),'#details');a.match(m('[x](https://example.com/?q="x")'),/%22/)});
test('images never emit auto-loading resource tags',()=>{const s=m('![secret](https://example.com/private.png)');a.doesNotMatch(s,/<(?:img|video|audio|iframe|script|style|object|embed)\b/);a.match(s,/изображение по ссылке/)});
test('all headings can start at specified level',()=>a.equal(m('# T\n## S',{headingLevel:3}),'<h3>T</h3><h4>S</h4>'));
test('bounded source and heading arguments fail explicitly',()=>{a.throws(()=>m('x'.repeat(1000001)),RangeError);a.throws(()=>m('x',{headingLevel:0}),RangeError)});
test('markup source never supplies DOM IDs or styles',()=>{a.doesNotMatch(m('<div id=x style="background:url(https://example.com)">hello</div>'),/<div/)});
