'use strict';
const C=require('./advanced-core.js');
const {button,ib}=require('./advanced-base.js');
const {icon}=require('./components.js');
const {safeMarkdown}=require('./editor.js');
const allKinds=['note','task','checklist','media','group'];
const operations=['read','create','move','resize','editContent','connect','editRelations','deleteRelations','archive','restore','open','discuss'];
const defaults={read:true,create:true,move:true,resize:true,editContent:true,connect:true,editRelations:true,deleteRelations:true,archive:true,restore:true,open:true,discuss:false};
function permitObject(v){if(v===false)return Object.fromEntries(operations.map(k=>[k,false]));if(!v||typeof v!=='object'||Array.isArray(v))throw new TypeError('Права: объект');const out={};for(const[k,b]of Object.entries(v)){if(k==='fields'){if(!b||typeof b!=='object')throw new TypeError('fields: объект');out.fields={};for(const[f,p]of Object.entries(b)){if(typeof p!=='boolean')throw new TypeError('Право поля: boolean');out.fields[f]=p;}}else{if(!operations.includes(k)||typeof b!=='boolean')throw new TypeError('Неизвестное право '+k);out[k]=b;}}return out;}
function suspendPending(surface){if(surface.pending){surface.invalidateRequest();surface.pending=false;surface.issue='Права изменились. Черновик сохранён, подтвердите доступные изменения заново.';}}
function installRoadmap(K){
 const base={action:K.prototype.action,inspector:K.prototype.inspector,edgeInspector:K.prototype.edgeInspector,preview:K.prototype.preview,requestCommit:K.prototype.requestCommit};
 Object.defineProperty(K.prototype,'dependencyCapabilities',{get(){return{create:true,update:true,delete:true,...this._dependencyCapabilities}},set(v){if(v===false)v={create:false,update:false,delete:false};if(!v||typeof v!=='object'||Object.entries(v).some(([k,x])=>!['create','update','delete'].includes(k)||typeof x!=='boolean'))throw new TypeError('dependencyCapabilities: create/update/delete boolean');this._dependencyCapabilities={...v};suspendPending(this);this.cancelGesture?.();this.schedule();}});
 K.prototype.checkDependencies=function(next,previous=this.data){const before=new Map(previous.dependencies.map(e=>[e.id,e])),after=new Map((next.dependencies||[]).map(e=>[e.id,e])),cap=this.dependencyCapabilities;for(const[id,e]of before){if(!after.has(id)&&!cap.delete||after.has(id)&&JSON.stringify(e)!==JSON.stringify(after.get(id))&&!cap.update){this.issue='Изменение зависимостей недоступно.';this.schedule();return false;}}if(!cap.create&&[...after.keys()].some(id=>!before.has(id))){this.issue='Создание зависимостей недоступно.';this.schedule();return false;}return true;};
 K.prototype.preview=function(next,operation){return this.checkDependencies(next)&&base.preview.call(this,next,operation)};
 K.prototype.requestCommit=function(){return this.checkDependencies(this.data,this.session.base)&&base.requestCommit.call(this)};
 K.prototype.inspector=function(r,d,disabled){let markup=base.inspector.call(this,r,d,disabled);const caps=this.dependencyCapabilities;if(!caps.create&&!caps.update&&!caps.delete)return markup.replace(/<details class="rm-link-editor">[\s\S]*?<\/details>/,'');if(!caps.create)markup=markup.replace(/<div class="rm-link-fields">[\s\S]*?<\/div>/,'');if(!caps.delete)markup=markup.replace(/<button[^>]*data-pro-action="remove-link"[^>]*>[\s\S]*?<\/button>/g,'');return markup;};
 K.prototype.edgeInspector=function(d,disabled){let out=base.edgeInspector.call(this,d,disabled);if(!this.dependencyCapabilities.delete)out=out.replace(/<button[^>]*data-pro-action="remove-link"[^>]*>[\s\S]*?<\/button>/g,'');return out;};
 K.prototype.action=function(action,el){if(action==='add-link'&&!this.dependencyCapabilities.create||action==='remove-link'&&!this.dependencyCapabilities.delete)return;const result=base.action.call(this,action,el);if(['scale','prev-range','next-range','today'].includes(action)){const b=this.bounds(),detail={scale:this.scale,range:{start:C.iso(b.start),end:C.iso(b.end)},reason:action};this.emit('iq-view-change',detail);}if(action==='deselect')this.emit('iq-selection',null);return result;};
}
function installGraph(K){
 const base={};for(const name of ['start','cleanup','render','nodeMarkup','inspector','libraryMarkup','textAlternative','action','preview','keys','nodes','edgeSVG','requestCommit'])base[name]=K.prototype[name];
 Object.defineProperties(K.prototype,{
  allowedKinds:{get(){return [...(this._allowedKinds||allKinds)]},set(v){if(!Array.isArray(v)||v.some(k=>!allKinds.includes(k)))throw new TypeError('allowedKinds: поддерживаемые виды');this._allowedKinds=[...new Set(v)];suspendPending(this);this.schedule();}},
  kindLabels:{get(){return {...this._kindLabels}},set(v){if(!v||Object.entries(v).some(([k,t])=>!allKinds.includes(k)||typeof t!=='string'||!t.trim()||t.length>80))throw new TypeError('kindLabels: непустые названия');this._kindLabels={...v};this.schedule();}},
  permissions:{get(){return {...defaults,...this._permissions}},set(v){this._permissions=permitObject(v);suspendPending(this);this.cancelGesture?.();this.schedule();}},
  nodePermissions:{get(){return C.clone(this._nodePermissions||{})},set(v){if(!v||Array.isArray(v)||typeof v!=='object')throw new TypeError('nodePermissions: объект по ID');this._nodePermissions=Object.fromEntries(Object.entries(v).map(([id,p])=>[id,permitObject(p)]));suspendPending(this);this.cancelGesture?.();this.schedule();}},
  mediaSources:{get(){return new Map(this._mediaSources||[])},set(v){if(!(v instanceof Map))throw new TypeError('mediaSources: Map<id, Blob | HTTPS URL>');for(const[id,s]of v){if(typeof id!=='string'||!(s instanceof Blob)&&!(typeof s==='string'&&/^https:\/\//.test(s)))throw new TypeError('Источник: Blob или разрешённый HTTPS URL');}for(const url of this._mediaURLs?.values()||[])URL.revokeObjectURL(url);this._mediaURLs=new Map();this._mediaSources=new Map(v);this.schedule();}},
  archiveClusters:{get(){return C.clone(this._archiveClusters||[])},set(v){if(!Array.isArray(v)||v.some(x=>!x||typeof x.id!=='string'||typeof x.title!=='string'||!Array.isArray(x.nodeIds)))throw new TypeError('archiveClusters: id/title/nodeIds');this._archiveClusters=C.clone(v);this.schedule();}}
 });
 K.prototype.can=function(op,n,field){const p=this.permissions,np=n?this._nodePermissions?.[n.id]||{}:{};let allowed=p[op]!==false&&np[op]!==false;if(n&&(n.status==='disabled'||n.readonly)&&!['read','open','discuss'].includes(op)&&np[op]!==true)allowed=false;if(field&&(p.fields?.[field]===false||np.fields?.[field]===false))allowed=false;return allowed;};
 K.prototype.visibleNode=function(n){return this.can('read',n)?n:{...n,title:'Содержимое недоступно',text:'',alt:'',url:'',items:[]};};
 K.prototype.nodes=function(){return base.nodes.call(this).map(n=>this.visibleNode(n));};
 K.prototype.textAlternative=function(d){const visible=this.nodes();return `<div class="graph-list" aria-label="Объекты и связи">${visible.map(n=>`<div class="graph-list-item"><button type="button" data-pro-action="select-node" data-node="${C.escape(n.id)}" aria-pressed="${this.selectedId===n.id}"><span><small>${C.escape(this.kindLabels[n.kind]||({note:'Заметка',task:'Задача',media:'Материал',group:'Группа',checklist:'Чек-лист'}[n.kind]))}</small><b>${C.escape(n.title)}</b></span>${icon('chevron',16)}</button>${d.edges.filter(e=>e.source===n.id&&visible.some(t=>t.id===e.target)).map(e=>{const t=visible.find(x=>x.id===e.target);const readable=this.can('read',n)&&this.can('read',t);return `<button type="button" class="graph-text-edge" data-pro-action="select-edge" data-edge="${C.escape(e.id)}">${icon('arrow',14)}${C.escape(readable?e.label||'Связь':'Связь с ограниченным доступом')}: ${C.escape(t.title)}</button>`}).join('')}</div>`).join('')}</div>`;};
 K.prototype.start=function(){base.start.call(this);const signal=this.events.signal;this.addEventListener('pointermove',e=>{const c=e.target.closest('.graph-canvas');if(!c)return;const rect=c.getBoundingClientRect(),v=this.viewport;this._lastPointer={x:(e.clientX-rect.left-v.x)/v.zoom,y:(e.clientY-rect.top-v.y)/v.zoom,pointerType:e.pointerType,inside:true};if(!this._pointerFrame)this._pointerFrame=requestAnimationFrame(()=>{this._pointerFrame=0;if(this.isConnected)this.emit('iq-pointer',this._lastPointer)});},{signal});this.addEventListener('pointerleave',()=>this.emit('iq-pointer',{inside:false}),{signal});};
 K.prototype.cleanup=function(){base.cleanup?.call(this);cancelAnimationFrame(this._pointerFrame);for(const url of this._mediaURLs?.values()||[])URL.revokeObjectURL(url);this._mediaURLs=new Map();};
 K.prototype.checkPermissions=function(next,old=this.data){
  const by=new Map(old.nodes.map(n=>[n.id,n]));
  const deny=()=>{this.issue='Это действие недоступно для выбранного объекта.';this.schedule();return false;};
  for(const n of next.nodes){const a=by.get(n.id);if(!a){if(!this.can('create')||!this.allowedKinds.includes(n.kind))return deny();continue;}for(const key of new Set([...Object.keys(a),...Object.keys(n)])){if(JSON.stringify(a[key])===JSON.stringify(n[key]))continue;const category=['x','y','parentId'].includes(key)?'move':['width','height'].includes(key)?'resize':key==='archived'||key==='archivedByGroup'?(n.archived?'archive':'restore'):'editContent';if(!this.can(category,a,key))return deny();}}
  if(old.nodes.some(n=>!next.nodes.some(x=>x.id===n.id)&&!this.can('archive',n)))return deny();
  const before=new Map(old.edges.map(e=>[e.id,e]));for(const e of next.edges){const prior=before.get(e.id),op=prior?'editRelations':'connect';if(!prior||JSON.stringify(prior)!==JSON.stringify(e)){if(!this.can(op)||[e.source,e.target].some(id=>!this.can(op,by.get(id))))return deny();}}
  if(old.edges.some(e=>!next.edges.some(x=>x.id===e.id)&&(!this.can('deleteRelations')||[e.source,e.target].some(id=>!this.can('deleteRelations',by.get(id))))))return deny();return true;
 };
 K.prototype.preview=function(next,op){return this.checkPermissions(next)&&base.preview.call(this,next,op)};
 K.prototype.requestCommit=function(){return this.checkPermissions(this.data,this.session.base)&&base.requestCommit.call(this)};
 K.prototype.edgeSVG=function(d){const nodes=new Map(d.nodes.map(n=>[n.id,n]));const safe={...d,edges:d.edges.map(e=>[e.source,e.target].some(id=>!this.can('read',nodes.get(id)))?{...e,label:'Связь с ограниченным доступом'}:e)};return base.edgeSVG.call(this,safe);};
 K.prototype.libraryMarkup=function(workflow,disabled){let markup=base.libraryMarkup.call(this,workflow,disabled);for(const k of allKinds){if(!this.allowedKinds.includes(k)||!this.can('create'))markup=markup.replace(new RegExp('<button[^>]*data-kind="'+k+'"[^>]*>[\\s\\S]*?<\\/button>','g'),'');else if(this.kindLabels[k])markup=markup.replace(new RegExp('(data-kind="'+k+'"[^>]*>[\\s\\S]*?<b>)[^<]+(<\\/b>)'),'$1'+C.escape(this.kindLabels[k])+'$2');}return markup;};
 K.prototype.nodeMarkup=function(n){const read=this.can('read',n);let display=read?n:{...n,title:'Содержимое недоступно',text:'Нет прав на просмотр',items:[],url:'',alt:'',kind:n.kind};let html=base.nodeMarkup.call(this,display);if(!this.can('read',n))html=html.replace(/<span class="graph-edit-presence">[\s\S]*?<\/span>/g,'');const label=this.kindLabels[n.kind];if(label){const labels={note:['Заметка','Запрос'],task:['Задача','Действие'],media:['Материал'],group:['Группа','Этапы'],checklist:['Чек-лист','Проверка']};for(const old of labels[n.kind]||[])html=html.replace(new RegExp('>'+old+'<','g'),'>'+C.escape(label)+'<');}
  if(read&&n.text&&n.kind!=='media'&&n.kind!=='group')html=html.replace('<p>'+C.escape(n.text)+'</p>','<div class="graph-markdown">'+safeMarkdown(n.text)+'</div>');
  if(read&&n.kind==='media'&&this._mediaSources?.has(n.id)){const source=this._mediaSources.get(n.id);let url=source;if(source instanceof Blob){if(!this._mediaURLs)this._mediaURLs=new Map();if(!this._mediaURLs.has(n.id))this._mediaURLs.set(n.id,URL.createObjectURL(source));url=this._mediaURLs.get(n.id);}html=html.replace(/<div class="graph-media-empty">[\s\S]*?<\/div>/,`<div class="graph-image-frame"><img src="${C.escape(url)}" alt="${C.escape(n.alt||n.title)}" draggable="false"><span class="graph-media-empty" hidden>Не удалось открыть материал</span></div>`);}
  if(this.can('open',n)&&read)html=html.replace('</h4>','</h4>'+`<button type="button" class="graph-domain-open" data-pro-action="open-node" data-node="${C.escape(n.id)}" aria-label="Открыть: ${C.escape(n.title)}">${icon('upRight',16)}</button>`);
  if(!this.can('connect',n))html=html.replace(/<button[^>]*class="graph-port[^>]*>[\s\S]*?<\/button>/g,'');if(!this.can('move',n))html=html.replace(/data-node-drag="[^"]*"/g,'');if(!this.can('resize',n))html=html.replace(/<span class="graph-resize"[^>]*><\/span>/,'');return html;
 };
 K.prototype.inspector=function(n){let markup=base.inspector.call(this,this.visibleNode(n));if(this.kindLabels[n.kind])markup=markup.replace(/(<h4>)[^<]+(<\/h4>)/,'$1'+C.escape(this.kindLabels[n.kind])+'$2');return markup;};
 K.prototype.render=function(){for(const[id,url]of this._mediaURLs||[]){const n=this.data.nodes.find(x=>x.id===id);if(!n||!this.can('read',n)){URL.revokeObjectURL(url);this._mediaURLs.delete(id);}}base.render.call(this);const n=this.data.nodes.find(n=>n.id===this.selectedId),panel=this.querySelector('.graph-inspector');if(panel&&n){for(const el of panel.querySelectorAll('[data-graph-field]')){const field=el.dataset.graphField,category=['x','y'].includes(field)?'move':['width','height'].includes(field)?'resize':'editContent';el.disabled=this.locked||!this.can(category,n,field);if(!this.can('read',n)&&category==='editContent')el.value='';}for(const el of panel.querySelectorAll('[data-graph-items]')){el.disabled=this.locked||!this.can('editContent',n,'items');if(!this.can('read',n))el.value='';}if(!this.can('read',n)){for(const el of panel.querySelectorAll('.iq-pro-field')){const f=el.querySelector('[data-graph-field]');if(!f||!['x','y','width','height'].includes(f.dataset.graphField))el.hidden=true;}}
   const submit=panel.querySelector('[data-pro-action=edit-node]');if(submit)submit.disabled=this.locked||!['editContent','move','resize'].some(op=>this.can(op,n));
   if(!this.can('connect',n))panel.querySelector('.graph-connect-form')?.remove();if(!this.can('archive',n))panel.querySelector('[data-pro-action=archive-node]')?.remove();
   if(this.can('discuss',n)&&this.can('read',n))panel.querySelector('.graph-inspector-end')?.insertAdjacentHTML('afterbegin',button('Обсудить','discuss-node','message'));
  }
  this.querySelectorAll('[data-pro-action=layout]').forEach(b=>b.disabled=this.locked||this.data.nodes.some(n=>!n.archived&&!this.can('move',n)));this.querySelectorAll('[data-pro-action=library]').forEach(b=>b.hidden=!this.can('create')||!this.allowedKinds.length);
  const edge=this.data.edges.find(e=>e.id===this.selectedEdge);if(edge){const readable=[edge.source,edge.target].every(id=>this.can('read',this.data.nodes.find(n=>n.id===id)));const input=this.querySelector('[data-graph-edge-label]');if(input){input.disabled=this.locked||!this.can('editRelations')||!readable;if(!readable)input.value='';}this.querySelectorAll('[data-pro-action=edit-edge]').forEach(b=>b.hidden=!this.can('editRelations')||!readable);this.querySelectorAll('[data-pro-action=delete-edge]').forEach(b=>b.hidden=!this.can('deleteRelations'));}
  this.querySelectorAll('[data-pro-action=add]').forEach(b=>b.disabled=this.locked||!this.can('create')||!this.allowedKinds.includes(b.dataset.kind));
  for(const buttonEl of this.querySelectorAll('[data-pro-action=restore]'))buttonEl.hidden=!this.can('restore',this.data.nodes.find(n=>n.id===buttonEl.dataset.node));
  if(this.showArchive&&this.archiveClusters.length)this.querySelector('.graph-archive-list')?.insertAdjacentHTML('beforeend',`<div class="graph-archive-clusters">${this.archiveClusters.map(c=>`<button type="button" class="iq-btn secondary sm" data-pro-action="open-cluster" data-cluster="${C.escape(c.id)}">${C.escape(c.title)} <span>${c.nodeIds.length}</span></button>`).join('')}</div>`);
 };
 K.prototype.action=function(action,el,event){const n=this.data.nodes.find(n=>n.id===(el.dataset.node||this.selectedId));if(action==='open-node'){if(n&&this.can('open',n)&&this.can('read',n))this.emit('iq-open',{kind:'node',id:n.id,node:C.clone(n)});return;}if(action==='discuss-node'){if(n&&this.can('discuss',n)&&this.can('read',n))this.emit('iq-discussion',{id:n.id});return;}if(action==='open-cluster'){this.emit('iq-open',{kind:'archive-cluster',id:el.dataset.cluster});return;}
  const operation={add:'create',connect:'connect','port-out':'connect','port-in':'connect','archive-node':'archive',restore:'restore','delete-edge':'deleteRelations','edit-edge':'editRelations'}[action];if(operation&&!this.can(operation,n))return;
  if(action==='edit-node'&&n){const next=this.data,target=next.nodes.find(n=>n.id===this.selectedId);for(const input of this.querySelectorAll('[data-graph-field]:not(:disabled)')){const key=input.dataset.graphField;target[key]=['x','y','width','height'].includes(key)?Number(input.value):input.value.trim();}const checklist=this.querySelector('[data-graph-items]:not(:disabled)');if(checklist)target.items=checklist.value.split('\n').filter(s=>s.trim()).map(s=>({label:s.replace(/^\s*(?:-\s*)?\[[ xX]\]\s*/,'').trim(),checked:/^\s*(?:-\s*)?\[[xX]\]/.test(s)}));return this.preview(next,{kind:'edit',id:n.id});}
  const result=base.action.call(this,action,el,event);if(action==='select-edge')this.emit('iq-selection',{kind:'edge',id:this.selectedEdge});if(action==='deselect')this.emit('iq-selection',null);return result;
 };
 K.prototype.keys=function(e){const edge=e.target.closest('[data-edge-id]');base.keys.call(this,e);if(edge&&['Enter',' '].includes(e.key))this.emit('iq-selection',{kind:'edge',id:this.selectedEdge});};
}
Object.assign(exports,{installGraph,installRoadmap,permitObject});
