'use strict';
const B=require('./whiteboard-core.js');
const U=require('./whiteboard-experience-core.js');
const {icon,escapeHTML:esc}=require('./components.js');
const labels={sticky:'Заметка',text:'Текст',shape:'Фигура',frame:'Область',task:'Действие',image:'Изображение',drawing:'Рисунок'};
const toolList=[['select','Выбрать','cursor','V'],['hand','Двигать','hand','H'],['sticky','Заметка','sticky','S'],['text','Текст','text','T'],['shape','Фигура','grid','R'],['connect','Связь','link','C'],['frame','Область','board','F']];
const colorNames={sand:'Песочный',lavender:'Лавандовый',mint:'Мятный',sky:'Голубой',rose:'Розовый',neutral:'Нейтральный'};
function btn(action,label,glyph,extra='',visible=true){return `<button type="button" class="wb-button${visible?'':' wb-icon-button'}" data-wb-action="${action}" aria-label="${esc(label)}" title="${esc(label)}" ${extra}>${glyph?icon(glyph,18):''}${visible?`<span>${esc(label)}</span>`:''}</button>`}
const inputTarget=e=>e.target.closest?.('input,textarea,select,[contenteditable="true"]');
const json=v=>JSON.stringify(v);
class IqWhiteboard extends HTMLElement{
 static get observedAttributes(){return['readonly','state']}
 constructor(){super();this._data=B.blank();this._selection=[];this._viewport={x:40,y:40,zoom:1};this._templates=[];this.tool='select';this.color='sand';this.shape='rectangle';this.history=[];this.future=[];this.controlled=false;this.mode='canvas';this.panel='';this.fitted=false;this.generation=0;this.vote={active:false,finished:false,limit:3,counts:{}};this.timer={remaining:300,running:false};this.uid=B.newId('board');this.error='';this.storageStatus='';this.activeArea=null;this.searchTerm='';this.sheetDrafts={};}
 connectedCallback(){if(this.events)return;this.events=new AbortController();this.initDOM();this.listen();this.render();this.ro=new ResizeObserver(()=>{if(!this.fitted&&this.stage.clientWidth>0){this.fitted=true;this.fit();}else this.updateViewport(false)});this.ro.observe(this.stage);}
 disconnectedCallback(){this.generation++;this.pending=null;this.events?.abort();this.events=null;this.ro?.disconnect();this.gestureEvents?.abort();cancelAnimationFrame(this.drawFrame);clearInterval(this.timerId);if(this.timer.running){this.timer.remaining=Math.max(0,Math.ceil((this.timer.end-Date.now())/1000));this.timer.running=false;}if(this.dialog?.open)this.dialog.close();if(this.shell&&this.dialog?.contains(this.shell))this.insertBefore(this.shell,this.dialog);this.querySelector('.wb-sheet')?.remove();}
 attributeChangedCallback(){if(this.hasAttribute('readonly')||this.state!=='ready'){const draft=this.editing&&this.editDraft();const dirty=this.editing&&this.editIsDirty();this.cancelGesture();this.finishEdit(false);this.cancelPending();this.tool='select';this.linkFrom=null;if(dirty){this.conflict=draft;this.error='Доступ к редактированию изменился. Набранный текст сохранён для экспорта.';}}this.render();}
 get saveStatus(){return this.storageStatus||''}
 set saveStatus(value){this.storageStatus=String(value??'').slice(0,180);this.render()}
 get readOnly(){return this.hasAttribute('readonly')}
 set readOnly(v){this.toggleAttribute('readonly',!!v)}
 get state(){return this.getAttribute('state')||'ready'}
 set state(v){if(!['ready','loading','error'].includes(v))throw new TypeError('state: ready, loading или error');this.setAttribute('state',v)}
 get view(){return this.mode}
 set view(v){if(!['canvas','list'].includes(v))throw new TypeError('view: canvas или list');this.mode=v;this.render();if(v==='canvas'&&this.stage)this.fit();}
 get locked(){return this.readOnly||this.state!=='ready'||!!this.pending||!!this.conflict}
 editIsDirty(){if(!this.editing)return false;const ed=this.editing,o=this._data.objects.find(o=>o.id===ed.id);return !o||(ed.input?.value??ed.textEl.innerText??ed.textEl.textContent)!==ed.original||ed.align!==o.align||ed.valign!==o.valign;}
 get data(){return B.clone(this.pending?.value||this._data)}
 set data(v){const next=B.validateBoard(v);const draft=this.editing&&this.editIsDirty()?this.editDraft():null;this.generation++;this.cancelGesture();this.finishEdit(false);if(this.pending||draft||this.retryValue){this.conflict=draft||B.clone(this.pending?.value||this.retryValue);this.pending=null;this.retryValue=null;this.error='Пришла другая версия. Ваша копия сохранена для экспорта.';this.generation++;}this._data=next;this.history=[];this.future=[];this._selection=this._selection.filter(k=>this.exists(k));this.render()}
 get selection(){return [...this._selection]}
 set selection(ids){if(!Array.isArray(ids)||ids.some(k=>typeof k!=='string'||!this.exists(k)))throw new TypeError('selection: массив существующих id');this._selection=[...new Set(ids)];this.renderSelection();}
 get viewport(){return{...this._viewport}}
 set viewport(v){if(!v||![v.x,v.y,v.zoom].every(Number.isFinite)||v.zoom<.2||v.zoom>2.5||Math.abs(v.x)>1000000||Math.abs(v.y)>1000000)throw new TypeError('Некорректный viewport');this._viewport={x:v.x,y:v.y,zoom:v.zoom};this.fitted=true;this.updateViewport(false)}
 get templates(){return this._templates.map(t=>({...t,data:B.clone(t.data)}))}
 set templates(v){if(!Array.isArray(v))throw new TypeError('templates: массив');this._templates=v.map(t=>({id:String(t.id),title:String(t.title),description:String(t.description||''),data:B.validateBoard(t.data)}))}
 exists(id){const data=this.pending?.value||this._data;return data.objects.some(o=>o.id===id)||data.connections.some(e=>e.id===id)}
 emit(name,detail){this.dispatchEvent(new CustomEvent(name,{detail,bubbles:true,composed:true}))}
 announce(text){if(this.live)this.live.textContent=text;this.emit('iq-announcement',{text})}
 initDOM(){if(this.shell){this.insertBefore(this.shell,this.dialog);return;}
 this.innerHTML=`<div class="wb-shell">
 <header class="wb-header"><div class="wb-heading"><span class="wb-board-mark">${icon('board',20)}</span><div><button class="wb-title" data-wb-action="rename" title="Переименовать доску"></button><div class="wb-save-state" aria-live="polite"></div></div></div><div class="wb-header-actions">${btn('quick-note','Добавить заметку','plus','class-placeholder')}${btn('templates','Шаблоны','grid')}${btn('menu','Ещё действия','more','',false)}${btn('fullscreen','Развернуть доску','expand','',false)}</div></header>
 <div class="wb-notice" role="status" hidden></div>
 <div class="wb-command-row"><div class="wb-idle-context"><span class="wb-mode-name">Выбор</span><span class="wb-mode-description">Нажмите на объект, чтобы работать с ним.</span><button type="button" class="wb-button" data-wb-action="cancel-tool" hidden>Отменить${icon('x',16)}</button></div><div class="wb-context" role="toolbar" aria-label="Действия с выделением" hidden></div><div class="wb-history">${btn('undo','Отменить последнее действие','undo','',false)}${btn('redo','Повторить отменённое действие','redo','',false)}</div></div>
 <div class="wb-workspace">
 <nav class="wb-rail" aria-label="Инструменты доски">${toolList.map(([t,l,i,k])=>`<button type="button" class="wb-tool" data-tool="${t}" aria-label="${l} (${k})" title="${l} (${k})" aria-pressed="${t==='select'}">${icon(i,21)}<span>${l}</span></button>`).join('')}${btn('image','Изображение','image')}</nav>
 <main class="wb-center">
 <div class="wb-stage" role="region" aria-label="Рабочая доска. Выберите объект или нажмите Добавить заметку. Справка содержит клавиатурные команды." tabindex="0"><div class="wb-world"><svg class="wb-links" aria-label="Связи"></svg><div class="wb-objects"></div></div><div class="wb-marquee" hidden></div><div class="wb-empty" hidden><span class="wb-empty-mark">${icon('sticky',28)}</span><h3>Начните с одной мысли</h3><p>Запишите её сейчас. Разложить по темам и связать идеи можно позже.</p><div>${btn('quick-note','Добавить заметку','plus')}${btn('bulk','Вставить список идей','list')}</div><button type="button" class="wb-empty-template" data-wb-action="templates">Нужна структура? Выбрать шаблон ${icon('arrow',16)}</button></div><div class="wb-state-surface" hidden></div></div>
 <div class="wb-accessible" hidden></div>
 <footer class="wb-footer"><div class="wb-footer-left">${btn('frames','Области','board')}${btn('search','Найти','search')}${btn('list','Список','list')}${btn('help','Помощь','info','',false)}</div><span class="wb-hint">Выделение рамкой — на свободном месте</span><div class="wb-zoom">${btn('zoom-out','Уменьшить','minus','',false)}<button class="wb-button wb-zoom-label" data-wb-action="reset-zoom" title="Вернуть масштаб 100%">100%</button>${btn('zoom-in','Увеличить','plus','',false)}${btn('fit','Всё','expand')}</div></footer>
 </main><aside class="wb-panel" aria-label="Панель доски" hidden></aside>
 </div><div class="wb-live sr-only" aria-live="polite" role="status"></div>
 </div><dialog class="wb-fullscreen" aria-label="Визуальная доска на весь экран"></dialog><input type="file" class="wb-file-input" data-file="image" accept="image/png,image/jpeg,image/webp" hidden><input type="file" class="wb-file-input" data-file="json" accept="application/json,.json" hidden>`;
 this.shell=this.querySelector('.wb-shell');this.dialog=this.querySelector('.wb-fullscreen');this.stage=this.querySelector('.wb-stage');this.world=this.querySelector('.wb-world');this.objectsEl=this.querySelector('.wb-objects');this.svg=this.querySelector('.wb-links');this.context=this.querySelector('.wb-context');this.live=this.querySelector('.wb-live');this.panelEl=this.querySelector('.wb-panel');this.statusEl=this.querySelector('.wb-save-state');this.listEl=this.querySelector('.wb-accessible');this.shell.querySelector('[data-wb-action=quick-note]').classList.add('wb-primary');
 }
 listen(){const s=this.events.signal;
 this.addEventListener('pointerdown',e=>{if(e.target.closest('[data-wb-action=cancel-edit],[data-wb-action=finish-edit],[data-wb-action=edit-next]'))e.preventDefault()},{signal:s,capture:true});
 this.addEventListener('click',e=>this.click(e),{signal:s});this.addEventListener('dblclick',e=>{if(e.target.closest('button,input,textarea,[contenteditable=true]'))return;const node=e.target.closest('[data-object]');if(node){e.preventDefault();this.edit(node.dataset.object);return}if(e.target===this.stage||e.target===this.world||e.target===this.objectsEl){if(!this.locked){e.preventDefault();const p=this.point(e);this.add('sticky',p.x-104,p.y-82);}}},{signal:s});
 this.addEventListener('pointerdown',e=>this.begin(e),{signal:s});this.addEventListener('keydown',e=>this.key(e),{signal:s});this.addEventListener('keyup',e=>{if(e.code==='Space'&&!inputTarget(e)){this.space=false;this.stage.classList.remove('is-pan')}},{signal:s});window.addEventListener('blur',()=>{this.space=false;this.cancelGesture()},{signal:s});
 this.stage.addEventListener('wheel',e=>{if(this.mode!=='canvas'||this.editing)return;e.preventDefault();const r=this.stage.getBoundingClientRect();if(e.ctrlKey||e.metaKey){this._viewport=B.zoomAt(this.viewport,this.viewport.zoom*Math.exp(-e.deltaY*.003),e.clientX-r.left,e.clientY-r.top)}else{this._viewport.x-=e.deltaX;this._viewport.y-=e.deltaY}this.queueViewport();},{signal:s,passive:false});
 this.addEventListener('focusin',e=>{if(e.target.matches?.('.wb-object,.wb-connection')&&!this.selection.includes(e.target.dataset.object||e.target.dataset.connection)){this._selection=[e.target.dataset.object||e.target.dataset.connection];this.renderSelection();this.emit('iq-selection',{ids:this.selection})}},{signal:s});
 this.addEventListener('paste',e=>this.paste(e),{signal:s});this.addEventListener('copy',e=>{if(inputTarget(e)||!this.selection.length)return;const selected=B.exportSelection(this.data,this.selection);if(!selected.objects.length)return;e.clipboardData.setData('application/x-iquipage-board',json(selected));e.clipboardData.setData('text/plain',selected.objects.map(o=>o.text).join('\n'));e.preventDefault();this.announce('Выделение скопировано')},{signal:s});
 this.addEventListener('change',e=>{if(e.target.matches('[data-file="image"]')){const f=e.target.files?.[0];e.target.value='';if(f)this.addImage(f)}if(e.target.matches('[data-file="json"]')){const f=e.target.files?.[0];e.target.value='';if(f)this.importFile(f)}},{signal:s});
 this.stage.addEventListener('dragover',e=>{if(!this.locked&&e.dataTransfer?.types.includes('Files')){e.preventDefault();this.stage.classList.add('is-file-over')}},{signal:s});this.stage.addEventListener('dragleave',()=>this.stage.classList.remove('is-file-over'),{signal:s});this.stage.addEventListener('drop',e=>{this.stage.classList.remove('is-file-over');if(!this.locked&&e.dataTransfer?.files.length){e.preventDefault();this.addImage(e.dataTransfer.files[0],this.point(e));}},{signal:s});
 this.dialog.addEventListener('cancel',e=>{e.preventDefault();if(this.editing)this.finishEdit(false);else if(this.gesture)this.cancelGesture();else this.fullscreen(false)},{signal:s});
 document.addEventListener('pointerdown',e=>{if(!this.contains(e.target))this.finishEdit(true)},{signal:s});
 }
 render(){if(!this.shell)return;this.shell.dataset.readonly=String(this.readOnly);this.shell.dataset.view=this.mode;this.shell.dataset.state=this.state;this.shell.querySelector('.wb-title').textContent=this._data.title;this.statusEl.textContent=this.conflict?'Конфликт версий':this.pending?'Ожидание подтверждения':this.readOnly?'Только просмотр':this.controlled?(this.storageStatus||'Изменения подтверждаются приложением'):(this.storageStatus||'Локальная доска. Сервер не подключён');
 const notice=this.shell.querySelector('.wb-notice');notice.hidden=!(this.error||this.pending||this.conflict);notice.innerHTML=this.conflict?`<span>${icon('warning',18)} ${esc(this.error)}</span>${btn('export-conflict','Экспортировать мою копию','download')}${btn('discard','Принять внешнюю версию','check')}`:this.pending?`<span>Изменение ещё не подтверждено приложением.</span>${btn('cancel-pending','Отменить','undo')}`:this.error?`<span>${icon('xCircle',18)} ${esc(this.error)}</span>${this.retryValue?btn('retry','Повторить','refresh'):''}${btn('dismiss','Закрыть','x','',false)}`:'';
 this.shell.querySelector('[data-wb-action=undo]').disabled=!this.history.length||this.locked;this.shell.querySelector('[data-wb-action=redo]').disabled=!this.future.length||this.locked;
 this.shell.querySelectorAll('.wb-tool[data-tool]').forEach(el=>{el.setAttribute('aria-pressed',String(this.tool===el.dataset.tool));el.disabled=this.locked&&!['select','hand'].includes(el.dataset.tool)});
 for(const action of ['quick-note','bulk','image','rename'])this.shell.querySelectorAll(`[data-wb-action=${action}]`).forEach(b=>b.disabled=this.locked);
 this.stage.dataset.canvasTool=this.tool;const listToggle=this.shell.querySelector('[data-wb-action=list] span');if(listToggle)listToggle.textContent=this.mode==='list'?'Холст':'Список';this.updateScene();this.renderSelection();this.updateViewport(false);this.renderPanel();this.renderMode();
 const surface=this.shell.querySelector('.wb-state-surface');surface.hidden=this.state==='ready';surface.innerHTML=this.state==='loading'?`<div class="wb-loading-symbol" aria-hidden="true">${icon('refresh',28)}</div><h3>Загружаем доску</h3><p>Объекты появятся после получения данных.</p>`:this.state==='error'?`<span class="wb-state-error">${icon('xCircle',28)}</span><h3>Не удалось загрузить доску</h3><p>Повторите запрос. Сохранённые данные не удалены.</p>${btn('reload','Повторить','refresh')}`:'';
 this.objectsEl.hidden=this.state!=='ready';this.svg.hidden=this.state!=='ready';this.stage.setAttribute('aria-busy',String(this.state==='loading'));
 const empty=this.shell.querySelector('.wb-empty');empty.hidden=this.data.objects.length>0||this.state!=='ready'||this.mode==='list';
 this.stage.hidden=this.mode==='list'&&this.state==='ready';this.listEl.hidden=this.mode!=='list'||this.state!=='ready';if(this.mode==='list'&&this.state==='ready')this.renderList();
 }
 updateScene(preview){if(!this.objectsEl)return;const scene=preview||this.data,keep=new Set(scene.objects.map(o=>o.id));for(const el of [...this.objectsEl.children])if(!keep.has(el.dataset.object))el.remove();
 const existing=new Map([...this.objectsEl.children].map(e=>[e.dataset.object,e]));const ordered=[...scene.objects.filter(o=>o.type==='frame'),...scene.objects.filter(o=>o.type!=='frame')];
 for(const o of ordered){let el=existing.get(o.id);if(!el){el=document.createElement('div');el.dataset.object=o.id;el.className='wb-object';el.tabIndex=0;el.setAttribute('role','group');this.objectsEl.append(el)}
 el.dataset.type=o.type;el.dataset.color=o.color;el.dataset.shape=o.shape||'rectangle';el.dataset.locked=String(B.isLocked(scene,o));el.style.left=o.x+'px';el.style.top=o.y+'px';el.style.width=o.width+'px';el.style.height=o.height+'px';
 const signature=json([o.text,o.author,o.done,o.type,o.src,o.shape,o.points,o.locked,o.owner]);
 if(el._signature!==signature&&this.editing?.id!==o.id){el._signature=signature;let content='';
 if(o.type==='frame')content=`<div class="wb-frame-head"><span class="wb-frame-number">${String(scene.objects.filter(n=>n.type==='frame').indexOf(o)+1).padStart(2,'0')}</span><span class="wb-object-text">${esc(o.text||'Новая рамка')}</span>${o.locked?icon('lock',14):btn('area-note','Добавить заметку в область','plus',`data-id="${o.id}"`,false)}</div>`;
 else if(o.type==='drawing')content=`<svg class="wb-drawing" viewBox="0 0 ${o.width} ${o.height}" preserveAspectRatio="none" aria-hidden="true"><polyline points="${o.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
 else if(o.type==='image')content=`<img src="${o.src}" alt="${esc(o.text||'Изображение на доске')}" draggable="false"><span class="wb-image-caption wb-object-text">${esc(o.text)}</span>`;
 else content=`${o.type==='task'?`<div class="wb-task-label">${icon(o.done?'checkCircle':'checklist',16)}<span>${o.done?'Сделано':'Следующий шаг'}</span></div>`:''}<div class="wb-object-text" data-placeholder="${o.type==='text'?'Заголовок':'Напишите мысль…'}">${esc(o.text)}</div>${o.type==='task'?`<div class="wb-task-owner">${icon('user',14)}<span>${esc(o.owner||'Назначьте ответственного')}</span><button type="button" class="wb-task-check" data-wb-action="task-toggle" data-id="${o.id}" aria-label="${o.done?'Вернуть в работу':'Завершить действие'}" aria-pressed="${!!o.done}" ${this.locked||B.isLocked(scene,o)?'disabled':''}>${icon(o.done?'checkCircle':'circle',18)}</button></div>`:''}${o.type==='sticky'?`<div class="wb-note-meta">${o.author?`<span>${esc(o.author)}</span>`:'<span></span>'}<span class="wb-vote-count"></span></div>`:''}`;
 el.innerHTML=content;
 }
 el.setAttribute('aria-label',`${labels[o.type]}: ${o.text?.slice(0,180)||'Без текста'}${B.isLocked(scene,o)?'. Заблокировано':''}${this.selection.includes(o.id)?'. Выбрано':''}`);el.setAttribute('aria-roledescription',labels[o.type]);
 const v=el.querySelector('.wb-vote-count');if(v)v.textContent=this.vote.counts[o.id]?`${this.vote.counts[o.id]} ${this.vote.counts[o.id]===1?'голос':'голоса'}`:'';
 }
 this.updateEdges(scene);}
 updateEdges(scene=this.data){const nodes=new Map(scene.objects.map(o=>[o.id,o]));const sig=json(scene.connections.map(e=>[e,nodes.get(e.from)?.text,nodes.get(e.to)?.text]));if(this.edgeSignature===sig&&this.edgeEls){for(const e of scene.connections){const el=this.edgeEls.get(e.id),a=nodes.get(e.from),b=nodes.get(e.to);if(el&&a&&b){const g=B.connectorGeometry(a,b,e.style);el.querySelectorAll('path').forEach(p=>p.setAttribute('d',g.path));const label=el.querySelector('text');if(label){label.setAttribute('x',g.x);label.setAttribute('y',g.y-12)}}}return;}this.edgeSignature=sig;this.svg.innerHTML=`<defs><marker id="${this.uid}-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M1 1 9 5 1 9" fill="none" stroke="context-stroke" stroke-width="1.5"/></marker></defs>`+scene.connections.map(e=>{const a=nodes.get(e.from),b=nodes.get(e.to);if(!a||!b)return'';const g=B.connectorGeometry(a,b,e.style);return`<g data-connection="${e.id}" tabindex="0" role="button" aria-label="${esc((a.text||labels[a.type])+' → '+(b.text||labels[b.type])+'. '+e.label)}" class="wb-connection ${this.selection.includes(e.id)?'is-selected':''}"><path class="wb-edge-hit" d="${g.path}"/><path class="wb-edge-line" d="${g.path}" ${e.arrow?`marker-end="url(#${this.uid}-arrow)"`:''}/>${e.label?`<text x="${g.x}" y="${g.y-12}" text-anchor="middle">${esc(e.label)}</text>`:''}</g>`}).join('');this.edgeEls=new Map([...this.svg.querySelectorAll('[data-connection]')].map(e=>[e.dataset.connection,e]));}
 renderSelection(){
 if(!this.shell||!this.objectsEl)return;const scene=this.data,byId=new Map(scene.objects.map(o=>[o.id,o]));this._selection=this.selection.filter(k=>byId.has(k)||scene.connections.some(e=>e.id===k));
 this.objectsEl.querySelectorAll('[data-object]').forEach(el=>{const yes=this.selection.includes(el.dataset.object);el.classList.toggle('is-selected',yes);el.classList.toggle('is-connect-source',this.linkFrom===el.dataset.object);el.querySelectorAll('.wb-resize').forEach(n=>n.remove());const o=byId.get(el.dataset.object);if(yes&&!this.locked&&!B.isLocked(scene,o)&&o.type!=='drawing'&&!this.editing)el.insertAdjacentHTML('beforeend',`<button class="wb-resize" type="button" data-resize="${o.id}" aria-label="Изменить размер. Alt и стрелки — с клавиатуры." title="Изменить размер"></button>`)});
 this.svg.querySelectorAll('[data-connection]').forEach(el=>el.classList.toggle('is-selected',this.selection.includes(el.dataset.connection)));
 this.context.hidden=!this.selection.length||this.state!=='ready'||this.tool==='connect';
 this.shell.querySelector('.wb-idle-context').hidden=!this.context.hidden;
 if(this.context.hidden){this.renderMode();return;}
 const objs=scene.objects.filter(o=>this.selection.includes(o.id)),edge=scene.connections.find(e=>this.selection.includes(e.id));const allLocked=objs.length&&objs.every(o=>B.isLocked(scene,o));
 if(this.editing){this.context.innerHTML=`<span class="wb-selection-count">Редактирование</span><span class="wb-edit-hint">Enter — новая строка</span>${btn('finish-edit','Готово','check')}${this.data.objects.find(o=>o.id===this.editing.id)?.type==='sticky'?btn('edit-next','Ещё заметка','plus'):''}${btn('cancel-edit','Отменить ввод','x')}`;return;}
 const single=objs.length===1?objs[0]:null;
 this.context.innerHTML=`<span class="wb-selection-count">${edge?'Связь':single?labels[single.type]:`Выбрано: ${objs.length}`}${allLocked?' / зафиксировано':''}</span>${edge?btn('edge-edit','Подпись','pencil'):single&&single.type!=='drawing'?btn('edit','Изменить','pencil'):''}${objs.some(o=>o.type==='sticky')?`<button type="button" class="wb-button" data-wb-action="appearance"><i class="wb-color-dot" data-color="${objs[0]?.color}"></i><span>Цвет</span></button>`:''}${objs.length>1?btn('arrange','Упорядочить','grid')+btn('frame-selection','В область','board'):''}${single&&single.type!=='frame'?btn('connect-selected','Связать','link'):''}${single?.type==='frame'?btn('area-note','Заметка в область','plus',`data-id="${single.id}"`):''}${single?.type==='shape'?btn('quick-next','Следующий блок','plus'):''}${single?.type==='sticky'?btn('make-action','В действие','checklist'):''}${this.vote.active&&single?.type==='sticky'?btn('vote','Голос +1','plus')+btn('unvote','Убрать голос','minus','',false):''}${btn('selection-more','Ещё','more')}`;
 this.context.querySelectorAll('button').forEach(b=>b.disabled=this.locked||(allLocked&&!['selection-more'].includes(b.dataset.wbAction)));
 this.renderMode();
 }
 updateViewport(emit=true){if(!this.world)return;const v=this._viewport;v.x=B.bounded(v.x,-1000000,1000000);v.y=B.bounded(v.y,-1000000,1000000);this.world.style.transform=`translate(${v.x}px,${v.y}px) scale(${v.zoom})`;this.stage.style.setProperty('--wb-dot-size',24*v.zoom+'px');this.stage.style.backgroundPosition=`${v.x}px ${v.y}px`;this.shell.querySelector('.wb-zoom-label').textContent=Math.round(v.zoom*100)+'%';if(emit)this.emit('iq-viewport',this.viewport);}
 queueViewport(){if(this.drawFrame)return;this.drawFrame=requestAnimationFrame(()=>{this.drawFrame=0;this.updateViewport();})}
 select(ids,announce=true){this.finishEdit(true);this._selection=[...new Set(ids)];this.renderSelection();if(this.mode==='list')this.renderList();this.emit('iq-selection',{ids:this.selection});if(announce)this.announce(this.selection.length?`Выбрано объектов: ${this.selection.length}`:'Выделение снято')}
 point(e){const r=this.stage.getBoundingClientRect(),v=this.viewport;return{x:(e.clientX-r.left-v.x)/v.zoom,y:(e.clientY-r.top-v.y)/v.zoom}}
 center(){return{x:(this.stage.clientWidth/2-this.viewport.x)/this.viewport.zoom,y:(this.stage.clientHeight/2-this.viewport.y)/this.viewport.zoom}}
 fit(ids){if(this.mode==='list')return;const obs=B.fitTargets(this.data,ids);this._viewport=B.fitViewport(obs,Math.max(240,this.stage.clientWidth),Math.max(240,this.stage.clientHeight),56);this.updateViewport();}
 zoomBy(factor){const s=this.stage;this._viewport=B.zoomAt(this.viewport,this.viewport.zoom*factor,s.clientWidth/2,s.clientHeight/2);this.updateViewport();}
 commit(next,reason='edit',historyAction=null){if(this.locked)return false;next=B.validateBoard(next);if(json({...next,revision:0})===json({...this._data,revision:0}))return true;this.error='';this.retryValue=null;
 if(this.controlled){const token=++this.generation,base=this._data.revision;this.pending={value:next,reason,base,historyAction,requestId:token};this.render();let settled=false;const valid=()=>!settled&&token===this.generation&&this.pending?.base===base&&this.isConnected;this.emit('iq-change-request',{requestId:token,baseRevision:base,value:B.clone(next),reason,accept:(value)=>{if(!valid())return false;const accepted=B.validateBoard(value||{...next,revision:base+1});if(accepted.revision<=base)throw new RangeError('Подтверждённая revision должна быть больше baseRevision');settled=true;if(historyAction==='undo'){this.history.pop();this.future.push(B.clone(this._data));}else if(historyAction==='redo'){this.future.pop();this.history.push(B.clone(this._data));}else{this.history.push(B.clone(this._data));this.future=[];}this.history=this.history.slice(-60);this._data=accepted;this.pending=null;this.render();this.emit('iq-change',{value:this.data,reason});return true;},reject:(message='Изменение не принято. Можно повторить.')=>{if(!valid())return false;settled=true;this.retryValue=B.clone(next);this.pending=null;this.error=String(message);this.render();return true;}});return true;}
 if(!historyAction){this.history.push(B.clone(this._data));this.history=this.history.slice(-60);this.future=[];}next.revision=this._data.revision+1;this._data=next;this.render();this.emit('iq-change',{value:this.data,reason});return true;
 }
 cancelPending(){if(!this.pending)return;const {requestId,base}=this.pending;this.generation++;this.pending=null;this.error='';this.render();this.emit('iq-change-cancel',{requestId,baseRevision:base});this.announce('Изменение отменено');}
 undo(){if(!this.history.length||this.locked)return;this.finishEdit(true);const next=this.history[this.history.length-1];if(this.controlled){this.commit(next,'undo','undo');return;}this.history.pop();this.future.push(B.clone(this._data));this.commit(next,'undo',true);this.announce('Последнее действие отменено')}
 redo(){if(!this.future.length||this.locked)return;const next=this.future[this.future.length-1];if(this.controlled){this.commit(next,'redo','redo');return;}this.future.pop();this.history.push(B.clone(this._data));this.commit(next,'redo',true);this.announce('Действие повторено')}
 add(type,x,y,text){if(this.locked)return;const p=this.center(),o=B.createObject(type,x??p.x-104,y??p.y-82,text||'',this.color);o.shape=type==='shape'?this.shape:undefined;let next=this.data;next.objects.push(o);next=B.assignFrames(next,[o.id]);if(this.commit(next,'add')){this.tool='select';this.select([o.id],false);this.render();if(type!=='image'&&type!=='drawing')this.edit(o.id);this.announce(`${labels[type]} добавлена`)}return o.id;}
 edit(id){if(this.locked)return;const o=this.data.objects.find(o=>o.id===id);if(!o||B.isLocked(this.data,o)||o.type==='drawing')return;this.finishEdit(true);if(this.mode==='list'){this.openEditSheet(o);return}const el=this.objectsEl.querySelector(`[data-object="${id}"]`),text=el?.querySelector('.wb-object-text');if(!text)return;
 this._selection=[id];this.editing={id,original:o.text,height:o.height,textEl:text};text.contentEditable='true';text.setAttribute('role','textbox');text.setAttribute('aria-label',`Текст: ${labels[o.type]}`);text.setAttribute('aria-multiline','true');text.spellcheck=true;el.classList.add('is-editing');this.renderSelection();text.focus();const range=document.createRange();range.selectNodeContents(text);range.collapse(false);getSelection().removeAllRanges();getSelection().addRange(range);
 text.oninput=()=>{if(o.type==='frame'||o.type==='image')return;el.style.height=Math.max(o.height,U.textHeight({...o,text:text.innerText}),text.scrollHeight+(o.type==='task'?96:o.type==='sticky'?64:40))+'px';};text.onblur=()=>{queueMicrotask(()=>{if(this.editing?.textEl===text&&document.activeElement!==text)this.finishEdit(true)})};
 }
 editDraft(){const next=this.data,ed=this.editing;if(!ed)return next;const o=next.objects.find(n=>n.id===ed.id);if(o)o.text=(ed.textEl.innerText??ed.textEl.textContent).slice(0,10000);return next;}
 finishEdit(save){const ed=this.editing;if(!ed)return;this.editing=null;const t=ed.textEl;textEditableOff(t);const node=t.closest('[data-object]');node?.classList.remove('is-editing');const next=this.data,o=next.objects.find(o=>o.id===ed.id);if(save&&o){o.text=(t.innerText??t.textContent).slice(0,10000).replace(/\n$/,'');if(!['frame','image'].includes(o.type))o.height=Math.max(64,parseFloat(node.style.height)||o.height);if(o.parentId){const f=next.objects.find(n=>n.id===o.parentId);if(f&&!f.locked)f.height=Math.max(f.height,o.y+o.height-f.y+24)}this.commit(next,'text')}else {if(node)node._signature=null;this.updateScene();}this.renderSelection();}
 openEditSheet(o){this.openSheet(o.type==='frame'?'Название области':o.type==='task'?'Следующий шаг':'Изменить '+labels[o.type].toLowerCase(),`<label>${o.type==='frame'?'Название':'Текст'}<textarea name="text" rows="${o.type==='frame'?2:5}" maxlength="10000">${esc(o.text)}</textarea></label>${o.type==='task'?`<label>Ответственный<input name="owner" maxlength="100" value="${esc(o.owner||'')}" placeholder="Имя или команда"></label><label class="wb-checkbox"><input type="checkbox" name="done" ${o.done?'checked':''}>Готово</label>`:''}`,form=>{const next=this.data,n=next.objects.find(n=>n.id===o.id);if(!n)throw new Error('Объект больше не существует');if(B.isLocked(next,n))throw new Error('Объект зафиксирован');n.text=form.elements.namedItem('text').value;if(o.type==='task'){n.owner=form.elements.namedItem('owner').value;n.done=form.elements.namedItem('done').checked;}n.height=Math.max(n.height,U.textHeight(n));this.commit(next,'edit-content')});}
 begin(e){if(e.isPrimary===false||this.gesture)return;if(e.button!==0&&e.button!==1)return;const inside=e.target.closest('.wb-stage');if(!inside)return;if(inputTarget(e)||e.target.closest('.wb-empty,.wb-state-surface'))return;if(e.target.closest('button')&&!e.target.closest('[data-resize]'))return;this.stage.focus({preventScroll:true});this.finishEdit(true);
 const object=e.target.closest('[data-object]'),id=object?.dataset.object,edge=e.target.closest('[data-connection]');
 if(this.tool==='connect'&&id){e.preventDefault();if(!this.linkFrom){this.linkFrom=id;this.select([id]);this.announce('Теперь выберите объект, к которому нужна связь')}else{if(this.connect(this.linkFrom,id)){this.linkFrom=null;this.tool='select';this.render();}else this.renderMode();}return;}
 if(edge){this.select([edge.dataset.connection]);return;}
 const p=this.point(e),pan=this.tool==='hand'||this.space||e.button===1;
 if(!pan&&!id&&['sticky','text','shape'].includes(this.tool)){e.preventDefault();this.add(this.tool,p.x,p.y);return;}
 if(this.state!=='ready')return;
 const original=this.data;let kind='lasso',ids=[];
 if(pan)kind='pan';else if(e.target.closest('[data-resize]')){if(this.locked)return;kind='resize';ids=[id];}
 else if(!id&&this.tool==='frame'&&!this.locked)kind='frame';
 else if(id){if(e.shiftKey){this.select(this.selection.includes(id)?this.selection.filter(k=>k!==id):[...this.selection,id]);return}if(!this.selection.includes(id))this.select([id],false);ids=[...B.mutableFamily(original,this.selection)];if(this.locked||!ids.length)return;kind='move';}
 const startSelection=this.selection;if(kind==='lasso'&&!e.shiftKey)this.select([],false);e.preventDefault();this.gesture={kind,ids,original,start:p,client:{x:e.clientX,y:e.clientY},viewport:this.viewport,selection:startSelection,additive:e.shiftKey,points:[[p.x,p.y]],moved:false,pointerId:e.pointerId};
 this.gestureEvents?.abort();this.gestureEvents=new AbortController();const s=this.gestureEvents.signal;
 window.addEventListener('pointermove',ev=>this.move(ev),{signal:s});window.addEventListener('pointerup',ev=>this.end(ev),{signal:s});window.addEventListener('pointercancel',()=>this.cancelGesture(),{signal:s});this.stage.classList.add('is-interacting');
 }
 move(e){const g=this.gesture;if(!g||e.pointerId!==g.pointerId)return;g.last={clientX:e.clientX,clientY:e.clientY};if(Math.hypot(e.clientX-g.client.x,e.clientY-g.client.y)>3)g.moved=true;if(!g.moved)return;if(!g.captured){try{this.stage.setPointerCapture?.(e.pointerId);g.captured=true}catch{}}
 if(g.kind==='pan'){this._viewport={...g.viewport,x:g.viewport.x+e.clientX-g.client.x,y:g.viewport.y+e.clientY-g.client.y};this.queueViewport();return;}
 const p=this.point(e),dx=p.x-g.start.x,dy=p.y-g.start.y;g.end=p;
 if(g.kind==='move'){g.offset={dx,dy};g.preview={...g.original,objects:g.original.objects.map(o=>g.ids.includes(o.id)?{...o,x:B.bounded(o.x+dx,-100000,100000),y:B.bounded(o.y+dy,-100000,100000)}:o)};this.paintGesture(g);}
 if(g.kind==='resize'){const next=B.clone(g.original),o=next.objects.find(o=>o.id===g.ids[0]);o.width=B.bounded(o.width+dx,o.type==='frame'?200:100,4000);o.height=B.bounded(o.height+dy,o.type==='frame'?160:64,4000);g.preview=next;this.paintGesture(g);}
 if(['lasso','frame'].includes(g.kind)){const r={x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),width:Math.abs(dx),height:Math.abs(dy)};g.rect=r;const v=this.viewport,m=this.shell.querySelector('.wb-marquee');m.hidden=false;Object.assign(m.style,{left:(r.x*v.zoom+v.x)+'px',top:(r.y*v.zoom+v.y)+'px',width:r.width*v.zoom+'px',height:r.height*v.zoom+'px'});}
 if(g.kind==='draw'){if(g.points.length<4000){const last=g.points[g.points.length-1];if(Math.hypot(p.x-last[0],p.y-last[1])>2)this.gesture.points.push([p.x,p.y])}this.svg.querySelector('[data-live-drawing]')?.remove();this.svg.insertAdjacentHTML('beforeend',`<polyline data-live-drawing points="${g.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="var(--iq-ink)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>`);}
 }
 paintGesture(g){if(this.drawFrame)return;this.drawFrame=requestAnimationFrame(()=>{this.drawFrame=0;if(this.gesture!==g)return;const by=new Map(g.preview.objects.map(o=>[o.id,o]));for(const id of g.ids){const n=by.get(id),el=this.objectsEl.querySelector(`[data-object="${id}"]`);if(n&&el){Object.assign(el.style,{left:n.x+'px',top:n.y+'px',width:n.width+'px',height:n.height+'px'})}}this.updateEdges(g.preview);})}
 end(e){const g=this.gesture;if(!g||e.pointerId!==g.pointerId)return;this.gesture=null;this.gestureEvents?.abort();cancelAnimationFrame(this.drawFrame);this.drawFrame=0;this.stage.classList.remove('is-interacting');this.shell.querySelector('.wb-marquee').hidden=true;try{this.stage.releasePointerCapture?.(e.pointerId)}catch{}
 if(!g.moved){if(g.kind==='lasso')this.select([],false);return;}
 if(g.kind==='move'&&g.preview)this.commit(B.assignFrames(g.preview,g.ids),'move');
 if(g.kind==='resize'&&g.preview)this.commit(g.preview,'resize');
 if(g.kind==='lasso'&&g.rect){const r=g.rect;this.select([...(g.additive?g.selection:[]),...g.original.objects.filter(o=>o.type!=='frame'&&o.x<r.x+r.width&&o.x+o.width>r.x&&o.y<r.y+r.height&&o.y+o.height>r.y).map(o=>o.id)]);}
 if(g.kind==='frame'&&g.rect){const r=g.rect;if(r.width>60&&r.height>60){const o=B.createObject('frame',r.x,r.y,'Новая рамка');o.width=Math.max(200,r.width);o.height=Math.max(160,r.height);const next=g.original;next.objects.unshift(o);this.commit(B.assignFrames(next,next.objects.filter(n=>n.type!=='frame').map(n=>n.id)),'frame');this.tool='select';this.select([o.id]);this.edit(o.id);}}
 if(g.kind==='draw'){this.svg.querySelector('[data-live-drawing]')?.remove();const points=g.points;if(points.length>1){const minX=Math.min(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),w=Math.max(40,Math.max(...points.map(p=>p[0]))-minX),h=Math.max(32,Math.max(...points.map(p=>p[1]))-minY);const o={id:B.newId('drawing'),type:'drawing',x:minX,y:minY,width:w,height:h,points:points.map(p=>[p[0]-minX,p[1]-minY]),text:'Рисунок',color:'neutral'};const next=this.data;next.objects.push(o);this.commit(next,'draw')}}
 this.render();
 }
 cancelGesture(){if(!this.gesture)return;try{this.stage?.releasePointerCapture(this.gesture.pointerId)}catch{}this.gestureEvents?.abort();this.gesture=null;cancelAnimationFrame(this.drawFrame);this.drawFrame=0;this.stage?.classList.remove('is-interacting');const m=this.shell?.querySelector('.wb-marquee');if(m)m.hidden=true;this.svg?.querySelector('[data-live-drawing]')?.remove();this.updateScene();this.announce('Перемещение отменено');}
 connect(from,to,label=''){if(this.locked||from===to)return false;const next=this.data;if(!next.objects.some(o=>o.id===from)||!next.objects.some(o=>o.id===to)||next.connections.some(e=>e.from===from&&e.to===to)){this.announce('Такая связь уже есть или её нельзя создать');return false}const e={id:B.newId('edge'),from,to,label,style:'curve',arrow:true};next.connections.push(e);this.commit(next,'connect');this.select([e.id],false);return true;}
 key(e){if(e.defaultPrevented||e.isComposing)return;const input=inputTarget(e);if(this.editing&&input){if(e.key==='Escape'){e.preventDefault();this.finishEdit(false);this.stage.focus()}else if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();const id=this.editing.id;this.finishEdit(true);const o=this.data.objects.find(o=>o.id===id);if(o?.type==='sticky'&&!e.shiftKey)this.addQuick('sticky',o.parentId);else this.stage.focus()}return}if(input)return;
 const mod=e.ctrlKey||e.metaKey;
 if(e.key==='Escape'){if(this.gesture)this.cancelGesture();else if(this.linkFrom){this.linkFrom=null;this.tool='select';this.render()}else if(this.tool!=='select'){this.tool='select';this.linkFrom=null;this.render()}else if(this.panel){this.panel='';this.renderPanel()}else if(this.pending)this.cancelPending();else if(this.dialog.open)this.fullscreen(false);else this.select([]);e.preventDefault();return;}
 if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo();return}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();this.redo();return}if(mod&&e.key.toLowerCase()==='a'){e.preventDefault();this.select(this.data.objects.filter(o=>o.type!=='frame').map(o=>o.id));return}if(mod&&e.key.toLowerCase()==='g'){e.preventDefault();this.action('frame-selection');return}if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();this.action('duplicate');return}
 if(e.key==='Delete'||e.key==='Backspace'){if(!this.locked&&this.selection.length){e.preventDefault();this.action('delete')}return}
 if(e.target.closest('.wb-sheet,.wb-panel,header,footer,.wb-context,.wb-rail'))return;
 if(e.code==='Space'){e.preventDefault();this.space=true;this.stage.classList.add('is-pan');return}
 if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&this.selection.length&&!this.locked){e.preventDefault();const amount=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-amount:e.key==='ArrowRight'?amount:0,dy=e.key==='ArrowUp'?-amount:e.key==='ArrowDown'?amount:0;if(e.altKey){const next=this.data;next.objects.forEach(o=>{if(this.selection.includes(o.id)&&!B.isLocked(next,o)){o.width=Math.max(100,o.width+dx);o.height=Math.max(64,o.height+dy)}});this.commit(next,'resize-keyboard')}else this.commit(B.assignFrames(B.translate(this.data,this.selection,dx,dy),this.selection),'move-keyboard');return}
 if(e.key==='Enter'&&this.selection.length===1){e.preventDefault();const edge=this.data.connections.find(n=>n.id===this.selection[0]);if(edge)this.action('edge-edit');else this.edit(this.selection[0]);return;}
 if(e.key==='0'){e.preventDefault();e.shiftKey?this.fit(this.selection):this.fit();return}if(e.key==='+'||e.key==='='){e.preventDefault();this.zoomBy(1.15);return}if(e.key==='-'){e.preventDefault();this.zoomBy(1/1.15);return}
 if(!mod&&['n','т'].includes(e.key.toLowerCase())){e.preventDefault();this.setTool('sticky');return;}
 const target=toolList.find(([, , ,k])=>k.toLowerCase()===e.key.toLowerCase());if(target&&!mod){e.preventDefault();this.setTool(target[0]);return;}

 }
 click(e){const tool=e.target.closest('.wb-tool[data-tool]');if(tool){this.setTool(tool.dataset.tool);return}const action=e.target.closest('[data-wb-action]');if(action&&!action.disabled){e.preventDefault();if(!['cancel-edit','finish-edit','edit-next'].includes(action.dataset.wbAction))this.finishEdit(true);try{this.action(action.dataset.wbAction,action)}catch(ex){this.error=ex.message;this.render()}return}
 const row=e.target.closest('[data-list-object]');if(row){this.select([row.dataset.listObject]);return}const edge=e.target.closest('[data-connection]');if(edge)this.select([edge.dataset.connection]);
 }
 setTool(t){if(this.locked&&!['select','hand'].includes(t))return;this.tool=t;this.linkFrom=null;this.render();this.stage.focus({preventScroll:true});this.announce(t==='connect'?'Выберите два объекта по очереди':toolList.find(x=>x[0]===t)?.[1]||t)}
 action(action,el){const scene=this.data,obs=scene.objects.filter(o=>this.selection.includes(o.id));
 const mutation=['delete','duplicate','tidy','frame-selection','color','edit','edge-edit','shape-cycle','quick-next','to-task','lock','bulk','image','unframe'];if(this.locked&&mutation.includes(action))return;
 if(this.experienceAction(action,el))return;
 switch(action){
 case'edit':this.edit(this.selection[0]);break;
 case'delete':this.commit(B.remove(scene,this.selection),'delete');this.select([]);break;
 case'duplicate':{const r=B.duplicate(scene,this.selection);this.commit(r.value,'duplicate');this.select(r.ids);break}
 case'unframe':{const frame=obs[0];if(frame?.type==='frame'&&!B.isLocked(scene,frame)){scene.objects=scene.objects.filter(o=>o.id!==frame.id);scene.objects.forEach(o=>{if(o.parentId===frame.id){if(frame.parentId)o.parentId=frame.parentId;else delete o.parentId}});scene.connections=scene.connections.filter(e=>e.from!==frame.id&&e.to!==frame.id);this.commit(scene,'unframe');this.select([])}break;}
 case'tidy':this.commit(B.tidy(scene,this.selection),'tidy');break;
 case'align-left':this.commit(B.align(scene,this.selection,'left'),'align');break;
 case'frame-selection':{const r=B.enclose(scene,this.selection,'Тема обсуждения');if(r.id){this.commit(r.value,'frame-selection');this.select([r.id])}break}
 case'color':this.color=el.dataset.color;scene.objects.forEach(o=>{if(this.selection.includes(o.id)&&o.type==='sticky'&&!B.isLocked(scene,o))o.color=this.color});this.commit(scene,'color');break;
 case'lock':{const unlock=obs.every(o=>o.locked);scene.objects.forEach(o=>{if(this.selection.includes(o.id))o.locked=!unlock});this.commit(scene,'lock');break}
 case'shape-cycle':if(obs[0]){obs[0].shape=B.SHAPES[(B.SHAPES.indexOf(obs[0].shape)+1)%3];this.commit(scene,'shape')}break;
 case'quick-next':if(obs[0]){const first=obs[0],o=B.createObject('shape',first.x+first.width+100,first.y,'Следующий шаг');scene.objects.push(o);scene.connections.push({id:B.newId('e'),from:first.id,to:o.id,label:'',style:'curve',arrow:true});this.commit(scene,'quick-next');this.select([o.id]);this.edit(o.id)}break;
 case'to-task':if(obs[0]){obs[0].type='task';obs[0].color='neutral';obs[0].width=Math.max(248,obs[0].width);this.commit(scene,'to-action')}break;
 case'undo':this.undo();break;case'redo':this.redo();break;
 case'zoom-in':this.zoomBy(1.15);break;case'zoom-out':this.zoomBy(1/1.15);break;case'reset-zoom':this._viewport=B.zoomAt(this.viewport,1,this.stage.clientWidth/2,this.stage.clientHeight/2);this.updateViewport();break;case'fit':this.fit();break;
 case'fullscreen':this.fullscreen(!this.dialog.open);break;
 case'list':this.mode=this.mode==='list'?'canvas':'list';this.render();if(this.mode==='canvas')this.fit();break;
 case'frames':case'templates':case'session':case'menu':case'help':this.panel=this.panel===action?'':action;this.renderPanel();break;
 case'panel-close':this.panel='';this.renderPanel();break;
 case'goto-frame':if(this.mode==='list')this.listEl.querySelector(`[data-list-object="${el.dataset.id}"]`)?.scrollIntoView({block:'start'});else this.fit([el.dataset.id]);this.select([el.dataset.id]);if(this.stage.clientWidth<500){this.panel='';this.renderPanel()}break;
 case'insert-template':{const t=this._templates.find(t=>t.id===el.dataset.id);if(t){if(this.locked)return;const b=B.bounds(scene.objects);const r=B.insertScene(scene,t.data,scene.objects.length?b.x+b.width+100:40,40);this.commit(r.value,'insert-template');this.panel='';this.renderPanel();this.fit(r.ids);this.select([]);this.announce('Шаблон добавлен рядом. Прежние записи сохранены; можно отменить.');}break;}
 case'bulk':this.openSheet('Несколько идей за один раз',`<p>Одна строка — одна заметка. Можно вставить список из документа.</p><label>Идеи<textarea name="ideas" rows="7" placeholder="Показывать результат до настройки\nСократить первый сценарий\nОбъяснить следующий шаг" required></textarea></label>`,form=>{const p=this.center(),objects=B.bulkObjects(form.elements.namedItem("ideas").value,p.x-220,p.y-160,this.color);const next=this.data;next.objects.push(...objects);this.commit(B.assignFrames(next,objects.map(o=>o.id)),'bulk');this.select(objects.map(o=>o.id));this.fit(objects.map(o=>o.id));},'Добавить заметки');break;
 case'rename':this.openSheet('Название доски',`<label>Название<input name="title" maxlength="160" value="${esc(scene.title)}" required></label>`,form=>this.commit({...this.data,title:form.elements.namedItem("title").value},'rename'));break;
 case'edge-edit':{const edge=scene.connections.find(e=>e.id===this.selection[0]);if(edge)this.openSheet('Связь между объектами',`<label>Подпись<input name="label" maxlength="240" value="${esc(edge.label)}"></label><label>Линия<select name="style"><option value="curve" ${edge.style==='curve'?'selected':''}>Плавная</option><option value="elbow" ${edge.style==='elbow'?'selected':''}>Ломаная</option><option value="straight" ${edge.style==='straight'?'selected':''}>Прямая</option></select></label><label class="wb-checkbox"><input type="checkbox" name="arrow" ${edge.arrow?'checked':''}>Показывать направление</label>`,form=>{Object.assign(edge,{label:form.elements.namedItem("label").value,style:form.elements.namedItem("style").value,arrow:form.elements.namedItem("arrow").checked});this.commit(scene,'edit-connection')});break;}
 case'connect-form':this.openConnectSheet();break;
 case'image':this.querySelector('[data-file=image]').click();break;case'import':this.querySelector('[data-file=json]').click();break;case'export':this.download(this.data);break;case'export-conflict':if(this.conflict)this.download(this.conflict);break;
 case'discard':this.conflict=null;this.error='';this.render();break;case'dismiss':this.error='';this.retryValue=null;this.render();break;case'cancel-pending':this.cancelPending();break;case'retry':{const n=this.retryValue;this.error='';this.retryValue=null;if(n)this.commit(n,'retry');break}case'reload':this.emit('iq-retry',{});break;
 case'clear':this.openSheet('Очистить доску?',`<p>Все объекты будут удалены. В этой сессии действие можно отменить.</p>`,()=>{this.commit({...B.blank(),title:this.data.title},'clear');this.select([])},'Очистить');break;
 case'exact':if(obs[0])this.openEditSheet(obs[0]);break;
 case'vote-start':this.vote={active:true,finished:false,limit:3,counts:{}};this.render();this.announce('Личный раунд. Выберите заметку и поставьте голос. Доступно три голоса.');break;
 case'vote-finish':this.vote.active=false;this.vote.finished=true;this.render();break;
 case'vote':case'unvote':{const id=this.selection[0],used=Object.values(this.vote.counts).reduce((s,n)=>s+n,0);if(!this.vote.active||!obs[0]||obs[0].type!=='sticky')break;if(action==='vote'&&used<this.vote.limit)this.vote.counts[id]=(this.vote.counts[id]||0)+1;else if(action==='unvote'&&this.vote.counts[id])this.vote.counts[id]--;else this.announce('Все три голоса использованы');this.emit('iq-vote',{objectId:id,votes:this.vote.counts[id]||0,local:true});this.render();break;}
 case'timer-start':if(!this.timer.running){this.timer.remaining=B.bounded(Number(this.panelEl.querySelector('[name=minutes]')?.value)||5,1,60)*60;this.timer.running=true;this.timer.end=Date.now()+this.timer.remaining*1000;this.timerId=setInterval(()=>this.tickTimer(),500);}this.renderPanel();break;
 case'timer-pause':this.timer.remaining=Math.max(0,Math.ceil((this.timer.end-Date.now())/1000));this.timer.running=false;clearInterval(this.timerId);this.renderPanel();break;
 case'timer-resume':this.timer.running=true;this.timer.end=Date.now()+this.timer.remaining*1000;this.timerId=setInterval(()=>this.tickTimer(),500);this.renderPanel();break;
 case'timer-reset':this.timer.running=false;this.timer.remaining=300;clearInterval(this.timerId);this.renderPanel();break;
 }
 }
 tickTimer(){this.timer.remaining=Math.max(0,Math.ceil((this.timer.end-Date.now())/1000));if(!this.timer.remaining){clearInterval(this.timerId);this.timer.running=false;this.announce('Время закончилось');this.renderPanel()}const el=this.panelEl?.querySelector('[data-timer-readout]');if(el)el.textContent=this.timerText();const hb=this.shell?.querySelector('[data-wb-action=session] span');if(hb)hb.textContent=this.timer.running?this.timerText():'Сессия';}
 timerText(){return`${String(Math.floor(this.timer.remaining/60)).padStart(2,'0')}:${String(this.timer.remaining%60).padStart(2,'0')}`}
 renderPanel(){if(!this.panelEl)return;this.panelEl.hidden=!this.panel;this.shell.classList.toggle('has-panel',!!this.panel);if(!this.panel)return;if(this.renderExperiencePanel())return;const names={frames:'Рамки доски',templates:'Начать со структуры',session:'Рабочая сессия',menu:'Доска и данные',help:'Быстрые действия'};let content='';
 if(this.panel==='frames'){const frames=this.data.objects.filter(o=>o.type==='frame');content=frames.length?frames.map((f,i)=>`<button class="wb-frame-jump" data-wb-action="goto-frame" data-id="${f.id}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${esc(f.text)}</b><small>${this.data.objects.filter(o=>o.parentId===f.id).length} объектов</small></div>${icon('upRight',16)}</button>`).join(''):`<p>Рамки собирают материалы в темы или этапы встречи. Выделите заметки и нажмите «В рамку».</p>`;}
 if(this.panel==='templates'){content=`<p>Добавим структуру рядом с вашими материалами. Ничего не удаляется.</p>`+(this._templates.length?this._templates.map(t=>`<button class="wb-template" data-wb-action="insert-template" data-id="${esc(t.id)}" ${this.locked?'disabled':''}><div class="wb-template-mini" aria-hidden="true">${t.data.objects.filter(o=>o.type==='sticky'||o.type==='shape').slice(0,6).map(o=>`<i data-color="${o.color}"></i>`).join('')}</div><b>${esc(t.title)}</b><small>${esc(t.description)}</small></button>`).join(''):'<p>Шаблоны задаются приложением через свойство templates.</p>');}
 if(this.panel==='session'){const used=Object.values(this.vote.counts).reduce((s,n)=>s+n,0);content=`<section><span class="wb-panel-kicker">ТАЙМБОКС</span><h4>Сначала — время подумать</h4><p>Локальный таймер. Он не синхронизирован с другими участниками.</p><div class="wb-timer" data-timer-readout>${this.timerText()}</div>${this.timer.running?btn('timer-pause','Пауза','pause'):this.timer.remaining!==300?btn('timer-resume','Продолжить','play'):`<label class="wb-timer-minutes">Минут<input name="minutes" type="number" min="1" max="60" value="5"></label>`+btn('timer-start','Начать','play')}${btn('timer-reset','Сбросить','refresh')}</section><section><span class="wb-panel-kicker">ВЫБОР ИДЕЙ</span><h4>${this.vote.active?`Использовано ${used} из 3`:'Три голоса на главное'}</h4><p>Личный раунд: в этом макете голосуете только вы. Выделите заметку — действие появится над доской.</p>${this.vote.active?btn('vote-finish','Показать результат','check'):btn('vote-start',this.vote.finished?'Новый раунд':'Начать выбор','star')}${this.vote.finished?`<ol class="wb-vote-results">${Object.entries(this.vote.counts).filter(([id,v])=>v&&this.exists(id)).sort((a,b)=>b[1]-a[1]).map(([id,n])=>`<li><b>${n}</b><span>${esc(this.data.objects.find(o=>o.id===id)?.text)}</span></li>`).join('')||'<li>Голосов пока нет.</li>'}</ol>`:''}</section>`;}
 if(this.panel==='menu')content=`${btn('export','Экспортировать JSON','download')}${btn('import','Добавить из JSON','upload',this.locked?'disabled':'')}${btn('connect-form','Связать без перетаскивания','link',this.locked?'disabled':'')}${this.selection.length?btn('exact','Точное положение и текст','sliders',this.locked?'disabled':''):''}${btn('clear','Очистить доску','trash',this.locked?'disabled':'')}<p>Файл содержит объекты и связи. Изображения включены в данные. Сервер не подключён.</p>`;
 if(this.panel==='help')content=`<p>Работайте прямо на доске. Панель свойств не нужна для каждой мысли.</p><dl class="wb-shortcuts">${[['S → щелчок','Новая заметка'],['Двойной щелчок','Редактировать текст'],['Ctrl/⌘ + Enter','Следующая заметка при вводе'],['Shift + щелчок','Добавить к выделению'],['Протянуть по фону','Выделить область'],['Пробел / H','Перемещать доску'],['Ctrl/⌘ + колёсико','Масштаб под указателем'],['Стрелки / Shift','Сдвиг на 1 / 10 px'],['Alt + стрелки','Изменить размер'],['Ctrl/⌘ + D','Дублировать'],['Ctrl/⌘ + Z','Отменить'],['0 / Shift + 0','Показать всё / выделение'],['Escape','Отменить жест или ввод']].map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('')}</dl><p>Вставьте несколько строк из буфера — они станут отдельными заметками. В режиме «Список» доступны те же объекты.</p>`;
 this.panelEl.innerHTML=`<header><h3>${names[this.panel]}</h3>${btn('panel-close','Закрыть панель','x','',false)}</header><div class="wb-panel-content">${content}</div>`;
 }
 renderList(){
 const ordered=[];const walk=parent=>{for(const o of this.data.objects.filter(o=>(o.parentId||'')===parent)){ordered.push(o);if(o.type==='frame')walk(o.id)}};walk('');
 this.listEl.innerHTML=`<div class="wb-list-header"><h3>Объекты доски</h3><span>${this.data.objects.length}</span>${btn('bulk','Добавить идеи','plus',this.locked?'disabled':'')}</div>${!ordered.length?`<div class="wb-list-empty"><h3>Запишите первую мысль</h3><p>Кнопка «Добавить заметку» создаст запись. Собрать темы можно позже.</p></div>`:''}`+ordered.map(o=>`<article class="wb-list-item ${this.selection.includes(o.id)?'is-selected':''} ${o.type==='frame'?'is-area':''}" data-list-object="${o.id}"><label class="wb-list-select"><input type="checkbox" data-list-select="${o.id}" aria-label="Выбрать ${esc((o.text||labels[o.type]).slice(0,100))}" ${this.selection.includes(o.id)?'checked':''}></label><div><small>${labels[o.type]}${o.parentId?' / '+esc(this.data.objects.find(f=>f.id===o.parentId)?.text||'Область'):''}</small><p>${esc(o.text||'Без текста')}</p>${o.type==='task'?`<span class="wb-list-relations">${o.done?'Готово':'В работе'}${o.owner?' / '+esc(o.owner):''}</span>`:''}<span class="wb-list-relations">${this.data.connections.filter(e=>e.from===o.id).map(e=>'→ '+esc(this.data.objects.find(n=>n.id===e.to)?.text||'Объект')).join('<br>')}</span></div><div class="wb-list-actions">${o.type==='frame'?btn('area-note','Добавить заметку в область','plus',`data-id="${o.id}" ${this.locked||B.isLocked(this.data,o)?'disabled':''}`,false):''}<button type="button" class="wb-button" data-list-edit="${o.id}" aria-label="Редактировать ${esc(o.text.slice(0,50))}" ${this.locked||B.isLocked(this.data,o)?'disabled':''}>${icon('pencil',18)}</button></div></article>`).join('');
 this.listEl.querySelectorAll('[data-list-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();this.select([b.dataset.listEdit],false);this.openEditSheet(this.data.objects.find(n=>n.id===b.dataset.listEdit));});
 this.listEl.querySelectorAll('[data-list-select]').forEach(b=>{b.onclick=e=>e.stopPropagation();b.onchange=()=>{const id=b.dataset.listSelect;this.select(b.checked?[...this.selection,id]:this.selection.filter(k=>k!==id));this.listEl.querySelector(`[data-list-select="${id}"]`)?.focus({preventScroll:true});};});
 }
 openSheet(title,content,accept,label='Применить'){this.finishEdit(true);this.querySelector('.wb-sheet')?.remove();const returnTo=document.activeElement,returnId=this.selection[0];const dialog=document.createElement('dialog');dialog.className='wb-sheet';dialog.innerHTML=`<form><header><h3>${esc(title)}</h3><button class="wb-button wb-icon-button" type="button" data-sheet-close aria-label="Закрыть">${icon('x',18)}</button></header><div class="wb-sheet-content">${content}</div><p class="wb-sheet-error" role="alert" hidden></p><footer><button class="wb-button" type="button" data-sheet-close>Отмена</button><button class="wb-button wb-primary" type="submit">${esc(label)}${icon('check',18)}</button></footer></form>`;this.append(dialog);dialog.querySelectorAll('[data-sheet-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.addEventListener('close',()=>{dialog.remove();if(returnTo?.isConnected&&!returnTo.disabled&&returnTo!==document.body)returnTo.focus({preventScroll:true});else if(this.mode==='list')(this.listEl.querySelector(`[data-list-select="${returnId}"]`)||this.listEl.querySelector('button'))?.focus({preventScroll:true});else this.stage.focus({preventScroll:true})});dialog.querySelector('form').onsubmit=e=>{e.preventDefault();try{if(this.locked)throw new Error('Доска недоступна для изменения');if(accept(e.target)!==false)dialog.close()}catch(ex){const error=dialog.querySelector('.wb-sheet-error');error.hidden=false;error.textContent=ex.message}};dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('input:not([type=checkbox]),textarea,select')?.focus());return dialog;}
 openConnectSheet(){const options=this.data.objects.filter(o=>o.type!=='frame').map(o=>`<option value="${o.id}">${esc(o.text||labels[o.type])}</option>`).join('');this.openSheet('Соединить объекты',`<label>Откуда<select name="from">${options}</select></label><label>Куда<select name="to">${options}</select></label><label>Подпись<input name="label" maxlength="240"></label>`,form=>{if(form.elements.namedItem("from").value===form.elements.namedItem("to").value)throw new Error('Выберите два разных объекта');if(!this.connect(form.elements.namedItem("from").value,form.elements.namedItem("to").value,form.elements.namedItem("label").value))throw new Error('Не удалось создать связь')},'Соединить');}
 fullscreen(open){this.finishEdit(true);this.cancelGesture();if(open&&!this.dialog.open){this.dialog.append(this.shell);this.dialog.showModal();this.shell.dataset.fullscreen='true';this.shell.querySelector('[data-wb-action=fullscreen]').innerHTML=icon('collapse',18);this.shell.querySelector('[data-wb-action=fullscreen]').setAttribute('aria-label','Свернуть доску');}else if(!open&&this.dialog.open){this.dialog.close();this.insertBefore(this.shell,this.dialog);delete this.shell.dataset.fullscreen;this.shell.querySelector('[data-wb-action=fullscreen]').innerHTML=icon('expand',18);this.shell.querySelector('[data-wb-action=fullscreen]').setAttribute('aria-label','Развернуть доску');}requestAnimationFrame(()=>this.stage.focus({preventScroll:true}));}
 async paste(e){if(inputTarget(e)||this.locked)return;const internal=e.clipboardData.getData('application/x-iquipage-board'),text=e.clipboardData.getData('text/plain'),file=[...e.clipboardData.files].find(f=>f.type.startsWith('image/'));if(!internal&&!text&&!file)return;e.preventDefault();try{if(file){await this.addImage(file);return}const p=this.center();if(internal){const r=B.insertScene(this.data,JSON.parse(internal),p.x-100,p.y-80);this.commit(r.value,'paste');this.select(r.ids)}else{const objects=B.bulkObjects(text,p.x-208,p.y-100,this.color),next=this.data;next.objects.push(...objects);this.commit(B.assignFrames(next,objects.map(o=>o.id)),'paste');this.select(objects.map(o=>o.id))}}catch(err){this.error=err.message;this.render()}}
 async addImage(file,point){if(this.locked)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){this.error='Выберите PNG, JPEG или WebP не больше 5 МБ.';this.render();return}const token=this.generation;try{const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Не удалось прочитать файл'));r.readAsDataURL(file)});const img=new Image();img.src=src;await img.decode();if(this.locked||!this.isConnected||token!==this.generation)return;const p=point||this.center(),o=B.createObject('image',p.x-160,p.y-100,file.name);o.src=src;o.width=320;o.height=Math.max(80,Math.min(480,320*img.naturalHeight/img.naturalWidth))+28;const next=this.data;next.objects.push(o);this.commit(next,'image');this.select([o.id]);}catch(ex){this.error='Не удалось открыть изображение.';this.render()}}
 async importFile(file){const generation=this.generation;if(file.size>15*1024*1024){this.error='JSON больше 15 МБ не поддерживается';this.render();return}try{const v=B.validateBoard(JSON.parse(await file.text()));if(this.locked||!this.isConnected||generation!==this.generation)return;const b=B.bounds(this.data.objects),r=B.insertScene(this.data,v,this.data.objects.length?b.x+b.width+100:40,40);this.commit(r.value,'import');this.select(r.ids);this.fit(r.ids)}catch(ex){this.error=ex.message;this.render()}}
 download(data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='iquipage-board.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.announce('Файл доски подготовлен');}
}
Object.assign(IqWhiteboard.prototype,require('./whiteboard-experience.js').experience);
require('./whiteboard-studio.js').installStudio(IqWhiteboard);
require('./whiteboard-workshop.js').installWorkshop(IqWhiteboard);
function textEditableOff(t){t.contentEditable='false';t.removeAttribute('role');t.removeAttribute('aria-multiline');t.oninput=null;t.onblur=null;}
function registerWhiteboard(){if(!customElements.get('iq-whiteboard'))customElements.define('iq-whiteboard',IqWhiteboard)}
Object.assign(exports,{IqWhiteboard,registerWhiteboard});

