'use strict';
/** Spatial editor composition. Extends stable history/controlled-state mechanisms. */
const B=require('./whiteboard-core.js'),U=require('./whiteboard-experience-core.js'),R=require('./whiteboard-routing.js');
const {icon,escapeHTML:esc}=require('./components.js');
const {safeMarkdown,markdownTools}=require('./editor.js');
const TITLES={sticky:'Заметка',text:'Текст',shape:'Фигура',frame:'Область',task:'Действие',image:'Подпись изображения'};
const Shapes=require('./whiteboard-shapes.js');
const SIDE_LABELS={auto:'Автоматически',top:'Сверху',right:'Справа',bottom:'Снизу',left:'Слева'};
const tools=[['select','Выбрать','cursor','V'],['hand','Двигать','hand','H'],['connect','Связи','link','C']];
const FILL={neutral:'var(--iq-muted)',accent:'var(--iq-focus)',success:'var(--iq-success)',warning:'var(--iq-warning)',error:'var(--iq-danger)'};
const action=(id,label,glyph,extra='')=>`<button type="button" class="wb-button" data-wb-action="${id}" aria-label="${esc(label)}" ${extra}>${glyph?icon(glyph,18):''}<span>${esc(label)}</span></button>`;
const shapeArt=kind=>`<i class="wb-shape-art" data-shape="${kind}" aria-hidden="true"></i>`;
function toolbarKey(e,group){if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...group.querySelectorAll('button:not(:disabled)')];let i=buttons.indexOf(e.target);if(i<0)return;e.preventDefault();e.stopPropagation();i=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons.forEach((b,n)=>b.tabIndex=n===i?0:-1);buttons[i]?.focus();}
function syncToolbar(group){if(!group)return;const buttons=[...group.querySelectorAll('button:not(:disabled)')];const active=buttons.find(b=>b===document.activeElement)||buttons.find(b=>b.tabIndex===0)||buttons[0];for(const b of group.querySelectorAll('button'))b.tabIndex=b===active&&!b.disabled?0:-1;}
function safeLabel(text){return String(text||'').replace(/[#*`~]/g,'').replace(/\s+/g,' ').slice(0,70)||'Без названия'}
function plainValue(ed){return ed?.input?.value??ed?.textEl?.innerText??''}
function installStudio(Klass){
 const base={};for(const name of ['initDOM','listen','render','updateScene','renderSelection','begin','move','end','cancelGesture','key','click','action','setTool','renderMode','disconnectedCallback'])base[name]=Klass.prototype[name];
 Object.assign(Klass.prototype,{
 initDOM(){
  base.initDOM.call(this);if(this.shell.dataset.studio==='055')return;this.shell.dataset.studio='055';this.libraryCategory='notes';this.libraryOpen=innerWidth>760;
  const rail=this.shell.querySelector('.wb-rail');rail.outerHTML=`<aside class="wb-library" aria-label="Библиотека объектов"><header><div><span class="wb-library-eyebrow">ДОБАВИТЬ НА ДОСКУ</span><h3>Объекты</h3></div>${action('library-toggle','Скрыть объекты','x')}</header><div class="wb-library-categories" role="group" aria-label="Категории объектов">${[['notes','Записи'],['shapes','Фигуры'],['media','Материалы']].map(([id,label])=>`<button type="button" data-library-category="${id}" aria-pressed="${id==='notes'}">${label}</button>`).join('')}</div><div class="wb-library-items"></div><p class="wb-library-tip">Выберите объект, затем нажмите на доску. Escape — отмена.</p></aside>`;
  this.libraryEl=this.shell.querySelector('.wb-library');this.renderLibrary();
  const footer=this.shell.querySelector('.wb-footer');footer.innerHTML=`<div class="wb-dock" role="toolbar" aria-label="Работа с доской">${action('library-toggle','Объекты','plus','aria-expanded="true"')}<span class="wb-dock-divider"></span>${tools.map(([id,label,glyph,k],i)=>`<button type="button" class="wb-tool" data-tool="${id}" aria-label="${label} (${k})" aria-pressed="${id==='select'}" tabindex="${i===0?0:-1}">${icon(glyph,20)}<span>${label}</span></button>`).join('')}<span class="wb-dock-divider"></span>${action('undo','Отменить','undo')}${action('redo','Повторить','redo')}</div><div class="wb-zoom">${action('zoom-out','Уменьшить','minus')}<button class="wb-button wb-zoom-label" data-wb-action="reset-zoom" aria-label="Вернуть масштаб 100%">100%</button>${action('zoom-in','Увеличить','plus')}${action('fit','Всё','expand')}</div>`;
  this.shell.querySelector('.wb-history')?.remove();
  this.shell.querySelector('.wb-header-actions').insertAdjacentHTML('afterbegin',action('search','Поиск','search'));
  this.shell.querySelector('.wb-idle-context').insertAdjacentHTML('beforeend','<span class="wb-hint sr-only"></span>');
  const editor=document.createElement('section');editor.className='wb-formatting';editor.setAttribute('aria-label','Редактор выбранного объекта');editor.hidden=true;this.shell.querySelector('.wb-workspace').before(editor);this.formatEl=editor;
  this.mode='canvas';
  this.stage.setAttribute('aria-label','Доска. Выбор, перемещение и связи находятся в нижней панели. Объекты добавляются из библиотеки слева.');
  this.shell.querySelectorAll('[title]').forEach(e=>e.removeAttribute('title'));
 },
 listen(){
  base.listen.call(this);const signal=this.events.signal;
  this.addEventListener('pointerdown',e=>{if(e.target.closest('[data-wb-md],[data-wb-align],[data-wb-valign]')){if(e.pointerType==='mouse')e.preventDefault();}},{signal,capture:true});
  this.addEventListener('keydown',e=>{const group=e.target.closest('.wb-dock,.wb-md-tools');if(group)toolbarKey(e,group);},{signal,capture:true});
  this.stage.addEventListener('pointermove',e=>{if(this.tool==='connect'&&this.linkFrom&&!this.gesture){this.linkPoint=this.point(e);if(!this.linkFrame)this.linkFrame=requestAnimationFrame(()=>{this.linkFrame=0;this.drawLinkPreview();});}},{signal});
 },
 disconnectedCallback(){this.cancelConnector();this.formatMeasure?.remove();cancelAnimationFrame(this.measureFrame);base.disconnectedCallback.call(this)},
 render(){
  base.render.call(this);if(!this.libraryEl)return;
  this.shell.classList.toggle('library-closed',!this.libraryOpen);this.libraryEl.hidden=!this.libraryOpen;
  this.shell.querySelector('[data-wb-action=library-toggle][aria-expanded]')?.setAttribute('aria-expanded',String(this.libraryOpen));
  this.libraryEl.querySelectorAll('[data-library-item]').forEach(b=>{b.disabled=this.locked;b.setAttribute('aria-pressed',String(b.dataset.libraryItem===this.tool&&(this.tool!=='shape'||b.dataset.shape===this.shape)));});
  this.shell.querySelectorAll('[title]').forEach(e=>e.removeAttribute('title'));
  if(this._edgeDrag)this.drawLinkPreview();syncToolbar(this.shell.querySelector('.wb-dock'));syncToolbar(this.formatEl?.querySelector('.wb-md-tools'));
 },
 renderLibrary(){
  if(!this.libraryEl)return;this.libraryEl.querySelectorAll('[data-library-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.libraryCategory===this.libraryCategory)));
  const item=(type,label,desc,glyph,shape)=>`<button type="button" class="wb-library-item" data-library-item="${type}" ${shape?`data-shape="${shape}"`:''} aria-pressed="false"><span class="wb-library-preview ${type==='sticky'?'is-note':''}">${shape?shapeArt(shape):icon(glyph,22)}</span><span><b>${label}</b><small>${desc}</small></span></button>`;
  this.libraryEl.querySelector('.wb-library-items').innerHTML=this.libraryCategory==='shapes'?`<p class="wb-library-group">Блоки для схем</p><div class="wb-shape-grid">${[['rectangle','Процесс'],['diamond','Решение'],['ellipse','Событие'],['pill','Начало / конец']].map(([shape,label])=>item('shape',label,'','',shape)).join('')}</div>`:this.libraryCategory==='media'?`<p class="wb-library-group">Материалы</p>${item('image','Изображение','PNG, JPEG или WebP','image')}${action('bulk','Несколько мыслей','list')}`:`<p class="wb-library-group">Мысли и договорённости</p>${item('sticky','Заметка','Одна мысль — одна карточка','sticky')}${item('text','Текст','Заголовок или пояснение','text')}${item('task','Действие','Результат и ответственный','checklist')}<p class="wb-library-group">Организация</p>${item('frame','Область','Собрать объекты в одну тему','board')}`;
 },
 updateScene(scene){
  base.updateScene.call(this,scene);if(!this.objectsEl)return;const d=scene||this.data;
  for(const o of d.objects){const el=this.objectsEl.querySelector(`[data-object="${o.id}"]`);if(!el)continue;el.dataset.align=o.align|| (o.type==='shape'?'center':'left');el.dataset.valign=o.valign||(o.type==='shape'?'middle':'top');el.dataset.autoheight=String(o.autoHeight!==false);if(o.type==='frame')el.style.setProperty('--wb-header-height',(o.headerHeight||56)+'px');if(o.type==='image')el.style.setProperty('--wb-caption-height',(o.captionHeight||32)+'px');
   if(o.type==='shape'&&!el.querySelector('.wb-shape-face')){const face=document.createElementNS('http://www.w3.org/2000/svg','svg');face.setAttribute('class','wb-shape-face');face.setAttribute('viewBox','0 0 100 100');face.setAttribute('preserveAspectRatio','none');face.setAttribute('aria-hidden','true');el.prepend(face);}
   if(o.type==='shape'){const inset=Shapes.shapeDefinition(o.shape).inset;el.style.setProperty('--shape-inset',inset.map(x=>x+'%').join(' '));el.style.setProperty('--shape-top',inset[0]+'%');el.style.setProperty('--shape-right',inset[1]+'%');el.style.setProperty('--shape-bottom',inset[2]+'%');el.style.setProperty('--shape-left',inset[3]+'%');const face=el.querySelector('.wb-shape-face');const kind=o.shape||'rectangle';if(face.dataset.kind!==kind+o.width+'x'+o.height){face.dataset.kind=kind+o.width+'x'+o.height;face.innerHTML=Shapes.face(kind,o.width,o.height);}}
   const text=el.querySelector('.wb-object-text');if(text&&this.editing?.id!==o.id&&text.dataset.markdown!==o.text){text.innerHTML=safeMarkdown(o.text||'');text.dataset.markdown=o.text||'';}
  }
 },
 renderSelection(){
  base.renderSelection.call(this);if(!this.objectsEl)return;this.objectsEl.querySelectorAll('.wb-port').forEach(n=>n.remove());
  for(const o of this.data.objects){if(o.type==='frame'||o.type==='drawing'||this.locked||B.isLocked(this.data,o))continue;const el=this.objectsEl.querySelector(`[data-object="${o.id}"]`);if(!el||this.editing?.id===o.id)continue;
   for(const side of ['top','right','bottom','left'])el.insertAdjacentHTML('beforeend',`<button type="button" class="wb-port" data-port="${side}" data-port-object="${o.id}" aria-label="Соединить: ${esc(safeLabel(o.text))}, ${SIDE_LABELS[side].toLowerCase()}" tabindex="${this.selection.includes(o.id)?'0':'-1'}"></button>`);
  }
  if(this.editing){this.context.innerHTML='<span class="wb-selection-count">Текст объекта</span><span class="wb-edit-hint">Ctrl / ⌘ + Enter — готово</span>';this.buildFormatting();}
  else if(this.formatEl)this.formatEl.hidden=true;
  const edge=this.data.connections.find(e=>this.selection.includes(e.id));if(edge&&!this.editing)this.context.innerHTML=`<span class="wb-selection-count">Связь</span>${action('edge-edit','Настроить связь','sliders')}${action('edge-reverse','Развернуть','sort')}${action('delete','Удалить','trash')}`;
  this.updateEdges();
 },
 renderMode(){base.renderMode.call(this);if(this.tool==='connect'){const el=this.shell?.querySelector('.wb-mode-description');if(el)el.textContent=this.linkFrom?'Выберите второй объект или перетащите к нужной стороне. Escape — отменить.':'Потяните от точки объекта к другому. Или нажмите на два объекта по очереди.';}},
 setTool(t){if(t==='pen')return;this.linkPort=null;this.linkPoint=null;base.setTool.call(this,t);this.renderLibrary();if(innerWidth<760&&['sticky','shape','text','frame','task'].includes(t)){this.libraryOpen=false;this.render();}},
 click(e){
  const category=e.target.closest('[data-library-category]');if(category){this.finishEdit(true);this.libraryCategory=category.dataset.libraryCategory;this.renderLibrary();return;}
  const item=e.target.closest('[data-library-item]');if(item){if(this.locked)return;const t=item.dataset.libraryItem;if(t==='image'){this.action('image');return;}if(t==='shape')this.shape=item.dataset.shape;this.setTool(t);return;}
  const format=e.target.closest('[data-wb-md]');if(format){e.preventDefault();e.stopPropagation();this.markdownCommand(format.dataset.wbMd);return;}
  const align=e.target.closest('[data-wb-align],[data-wb-valign]');if(align){e.preventDefault();e.stopPropagation();this.setTextAlignment(align.dataset.wbAlign,align.dataset.wbValign);return;}
  if(e.target.closest('[data-port],[data-edge-end]'))return;
  base.click.call(this,e);
 },
 action(id,el){
  if(id==='list'){this.mode='canvas';this.panel='search';this.render();return;}
  if(id==='library-toggle'){this.libraryOpen=!this.libraryOpen;this.render();return;}
  if(id==='edge-edit'){this.editConnection(this.selection[0]);return;}
  if(id==='edge-reverse'){if(this.locked)return;const next=this.data,e=next.connections.find(e=>this.selection.includes(e.id));if(e){[e.from,e.to]=[e.to,e.from];[e.fromPort,e.toPort]=[e.toPort,e.fromPort];this.commit(next,'reverse-connection');}return;}
  if(id==='edit'){this.edit(this.selection[0]);return;}
  if(id==='finish-edit'){this.finishEdit(true);this.stage.focus({preventScroll:true});return;}
  if(id==='cancel-edit'){this.finishEdit(false);return;}
  if(id==='connect-selected'){this.finishEdit(true);this.linkFrom=this.selection[0];this.linkPort='auto';this.tool='connect';this.render();return;}
  base.action.call(this,id,el);
 },
 add(type,x,y,text){
  if(this.locked)return;this.finishEdit(true);const p=this.center(),o=B.createObject(type,x??p.x-120,y??p.y-80,text||'',this.color);if(type==='shape'){o.shape=this.shape;[o.width,o.height]=Shapes.shapeDefinition(o.shape).size;o.minHeight=o.height;o.align='center';o.valign='middle';}
  let next=this.data;next.objects.push(o);next=B.assignFrames(next,[o.id]);if(this.commit(next,'add')){this.tool='select';this.select([o.id],false);this.render();if(!['image','drawing'].includes(type))this.edit(o.id);}return o.id;
 },
 edit(id){
  if(this.locked)return;const o=this.data.objects.find(o=>o.id===id);if(!o||B.isLocked(this.data,o)||o.type==='drawing')return;if(this.editing?.id===id)return;this.finishEdit(true);if(this.locked)return;
  if(innerWidth<680){this.openRichSheet(o);return;}
  const el=this.objectsEl.querySelector(`[data-object="${id}"]`),text=el?.querySelector('.wb-object-text');if(!text)return;
  const input=document.createElement('textarea');input.className='wb-inline-input';input.value=o.text;input.maxLength=10000;input.setAttribute('aria-label',`Текст: ${TITLES[o.type]}`);input.setAttribute('spellcheck','true');input.rows=1;
  Object.defineProperty(input,'innerText',{get(){return this.value},set(v){this.value=v},configurable:true});
  text.replaceChildren(input);text.classList.add('has-editor');el.classList.add('is-editing');this._selection=[id];this.editing={id,original:o.text,height:o.height,textEl:input,input,align:o.align,valign:o.valign,history:[o.text],cursor:0};
  input.oninput=()=>{const ed=this.editing;if(!ed)return;if(ed.history[ed.cursor]!==input.value){ed.history=ed.history.slice(0,ed.cursor+1);ed.history.push(input.value);ed.cursor=ed.history.length-1;}cancelAnimationFrame(this.measureFrame);this.measureFrame=requestAnimationFrame(()=>this.sizeWhileEditing());};
  this.renderSelection();this.focusObjects([id]);input.focus({preventScroll:true});input.setSelectionRange(input.value.length,input.value.length);this.sizeWhileEditing();
 },
 measureText(o,text){
  if(!['sticky','task','text','shape','frame','image'].includes(o.type)||o.autoHeight===false)return o.height;
  const diamond=o.type==='shape'&&o.shape==='diamond',ellipse=o.type==='shape'&&o.shape==='ellipse';
  const inset=o.type==='shape'?Shapes.shapeDefinition(o.shape).inset:null;const width=inset?o.width*(100-inset[1]-inset[3])/100:o.width-(o.type==='text'?12:o.type==='frame'?124:o.type==='image'?24:40);
  const box=document.createElement('div');box.className='wb-object-text wb-measure';
  Object.assign(box.style,{position:'fixed',left:'-20000px',top:'0',width:Math.max(24,width)+'px',height:'auto',maxHeight:'none',display:'block',visibility:'hidden',pointerEvents:'none',fontSize:(o.type==='text'?24:o.type==='image'?13:16)+'px',lineHeight:'1.5'});
  box.setAttribute('aria-hidden','true');box.innerHTML=safeMarkdown(text||' ');this.shell.append(box);
  const body=box.getBoundingClientRect().height;box.remove();
  if(o.type==='frame')return Math.max(56,Math.min(4000,Math.ceil((body+28)/4)*4));if(o.type==='image')return Math.max(32,Math.min(4000,Math.ceil((body+24)/4)*4));
  const needed=inset?(body+12)*100/(100-inset[0]-inset[2]):body+(o.type==='task'?92:o.type==='text'?12:48);
  return Math.min(4000,Math.max(o.minHeight||o.height,Math.ceil(needed/4)*4));
 },
 textScene(id,text){const raw=this.data,o=raw.objects.find(o=>o.id===id);if(!o)return raw;if(o.type==='frame'){const next=B.clone(raw),n=next.objects.find(n=>n.id===id),header=this.measureText(o,text),delta=header-(o.headerHeight||56);n.text=text;n.headerHeight=header;n.height=Math.min(10000,Math.max(header+48,n.height+delta));const ids=B.family(next,[id]);for(const child of next.objects)if(child.id!==id&&ids.has(child.id))child.y+=delta;return B.validateBoard(U.growParents(next,id));}const measured=this.measureText(o,text);if(o.type==='image'){const next=U.resizeText(raw,id,text,o.height-(o.captionHeight||32)+measured);next.objects.find(n=>n.id===id).captionHeight=measured;return B.validateBoard(next);}const next=U.resizeText(raw,id,text,measured);return next;},
 sizeWhileEditing(){const ed=this.editing;if(!ed)return;const o=this.data.objects.find(o=>o.id===ed.id),el=this.objectsEl.querySelector(`[data-object="${ed.id}"]`);if(!o||!el)return;
  const next=this.textScene(o.id,ed.input.value);ed.preview=next;
  for(const n of next.objects){const node=this.objectsEl.querySelector(`[data-object="${n.id}"]`);if(node){node.style.top=n.y+'px';node.style.height=n.height+'px';if(n.type==='frame')node.style.setProperty('--wb-header-height',(n.headerHeight||56)+'px');if(n.type==='image')node.style.setProperty('--wb-caption-height',(n.captionHeight||32)+'px');}}
  this.updateEdges(next);ed.input.style.height='auto';const available=el.querySelector('.wb-object-text').clientHeight;ed.input.style.height=Math.min(available,Math.max(24,ed.input.scrollHeight))+'px';
  this.formatEl.querySelector('[data-wb-count]')?.replaceChildren(document.createTextNode(ed.input.value.length+' / 10 000'));
 },
 editDraft(){if(!this.editing)return this.data;const ed=this.editing,next=this.textScene(ed.id,plainValue(ed)),o=next.objects.find(n=>n.id===ed.id);if(o){o.align=ed.align;o.valign=ed.valign;}return next;},
 finishEdit(save){cancelAnimationFrame(this.measureFrame);const ed=this.editing;if(!ed)return;const next=this.editDraft();this.editing=null;ed.input.oninput=null;const obj=this.objectsEl?.querySelector(`[data-object="${ed.id}"]`);if(obj){obj._signature=null;obj.classList.remove('is-editing');}if(this.formatEl)this.formatEl.hidden=true;this.formatEl.dataset.object='';if(save&&!this.locked)this.commit(next,'edit-text');this.updateScene();this.renderSelection();},
 buildFormatting(){const ed=this.editing;if(!ed||!this.formatEl)return;this.formatEl.hidden=false;
  if(this.formatEl.dataset.object!==ed.id){this.formatEl.dataset.object=ed.id;this.formatEl.innerHTML=`<div class="wb-format-head"><b>Текст и выравнивание</b><span data-wb-count></span>${action('cancel-edit','Отменить','x')}${action('finish-edit','Готово','check')}</div><div class="wb-format-body"><div class="wb-md-tools" role="toolbar" aria-label="Markdown">${markdownTools.map((t,i)=>`<button type="button" data-wb-md="${t.id}" aria-label="${t.label}" tabindex="${i?' -1':'0'}">${icon(t.glyph,17)}</button>`).join('')}</div><div class="wb-alignment" role="group" aria-label="Выравнивание текста">${[['left','По левому краю','alignLeft'],['center','По центру','alignCenter'],['right','По правому краю','alignRight']].map(([id,label,symbol])=>`<button type="button" data-wb-align="${id}" aria-label="${label}">${icon(symbol,17)}</button>`).join('')}<span class="wb-dock-divider"></span>${[['top','По верхнему краю','alignLeft'],['middle','По центру по вертикали','alignCenter'],['bottom','По нижнему краю','alignRight']].map(([id,label,symbol])=>`<button type="button" data-wb-valign="${id}" aria-label="${label}"><span class="wb-vertical-align" aria-hidden="true">${icon(symbol,17)}</span></button>`).join('')}</div></div>`;}
  this.formatEl.querySelectorAll('[data-wb-align]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.wbAlign===(ed.align||'left'))));this.formatEl.querySelectorAll('[data-wb-valign]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.wbValign===(ed.valign||'top'))));
 },
 setTextAlignment(align,valign){const ed=this.editing;if(!ed)return;if(align)ed.align=align;if(valign)ed.valign=valign;const el=this.objectsEl.querySelector(`[data-object="${ed.id}"]`);el.dataset.align=ed.align;el.dataset.valign=ed.valign;this.buildFormatting();ed.input.focus({preventScroll:true});},
 markdownCommand(id){const ed=this.editing;if(!ed)return;const input=ed.input;if(id==='undo'||id==='redo'){const index=ed.cursor+(id==='undo'?-1:1);if(index<0||index>=ed.history.length)return;ed.cursor=index;input.value=ed.history[index];}
  else{const v=input.value,start=input.selectionStart,end=input.selectionEnd,selected=v.slice(start,end)||'текст';let a=start,b=end,insert='';const pairs={bold:'**',italic:'*',strike:'~~',code:'`'};
   if(pairs[id])insert=pairs[id]+selected+pairs[id];else if(id==='link')insert=`[${selected}](https://example.com)`;else if(id==='image')insert='![Описание](https://example.com/image.png)';else if(id==='block')insert='\n```\n'+selected+'\n```\n';else if(id==='rule')insert='\n\n---\n\n';else{const prefixes={h1:'# ',h2:'## ',h3:'### ',ul:'- ',ol:'1. ',task:'- [ ] ',quote:'> '};a=v.lastIndexOf('\n',start-1)+1;b=v.indexOf('\n',end);if(b<0)b=v.length;insert=(v.slice(a,b)||'текст').split('\n').map((line,i)=>(id==='ol'?(i+1)+'. ':prefixes[id]||'')+line.replace(/^(#{1,3} |> |- \[[ x]\] |[-*] |\d+\. )/,'')).join('\n');}
   if(v.length-(b-a)+insert.length>10000){this.announce('Максимум 10 000 знаков.');return;}input.setRangeText(insert,a,b,'select');ed.history=ed.history.slice(0,ed.cursor+1);ed.history.push(input.value);ed.cursor=ed.history.length-1;
  }input.focus({preventScroll:true});this.sizeWhileEditing();},
 openRichSheet(o){
  require('./editor.js').registerEditors();const dialog=this.openSheet('Текст объекта',`<iq-markdown-editor label="${esc(TITLES[o.type])}" maxlength="10000"></iq-markdown-editor><div class="wb-field-pair"><label>По горизонтали<select name="align">${[['left','Слева'],['center','По центру'],['right','Справа']].map(([id,t])=>`<option value="${id}">${t}</option>`).join('')}</select></label><label>По вертикали<select name="valign">${[['top','Сверху'],['middle','По середине'],['bottom','Снизу']].map(([id,t])=>`<option value="${id}">${t}</option>`).join('')}</select></label></div>${o.type==='task'?`<label>Ответственный<input name="owner" value="${esc(o.owner||'')}" maxlength="100"></label>`:''}`,form=>{const next=this.textScene(o.id,form.querySelector('iq-markdown-editor').value),n=next.objects.find(n=>n.id===o.id);if(!n||B.isLocked(next,n))throw new Error('Объект недоступен для изменения');n.align=form.elements.align.value;n.valign=form.elements.valign.value;if(o.type==='task')n.owner=form.elements.owner.value;return this.commit(next,'edit-content');},'Сохранить');dialog.classList.add('wb-rich-sheet');dialog.querySelector('iq-markdown-editor').value=o.text;dialog.querySelector('[name=align]').value=o.align||'left';dialog.querySelector('[name=valign]').value=o.valign||'top';
 },
 openEditSheet(o){this.openRichSheet(o);},
 key(e){const ed=this.editing;if(ed){if(e.isComposing)return;if((e.ctrlKey||e.metaKey)&&['b','i','k'].includes(e.key.toLowerCase())){e.preventDefault();this.markdownCommand({b:'bold',i:'italic',k:'link'}[e.key.toLowerCase()]);return;}if(e.key==='Escape'){e.preventDefault();this.finishEdit(false);return;}if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();this.finishEdit(true);return;}}
  const edgeEnd=e.target.closest('[data-edge-end]');if(edgeEnd&&['Enter',' '].includes(e.key)){e.preventDefault();this.editConnection(edgeEnd.dataset.edge);return;}const port=e.target.closest('[data-port]');if(port&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(this.linkFrom&&this.linkFrom!==port.dataset.portObject){this.connect(this.linkFrom,port.dataset.portObject,'',{fromPort:this.linkPort,toPort:port.dataset.port});this.linkFrom=null;this.tool='select';this.render();}else{this.linkFrom=port.dataset.portObject;this.linkPort=port.dataset.port;this.tool='connect';this.renderMode();}return;}
  if(e.key==='Escape'&&(this._edgeDrag||this.linkFrom)){e.preventDefault();e.stopPropagation();this.cancelConnector();this.linkFrom=null;this.linkPort=null;this.tool='select';this.render();this.stage.focus({preventScroll:true});return;}
  base.key.call(this,e);
 },
 updateEdges(scene=this.data){
  if(!this.svg)return;if(!this.edgeHandleLayer?.isConnected){this.edgeHandleLayer=document.createElementNS('http://www.w3.org/2000/svg','svg');this.edgeHandleLayer.setAttribute('class','wb-link-handles');this.svg.parentElement.append(this.edgeHandleLayer);}const handleKeep=new Set();const by=new Map(scene.objects.map(o=>[o.id,o]));
  if(!this.svg.querySelector('defs'))this.svg.innerHTML=`<defs><marker id="${this.uid}-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M2 1 8 5 2 9" fill="none" stroke="context-stroke" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></marker></defs>`;
  const keep=new Set(scene.connections.map(e=>e.id));for(const e of this.svg.querySelectorAll('[data-connection]'))if(!keep.has(e.dataset.connection))e.remove();
  if(!this.edgeEls)this.edgeEls=new Map();
  const obstacleSignature=JSON.stringify(scene.objects.map(n=>[n.id,n.type,n.x,n.y,n.width,n.height]));
  for(const edge of scene.connections){const a=by.get(edge.from),b=by.get(edge.to);if(!a||!b)continue;const sig=JSON.stringify([a.x,a.y,a.width,a.height,a.shape,b.x,b.y,b.width,b.height,b.shape,edge,obstacleSignature]);this.routeCache ||= new Map();let cached=this.routeCache.get(edge.id);if(cached?.sig!==sig){cached={sig,g:R.route(a,b,edge,scene.objects)};this.routeCache.set(edge.id,cached);}const g=cached.g,selected=this.selection.includes(edge.id);let el=this.edgeEls.get(edge.id);
   if(!el?.isConnected){el=document.createElementNS('http://www.w3.org/2000/svg','g');el.dataset.connection=edge.id;el.tabIndex=0;el.setAttribute('role','button');el.innerHTML='<path class="wb-edge-hit"/><path class="wb-edge-line"/><g class="wb-connection-label"><rect height="26" rx="6"/><text dominant-baseline="central" text-anchor="middle"/></g>';this.svg.append(el);this.edgeEls.set(edge.id,el);}
   el.setAttribute('class','wb-connection'+(selected?' is-selected':''));el.style.setProperty('--edge-color',FILL[edge.color]||FILL.neutral);el.setAttribute('aria-label',safeLabel(a.text)+' → '+safeLabel(b.text)+(edge.label?': '+edge.label:''));
   el.querySelector('.wb-edge-hit').setAttribute('d',g.path);const line=el.querySelector('.wb-edge-line');line.setAttribute('d',g.path);line.setAttribute('stroke-dasharray',edge.dashed?'6 5':'none');
   for(const[end,yes]of [['end',edge.arrow],['start',edge.arrowStart]]){if(yes)line.setAttribute('marker-'+end,`url(#${this.uid}-arrow)`);else line.removeAttribute('marker-'+end);}
   const label=el.querySelector('.wb-connection-label'),text=label.querySelector('text'),rect=label.querySelector('rect');label.style.display=edge.label?'':'none';
   if(text.textContent!==edge.label){text.textContent=edge.label||'';el._labelWidth=edge.label?Math.max(36,text.getComputedTextLength()+20):36;}
   const width=el._labelWidth||36;text.setAttribute('x',g.x);text.setAttribute('y',g.y);rect.setAttribute('x',g.x-width/2);rect.setAttribute('y',g.y-13);rect.setAttribute('width',width);
   for(const[end,p]of [['from',g.source],['to',g.target]]){const key=edge.id+':'+end;if(!selected||this.locked)continue;handleKeep.add(key);let c=this.edgeHandleLayer.querySelector(`[data-handle-key="${key}"]`);if(!c){c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','wb-edge-end');c.setAttribute('vector-effect','non-scaling-stroke');c.dataset.handleKey=key;c.dataset.edgeEnd=end;c.dataset.edge=edge.id;c.setAttribute('r','8');c.setAttribute('tabindex','0');c.setAttribute('role','button');c.setAttribute('aria-label',end==='from'?'Переподключить начало связи':'Переподключить конец связи');this.edgeHandleLayer.append(c);}c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);}
  }for(const id of this.edgeEls.keys())if(!keep.has(id)){this.edgeEls.delete(id);this.routeCache?.delete(id);}for(const c of this.edgeHandleLayer.children)if(!handleKeep.has(c.dataset.handleKey))c.remove();
 },
 begin(e){
  const port=e.target.closest('[data-port]'),end=e.target.closest('[data-edge-end]');if((port||end)&&!this.locked){if(e.button!==0||e.isPrimary===false)return;const n=port&&this.data.objects.find(n=>n.id===port.dataset.portObject);if(n&&B.isLocked(this.data,n))return;e.preventDefault();e.stopPropagation();this.finishEdit(true);const from=port?.dataset.portObject;this._edgeDrag={pointerId:e.pointerId,start:{x:e.clientX,y:e.clientY},source:from||null,port:port?.dataset.port,edgeId:end?.dataset.edge,end:end?.dataset.edgeEnd,moved:false};this.linkPoint=this.point(e);this.edgeGestures?.abort();this.edgeGestures=new AbortController();const signal=this.edgeGestures.signal;window.addEventListener('pointermove',ev=>this.moveConnector(ev),{signal});window.addEventListener('pointerup',ev=>this.endConnector(ev),{signal});window.addEventListener('pointercancel',()=>this.cancelConnector(),{signal});return;}
  if(this.tool==='connect'&&this.linkFrom&&e.target.closest('[data-object]')&&!port){const to=e.target.closest('[data-object]').dataset.object;if(to!==this.linkFrom){e.preventDefault();this.connect(this.linkFrom,to,'',{fromPort:this.linkPort||'auto'});this.linkFrom=null;this.linkPort=null;this.tool='select';this.render();return;}}
  if(this.tool==='task'&&!e.target.closest('[data-object]')&&e.target.closest('.wb-stage')&&!e.target.closest('button')){e.preventDefault();const p=this.point(e);this.add('task',p.x,p.y);return;}
  base.begin.call(this,e);
 },
 moveConnector(e){const g=this._edgeDrag;if(!g||g.pointerId!==e.pointerId)return;if(Math.hypot(e.clientX-g.start.x,e.clientY-g.start.y)>4)g.moved=true;this.linkPoint=this.point(e);const target=document.elementFromPoint(e.clientX,e.clientY),port=target?.closest('[data-port]'),node=target?.closest('[data-object]');g.target=node?.dataset.object||port?.dataset.portObject;g.targetPort=port?.dataset.port||'auto';this.objectsEl.querySelectorAll('.is-link-target').forEach(e=>e.classList.remove('is-link-target'));if(g.target&&g.target!==g.source)this.objectsEl.querySelector(`[data-object="${g.target}"]`)?.classList.add('is-link-target');if(!this.linkFrame)this.linkFrame=requestAnimationFrame(()=>{this.linkFrame=0;this.drawLinkPreview();});},
 drawLinkPreview(){const drag=this._edgeDrag,edge=drag?.edgeId?this.data.connections.find(e=>e.id===drag.edgeId):null;let from=drag?.source||this.linkFrom,port=drag?.port||this.linkPort||'auto';if(edge){from=drag.end==='from'?edge.to:edge.from;port=drag.end==='from'?edge.toPort:edge.fromPort;}const a=this.data.objects.find(o=>o.id===from),b=this.data.objects.find(o=>o.id===drag?.target);if(!a||!this.linkPoint)return;const p=this.linkPoint,target=b||{x:p.x,y:p.y,width:1,height:1};const g=R.route(a,target,{style:edge?.style||'elbow',fromPort:port,toPort:drag?.targetPort||'auto'},this.data.objects);let line=this.svg.querySelector('[data-link-preview]');if(!line){line=document.createElementNS('http://www.w3.org/2000/svg','path');line.setAttribute('data-link-preview','');line.setAttribute('class','wb-link-preview');this.svg.append(line);}line.setAttribute('d',g.path);},
 endConnector(e){const g=this._edgeDrag;if(!g||g.pointerId!==e.pointerId)return;this.moveConnector(e);cancelAnimationFrame(this.linkFrame);this.linkFrame=0;this.edgeGestures?.abort();this._edgeDrag=null;this.svg.querySelector('[data-link-preview]')?.remove();this.objectsEl.querySelectorAll('.is-link-target').forEach(e=>e.classList.remove('is-link-target'));
  if(!g.moved&&!g.edgeId){if(this.linkFrom&&g.source!==this.linkFrom){this.connect(this.linkFrom,g.source,'',{fromPort:this.linkPort||'auto',toPort:g.port});this.linkFrom=null;this.tool='select';}else{this.linkFrom=g.source;this.linkPort=g.port;this.tool='connect';this.announce('Выберите второй объект.');}this.render();return;}
  if(g.target&&this.canLink(g.source||this.data.connections.find(e=>e.id===g.edgeId)?.[g.end==='from'?'to':'from'],g.target)){if(g.edgeId){const next=this.data,ed=next.connections.find(e=>e.id===g.edgeId);if(ed){const other=g.end==='from'?ed.to:ed.from;if(g.target!==other){if(next.connections.some(x=>x.id!==ed.id&&x.from===(g.end==='from'?g.target:ed.from)&&x.to===(g.end==='to'?g.target:ed.to))){this.announce('Такая связь уже существует.');this.render();return;}ed[g.end]=g.target;ed[g.end==='from'?'fromPort':'toPort']=g.targetPort;this.commit(next,'reconnect');}}}else this.connect(g.source,g.target,'',{fromPort:g.port,toPort:g.targetPort});}else this.announce('Связь не изменена: выберите объект на доске.');this.linkPoint=null;this.linkFrom=null;this.tool='select';this.render();
 },
 cancelConnector(){cancelAnimationFrame(this.linkFrame);this.linkFrame=0;this.edgeGestures?.abort();this._edgeDrag=null;this.linkPoint=null;this.svg?.querySelector('[data-link-preview]')?.remove();this.objectsEl?.querySelectorAll('.is-link-target').forEach(e=>e.classList.remove('is-link-target'));},
 cancelGesture(){this.cancelConnector();base.cancelGesture.call(this)},
 canLink(from,to){const scene=this.data,a=scene.objects.find(n=>n.id===from),b=scene.objects.find(n=>n.id===to);return !!(a&&b&&a.id!==b.id&&!this.locked&&!B.isLocked(scene,a)&&!B.isLocked(scene,b)&&!['drawing','frame'].includes(a.type)&&!['drawing','frame'].includes(b.type));},
 connect(from,to,label='',options={}){if(!this.canLink(from,to)){this.announce('Эти объекты нельзя соединить.');return false;}const next=this.data;if(!next.objects.some(o=>o.id===from)||!next.objects.some(o=>o.id===to)||next.connections.some(e=>e.from===from&&e.to===to)){this.announce('Такая связь уже существует.');return false;}const edge={id:B.newId('edge'),from,to,label,style:'elbow',arrow:true,...options};next.connections.push(edge);if(!this.commit(next,'connect'))return false;this._selection=[edge.id];this.render();this.emit('iq-selection',{ids:this.selection});return true;},
 editConnection(id){const edge=this.data.connections.find(e=>e.id===id);if(!edge||this.locked)return;const objects=this.data.objects.filter(o=>!['drawing','frame'].includes(o.type)&&!B.isLocked(this.data,o));const opts=objects.map(o=>`<option value="${o.id}">${esc(safeLabel(o.text))}</option>`).join('');const sides=Object.entries(SIDE_LABELS).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');
  const dialog=this.openSheet('Настроить связь',`<label>Подпись<input name="label" maxlength="240"></label><div class="wb-field-pair"><label>Начало<select name="from">${opts}</select></label><label>Сторона<select name="fromPort">${sides}</select></label><label>Конец<select name="to">${opts}</select></label><label>Сторона<select name="toPort">${sides}</select></label></div><div class="wb-field-pair"><label>Линия<select name="style"><option value="curve">Плавная</option><option value="elbow">Ортогональная</option><option value="straight">Прямая</option></select></label><label>Направление<select name="direction"><option value="end">Стрелка в конце</option><option value="start">Стрелка в начале</option><option value="both">В обе стороны</option><option value="none">Без стрелок</option></select></label><label>Положение подписи<input name="labelPosition" type="range" min="15" max="85"></label><label>Смещение изгиба<input name="bend" type="number" min="-500" max="500"></label></div><label class="wb-checkbox"><input name="dashed" type="checkbox">Пунктирная линия</label>`,form=>{const n=this.data,e=n.connections.find(e=>e.id===id);if(!e)throw new Error('Связь удалена');const f=form.elements;if(!this.canLink(f.from.value,f.to.value))throw new Error('Начало и конец недоступны или совпадают');if(n.connections.some(e=>e.id!==id&&e.from===f.from.value&&e.to===f.to.value))throw new Error('Такая связь уже существует');Object.assign(e,{label:f.label.value,from:f.from.value,to:f.to.value,fromPort:f.fromPort.value,toPort:f.toPort.value,style:f.style.value,arrow:['end','both'].includes(f.direction.value),arrowStart:['start','both'].includes(f.direction.value),dashed:f.dashed.checked,bend:Number(f.bend.value),labelPosition:Number(f.labelPosition.value)/100});this.commit(n,'edit-connection');},'Сохранить связь');
  const f=dialog.querySelector('form').elements;for(const k of ['label','from','to','fromPort','toPort','style','bend'])f[k].value=edge[k]??(k==='bend'?0:k.endsWith('Port')?'auto':'');f.dashed.checked=!!edge.dashed;f.labelPosition.value=(edge.labelPosition??.5)*100;f.direction.value=edge.arrowStart?edge.arrow?'both':'start':edge.arrow?'end':'none';
 }
 });
}
exports.installStudio=installStudio;
