
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/modules/advanced-core.js');
global.HTMLElement=class {};
const {chartScale}=require('../src/modules/data-chart.js');
const {edgeGeometry,descendants}=require('../src/modules/graph.js');
const {optionList}=require('../src/modules/remote-inputs.js');
const plan=()=>({revision:1,title:'План',rows:[{id:'a',title:'A',start:'2026-09-01',end:'2026-09-03'},{id:'b',title:'B',start:'2026-09-04',end:'2026-09-07'}],dependencies:[{id:'ab',from:'a',to:'b',type:'FS',lagDays:0}]});
const graph=()=>({revision:1,nodes:[{id:'a',title:'A',x:0,y:0,width:260,height:180},{id:'b',title:'B',x:400,y:0,width:260,height:180}],edges:[{id:'ab',source:'a',target:'b'}]});
test('valid calendar days, leap day and DST-independent arithmetic',()=>{assert.ok(Number.isFinite(C.day('2024-02-29')));assert.ok(Number.isNaN(C.day('2025-02-29')));assert.equal(C.addDays('2026-03-28',2),'2026-03-30');assert.equal(C.addDays('2026-12-31',1),'2027-01-01')});
test('invalid calendar dates and formats rejected',()=>{for(const x of ['2026-02-30','2026-13-01','2026-1-01','2026-09-01T00:00:00Z',null,NaN])assert.ok(Number.isNaN(C.day(x)))});
test('plan input immutable and defaults explicit',()=>{const p=plan(),before=C.clone(p),v=C.validateRoadmap(p);v.rows[0].title='x';assert.deepEqual(p,before);assert.equal(v.rows[0].kind,'task')});
test('end precedes start',()=>{const p=plan();p.rows[0].end='2026-08-30';assert.throws(()=>C.validateRoadmap(p))});
test('milestone has one inclusive date',()=>{const p=plan();p.rows[0].kind='milestone';assert.throws(()=>C.validateRoadmap(p));p.rows[0].end=p.rows[0].start;assert.equal(C.validateRoadmap(p).rows[0].kind,'milestone')});
test('duplicate row and dependency IDs',()=>{const p=plan();p.rows[1].id='a';assert.throws(()=>C.validateRoadmap(p));const q=plan();q.dependencies.push({...q.dependencies[0]});assert.throws(()=>C.validateRoadmap(q))});
test('duplicate same-type relationship refused',()=>{const p=plan();p.dependencies.push({...p.dependencies[0],id:'ab2'});assert.throws(()=>C.validateRoadmap(p))});
test('relationship cycle refused',()=>{const p=plan();p.dependencies.push({id:'ba',from:'b',to:'a',type:'FS'});assert.throws(()=>C.validateRoadmap(p))});
test('missing endpoint refused',()=>{const p=plan();p.dependencies[0].to='missing';assert.throws(()=>C.validateRoadmap(p))});
test('NaN lag is not silently normalized',()=>{const p=plan();p.dependencies[0].lagDays=NaN;assert.throws(()=>C.validateRoadmap(p))});
test('fractional lag refused; negative integer accepted',()=>{const p=plan();p.dependencies[0].lagDays=.5;assert.throws(()=>C.validateRoadmap(p));p.dependencies[0].lagDays=-1;assert.equal(C.validateRoadmap(p).dependencies[0].lagDays,-1)});
test('progress bound checks',()=>{for(const progress of [-1,101,Infinity,NaN]){const p=plan();p.rows[0].progress=progress;assert.throws(()=>C.validateRoadmap(p))}});
for(const type of ['FS','SS','FF','SF'])test('dependency contract '+type,()=>{const p=plan();p.dependencies[0].type=type;assert.equal(C.roadmapConflicts(C.validateRoadmap(p)).length,0)});
test('FS inclusive boundary starts on next calendar day',()=>{const p=plan();p.rows[1].start='2026-09-03';assert.equal(C.roadmapConflicts(p).length,1);assert.equal(p.rows[1].start,'2026-09-03')});
test('no automatic dependency rescheduling',()=>{const p=plan();p.rows[0].end='2026-09-06';const q=C.clone(p);C.roadmapConflicts(p);assert.deepEqual(p,q)});
test('draft cancel restores model',()=>{const s=new C.EditSession(plan()),p=C.clone(s.value);p.rows[0].title='local';s.preview(p,{kind:'edit'});assert.equal(s.base.rows[0].title,'A');s.cancel();assert.equal(s.value.rows[0].title,'A')});
test('no-op preview does not create dirty state',()=>{const s=new C.EditSession(plan());s.preview(plan(),{});assert.equal(s.dirty,false)});
test('commit increments revision and stages undo',()=>{const s=new C.EditSession(plan()),p=C.clone(s.value);p.title='change';s.preview(p,{});s.commit();assert.equal(s.base.revision,2);assert.equal(s.history.length,1);s.undo();assert.equal(s.base.title,'План')});
test('external update is not overwritten while dirty',()=>{const s=new C.EditSession(plan()),p=C.clone(s.value);p.rows[0].title='local';s.preview(p,{});const remote=plan();remote.revision=2;remote.rows[1].title='remote';assert.equal(s.load(remote),false);assert.equal(s.value.rows[0].title,'local');assert.throws(()=>s.commit())});
test('three-way rebase preserves unrelated remote field',()=>{const s=new C.EditSession(plan()),p=C.clone(s.value);p.rows[0].title='local';s.preview(p,{});const remote=plan();remote.revision=2;remote.rows[1].title='remote';s.load(remote);s.resolve('reapply');assert.equal(s.value.rows[0].title,'local');assert.equal(s.value.rows[1].title,'remote');assert.equal(s.base.revision,2)});
test('explicit local conflict wins only after reapply',()=>{const b=plan(),l=C.clone(b),r=C.clone(b);l.title='local';r.title='remote';r.revision=2;assert.equal(C.rebaseDraft(b,l,r).title,'local');assert.equal(C.rebaseDraft(b,l,r).revision,2)});
test('deleted remote edited object is not resurrected',()=>{const b=plan(),l=C.clone(b),r=C.clone(b);l.rows[0].title='changed';r.rows.shift();assert.throws(()=>C.rebaseDraft(b,l,r))});
test('rebase refuses editing newly protected object',()=>{const b=plan(),l=C.clone(b),r=C.clone(b);l.rows[0].title='changed';r.rows[0].readonly=true;assert.throws(()=>C.rebaseDraft(b,l,r))});
test('remote addition survives local edit',()=>{const b=plan(),l=C.clone(b),r=C.clone(b);l.title='local';r.rows.push({id:'c',title:'C'});assert.equal(C.rebaseDraft(b,l,r).rows.length,3)});
test('new revision invalidates obsolete undo history',()=>{const s=new C.EditSession(plan()),p=plan();p.title='change';s.preview(p,{});s.commit();const remote=plan();remote.revision=8;s.load(remote);assert.equal(s.history.length,0)});
test('reject unknown graph kind',()=>{const g=graph();g.nodes[0].kind='unknown';assert.throws(()=>C.graphData(g))});
test('reject nonfinite graph geometry',()=>{for(const v of [NaN,Infinity,-Infinity]){const g=graph();g.nodes[0].x=v;assert.throws(()=>C.graphData(g))}});
test('reject invalid graph extent',()=>{const g=graph();g.nodes[0].width=1;assert.throws(()=>C.graphData(g))});
test('reject orphan group membership',()=>{const g=graph();g.nodes[0].parentId='missing';assert.throws(()=>C.graphData(g))});
test('reject group containment cycle',()=>{const g=graph();for(const n of g.nodes)n.kind='group';g.nodes[0].parentId='b';g.nodes[1].parentId='a';assert.throws(()=>C.graphData(g))});
test('checklist items have actual labels',()=>{const g=graph();g.nodes[0].kind='checklist';g.nodes[0].items=[{checked:false}];assert.throws(()=>C.graphData(g))});
test('map cycles allowed but auto layout refuses',()=>{const g=graph();g.edges.push({id:'ba',source:'b',target:'a'});assert.equal(C.graphData(g).edges.length,2);assert.throws(()=>C.layoutGraph(g))});
test('auto layout respects actual dimensions',()=>{const g=graph();g.nodes[0].width=640;const n=C.layoutGraph(g);assert.ok(n.nodes[1].x>=n.nodes[0].x+n.nodes[0].width+80)});
test('auto layout does not move readonly objects',()=>{const g=graph();g.nodes[0].readonly=true;assert.throws(()=>C.layoutGraph(g))});
test('nested group descendants collected recursively',()=>{assert.deepEqual([...descendants([{id:'g'},{id:'c',parentId:'g'},{id:'n',parentId:'c'},{id:'x'}],'g')],['g','c','n'])});
test('edge geometry contains finite coordinates for forward and reverse links',()=>{const [a,b]=graph().nodes;for(const [s,t]of[[a,b],[b,a]]){const g=edgeGeometry(s,t);assert.ok(!/NaN|Infinity/.test(g.path));assert.ok(Number.isFinite(g.x)&&Number.isFinite(g.y))}});
test('unsafe media URLs never emitted',()=>{for(const u of ['javascript:alert(1)','data:text/html,x','http://example.com/a','file:///x'])assert.equal(C.safeMedia(u),'');assert.ok(C.safeMedia('https://example.com/x'));assert.ok(C.safeMedia('data:image/png;base64,AA=='))});
test('normalization retains zeros and negatives; gaps not zero',()=>{const {data,missing}=C.chartData({labels:['a','b','c','d','e'],series:[{id:'x',values:[0,-3,null,NaN,Infinity]}]});assert.deepEqual(data.series[0].values,[0,-3,null,null,null]);assert.equal(missing,3)});
test('chart labels and values length must match',()=>assert.throws(()=>C.chartData({labels:['a'],series:[{id:'x',values:[]}]})));
test('chart series IDs unique',()=>assert.throws(()=>C.chartData({labels:['a'],series:[{id:'x',values:[1]},{id:'x',values:[2]}]})));
test('nice axis at ordinary scale',()=>{const s=chartScale([31,94]);assert.equal(s.high,100);assert.deepEqual(s.ticks,[0,25,50,75,100])});
for(const values of [[0,0],[-10,-20],[1e308,-1e308],[1e-310,2e-310],[-2,3]])test('finite chart domain '+values.join(','),()=>{const s=chartScale(values);assert.ok(Number.isFinite(s.range)&&s.range>0);assert.ok(s.ticks.every(t=>Number.isFinite(t*s.maximum)))});
test('empty label and duplicate option refused',()=>{assert.throws(()=>optionList([{value:'a',label:''}]));assert.throws(()=>optionList([{value:'a',label:'A'},{value:'a',label:'B'}]))});
test('option normalization retains disabled and description',()=>assert.deepEqual(optionList([{value:'a',label:'A',disabled:true,description:'test'}])[0],{value:'a',label:'A',description:'test',disabled:true}));

test('generated IDs are nonempty, distinct and prefix-scoped',()=>{const ids=Array.from({length:1000},()=>C.newId('node'));assert.equal(new Set(ids).size,1000);assert.ok(ids.every(id=>id.startsWith('node-')&&id.length>10))});
