'use strict';
const C=require('./advanced-core.js'),{icon}=require('./components.js'),U=require('./ui.js');
const roadmapDemo={title:'Выпуск 2.5',revision:1,rows:[
 {id:'REL-01',title:'Утвердить концепцию',start:'2026-09-01',end:'2026-09-04',progress:100,status:'done'},
 {id:'REL-02',title:'Проверить интерактивный прототип',start:'2026-09-05',end:'2026-09-09',progress:60},
 {id:'REL-03',title:'Реализовать основной сценарий',start:'2026-09-10',end:'2026-09-19',progress:25},
 {id:'REL-04',title:'Проверить релизную сборку',start:'2026-09-20',end:'2026-09-25',blocked:true,blockReason:'Нужна тестовая среда. Изменение разблокирует приложение.'},
 {id:'REL-05',title:'Опубликовать выпуск',start:'2026-09-28',end:'2026-09-28',kind:'milestone'},
 {id:'REL-06',title:'Подготовить документацию',start:'2026-09-04',end:'2026-09-22',readonly:true}
 ],dependencies:[{id:'dep-1',from:'REL-01',to:'REL-02',type:'FS'},{id:'dep-2',from:'REL-02',to:'REL-03',type:'FS'},{id:'dep-3',from:'REL-03',to:'REL-04',type:'FS'},{id:'dep-4',from:'REL-04',to:'REL-05',type:'FS'}]};
const graphDemo={title:'Как сделать первый шаг понятным',revision:1,nodes:[
 {id:'context',kind:'group',title:'Основания решения',x:24,y:28,width:334,height:494},
 {id:'note',parentId:'context',kind:'note',title:'Сначала результат, потом настройки',text:'Гипотеза: человеку проще начать, когда ожидаемый результат виден до заполнения свойств.',x:44,y:94,width:294,height:190},
 {id:'evidence',parentId:'context',kind:'checklist',title:'Как проверим гипотезу',items:[{label:'Понятно, что получится',checked:true},{label:'Есть следующий шаг',checked:false},{label:'Можно вернуться назад',checked:false}],x:44,y:306,width:294,height:190},
 {id:'task',kind:'task',title:'Прототип первого действия',text:'Показать цель, исходные материалы и одно основное действие. Не раскрывать все настройки сразу.',x:500,y:122,width:302,height:202},
 {id:'media',kind:'media',title:'Рабочий бриф',url:require('./sample-data.js').pdfSamplePreview,alt:'Демонстрационный бриф релиза с разделами цели, объёма и проверки',x:500,y:378,width:302,height:214},
 {id:'archive-1',kind:'note',title:'Ранняя версия',text:'Начинали с длинной формы настроек.',x:44,y:560,width:294,height:180,archived:true}
],edges:[{id:'edge-1',source:'note',target:'task',kind:'supports',label:'Предлагает решение'},{id:'edge-2',source:'evidence',target:'task',kind:'supports',label:'Задаёт критерии'},{id:'edge-3',source:'task',target:'media',kind:'relates',label:'Опирается на бриф'}]};
const workflowDemo={title:'От запроса до готового выпуска',revision:1,nodes:[
 {id:'request',kind:'note',title:'Принять запрос',text:'Цель и ожидаемый результат.',x:40,y:76,width:260,height:160,status:'done'},
 {id:'work',kind:'task',title:'Подготовить решение',text:'Выполнить согласованный объём.',x:400,y:76,width:260,height:160},
 {id:'review',kind:'checklist',title:'Проверить результат',items:[{label:'Критерии выполнены',checked:false},{label:'Изменения согласованы',checked:false}],x:400,y:342,width:260,height:174},
 {id:'release',kind:'task',title:'Опубликовать выпуск',text:'Передать проверенный результат команде.',x:40,y:342,width:260,height:174}
],edges:[{id:'flow-1',source:'request',target:'work',kind:'depends',label:'Запрос принят'},{id:'flow-2',source:'work',target:'review',kind:'depends',label:'Готово к проверке'},{id:'flow-3',source:'review',target:'release',kind:'depends',label:'Согласовано'}]};
const chartDemo={title:'Завершённые задачи',description:'Результаты команды за апрель — сентябрь.',unit:'Задачи',xLabel:'Месяц',labels:['Апр','Май','Июн','Июл','Авг','Сен'],series:[{id:'done',label:'Завершено',values:[31,49,41,70,60,81]}]};
function registerAdvanced(){const defs={'iq-roadmap':require('./roadmap.js').IqRoadmap,'iq-graph':require('./graph.js').IqGraph,'iq-remote-combobox':require('./remote-inputs.js').IqRemoteCombobox,'iq-tag-input':require('./remote-inputs.js').IqTagInput,'iq-data-chart':require('./data-chart.js').IqDataChart,'iq-image-crop':require('./image-crop.js').IqImageCrop};for(const [name,ctor]of Object.entries(defs))if(!customElements.get(name))customElements.define(name,ctor)}
class IqExtensionDemo extends HTMLElement{
 connectedCallback(){this.events?.abort();this.events=new AbortController();const signal=this.events.signal;this.kind=this.getAttribute('kind')||'roadmap';this.mode='ready';this.build();this.addEventListener('iq-change',(e)=>{if(e.target===this.querySelector('[data-demo-state]')){e.stopPropagation();this.setMode(String(e.detail.value));return}if(e.target===this.component){this.feedback('Изменение применено в данных примера.');this.refreshData()}},{signal});
 this.addEventListener('iq-preview',e=>{if(e.target===this.component){this.feedback('Есть черновик. Выберите «Применить» или «Отменить».');this.refreshData()}},{signal});
 this.addEventListener('iq-retry',()=>this.setMode('ready'),{signal});this.addEventListener('iq-query',e=>this.feedback(`Поиск «${e.detail.query||'все'}», страница ${e.detail.cursor==null?1:Math.floor(+e.detail.cursor/15)+1}. Локальный источник.`),{signal});
 this.addEventListener('iq-change-request',e=>{if(e.target===this.component&&this.kind!=='tags'&&this.component.controlled&&e.detail.accept){this.pendingRequest=e.detail;this.querySelector('[data-demo-commit-actions]')?.removeAttribute('hidden')}if(e.target===this.component&&this.kind==='tags'){this.component.value=e.detail.value;this.feedback('Управляемое значение принято владельцем.');this.refreshData()}},{signal});
 this.addEventListener('click',e=>{if(e.target.closest('[data-demo-hierarchy]')){const v=C.clone(roadmapDemo);v.rows.forEach(r=>r.parentId='epic');v.rows.push({id:'goal',kind:'goal',title:'Сделать первый запуск понятным',start:'2026-09-01',end:'2026-09-30'},{id:'epic',kind:'epic',parentId:'goal',title:'Подготовить выпуск',start:'2026-09-01',end:'2026-09-28'},{id:'later',parentId:'goal',title:'Собрать обратную связь после выпуска',start:null,end:null});this.component.data=v;this.refreshData();}if(e.target.closest('[data-demo-accept]')){const v=this.component.data;v.revision=Number(v.revision||0)+1;this.pendingRequest?.accept(v);this.pendingRequest=null;this.querySelector('[data-demo-commit-actions]').hidden=true;this.feedback('Изменение принято в локальном примере.');this.refreshData()}if(e.target.closest('[data-demo-reject]')){this.pendingRequest?.reject('Сохранение отклонено в тестовом сценарии. Черновик сохранён.');this.pendingRequest=null;this.querySelector('[data-demo-commit-actions]').hidden=true;this.feedback('Показано отклонение сохранения. Можно повторить применение.')}if(e.target.closest('[data-demo-reset]'))this.setMode('ready');if(e.target.closest('[data-demo-empty-tags]')){this.component.value=[];this.refreshData()}if(e.target.closest('[data-demo-replace-tags]')){this.component.value=['Проверка','Интерфейс'];this.refreshData()}if(e.target.closest('[data-demo-chart-alternate]')){this.component.data={title:'Изменение баланса',unit:'Единицы',labels:['Пн','Вт','Ср','Чт','Пт'],series:[{id:'balance',label:'Баланс',values:[-12,18,NaN,22,0]},{id:'forecast',label:'Прогноз',values:[-5,20,14,25,Infinity]}]};this.refreshData()}if(e.target.closest('[data-demo-presence]')){this.presenceOn=!this.presenceOn;this.component.presence=this.presenceOn?[{id:'p1',label:'Мария (пример)',cursor:{x:655,y:340},editingNodeId:'task'}]:[];this.feedback('Только входные данные присутствия. Сетевая синхронизация не подключена.')}},{signal})
 }
 disconnectedCallback(){this.events?.abort();this.providerAbort?.abort()}
 build(){const opts=this.kind==='remote'?[['ready','Обычный поиск'],['error','Ошибка источника'],['loading','Загрузка'],['empty','Нет результатов'],['readonly','Только чтение'],['disabled','Недоступно']]:this.kind==='tags'?[['ready','Редактирование'],['readonly','Только чтение'],['disabled','Недоступно']]:this.kind==='chart'?[['ready','Есть данные'],['loading','Загрузка'],['empty','Нет данных'],['error','Ошибка']]:[['ready','Редактирование'],['readonly','Только чтение'],['blocked','Заблокировано'],['loading','Загрузка'],['empty','Нет данных'],['error','Ошибка'],['conflict','Конфликт версий'],['pending','Ожидание принятия']];
 this.innerHTML=`<div class="extension-demo-head"><div><span class="iq-badge sample">05.2</span><span>Локальные данные. API не подключён.</span></div>${U.select('Проверить состояние',opts.map(([value,label])=>({value,label})),'value="ready" data-demo-state')}</div><div data-extension-mount></div><div class="extension-demo-commit-actions" data-demo-commit-actions hidden><span>Ответ локального примера</span><button type="button" class="iq-btn secondary sm" data-demo-accept>Принять</button><button type="button" class="iq-btn secondary sm" data-demo-reject>Отклонить</button></div><div class="extension-demo-foot"><span data-extension-feedback>Выберите объект или измените данные.</span><button type="button" class="iq-btn ghost sm" data-demo-reset>Сбросить пример ${icon('refresh',15)}</button></div><details class="extension-data-details"><summary>Данные и текущий черновик</summary><pre data-extension-json></pre></details>`;
 const mount=this.querySelector('[data-extension-mount]');
 if(this.kind==='remote'){mount.innerHTML='<div class="extension-demo-fields"><h3>Кто продолжит работу?</h3><p>Поиск с постраничной выдачей. Выбранный участник остаётся выбранным, даже когда его нет в текущих результатах.</p><iq-remote-combobox label="Ответственный" placeholder="Найти участника" name="assignee"></iq-remote-combobox></div>';this.component=mount.querySelector('iq-remote-combobox');const names=['Александр Ким','Мария Лебедева','Дмитрий Соколов','Анна Волкова','Ирина Морозова','Никита Орлов'];this.component.provider=async({query,cursor,signal})=>{await new Promise((resolve,reject)=>{const t=setTimeout(resolve,this.mode==='loading'?600000:260);signal.addEventListener('abort',()=>{clearTimeout(t);reject(new DOMException('Aborted','AbortError'))},{once:true})});if(this.mode==='error')throw Error('Источник временно недоступен');const list=Array.from({length:90},(_,i)=>({value:'person-'+i,label:names[i%names.length]+(i>=6?' '+(Math.floor(i/6)+1):''),description:i%2?'Продуктовая команда':'Дизайн и исследование'})).filter(o=>o.label.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));const start=+cursor||0,options=this.mode==='empty'?[]:list.slice(start,start+15);return{options,nextCursor:this.mode==='empty'||start+15>=list.length?null:String(start+15)}};this.component.selectedOption={value:'person-1',label:'Мария Лебедева'};}
 else if(this.kind==='tags'){mount.innerHTML='<div class="extension-demo-fields is-tags"><h3>Метки проекта</h3><p>Владелец передаёт значение и принимает изменения. Пустой массив — полноценное состояние, не повод добавлять демонстрационные метки.</p><iq-tag-input label="Метки" max="5" maxlength="28" name="tags"></iq-tag-input><div class="extension-demo-foot"><button type="button" class="iq-btn secondary sm" data-demo-empty-tags>Очистить метки</button><button type="button" class="iq-btn secondary sm" data-demo-replace-tags>Заменить набор</button></div></div>';this.component=mount.querySelector('iq-tag-input');this.component.controlled=true;this.component.value=['Дизайн','Релиз']}
 else if(this.kind==='chart'){mount.innerHTML='<iq-data-chart type="bar"></iq-data-chart><div class="extension-demo-foot"><button type="button" class="iq-btn ghost sm" data-demo-chart-alternate>Данные с пропусками и отрицательными значениями</button></div>';this.component=mount.querySelector('iq-data-chart');this.component.data=C.clone(chartDemo)}
 else{mount.innerHTML=this.kind==='roadmap'?'<iq-roadmap></iq-roadmap><div class="extension-demo-foot"><button type="button" class="iq-btn secondary sm" data-demo-hierarchy>Цель, эпик и задачи без дат</button></div>':`<iq-graph mode="${this.kind==='workflow'?'workflow':'map'}"></iq-graph>${this.kind==='map'?'<button type="button" class="iq-btn ghost sm" data-demo-presence>Показать участника</button>':''}`;this.component=mount.querySelector('iq-roadmap,iq-graph');const sample=C.clone(this.kind==='roadmap'?roadmapDemo:this.kind==='workflow'?workflowDemo:graphDemo);this.exampleData=C.clone(sample);this.component.data=sample;if(this.kind==='roadmap'){this.component.range={start:'2026-09-01',end:'2026-09-30'};this.component.today='2026-09-06'}}
 this.refreshData()
 }
 setMode(mode){this.pendingRequest=null;const ca=this.querySelector('[data-demo-commit-actions]');if(ca)ca.hidden=true;this.mode=mode;const picker=this.querySelector('[data-demo-state]');if(picker)picker.value=mode;const el=this.component;if(['remote','tags'].includes(this.kind)){if(this.kind==='tags'&&mode==='ready')el.value=['Дизайн','Релиз'];el.disabled=mode==='disabled';el.toggleAttribute('readonly',mode==='readonly');if(this.kind==='remote'&&!el.disabled&&mode!=='readonly'){el.open=true;el.query='';el.request(false)}this.feedback(mode==='ready'?'Источник готов.':'Показано выбранное состояние.');return}
 if(this.kind==='chart'){el.state=mode;if(mode==='ready')el.data=C.clone(chartDemo);this.refreshData();return}
 el.invalidateRequest?.();el.session.cancel();el.pending=false;el.controlled=false;el.readonly=mode==='readonly';el.state=['loading','error','empty','blocked'].includes(mode)?mode:'ready';el.data=C.clone(this.exampleData);el.selectedId='';el.issue='';
 if(mode==='conflict'||mode==='pending'){el.readonly=false;el.state='ready';const next=el.data;if(this.kind==='roadmap'){next.rows[0].title='Уточнить концепцию выпуска';el.preview(next,{kind:'title',id:next.rows[0].id})}else{next.nodes.find(n=>n.kind!=='group').title='Уточнённая локальная гипотеза';el.preview(next,{kind:'title'})}if(mode==='conflict'){const remote=C.clone(this.exampleData);if(remote.rows?.[1])remote.rows[1].title+=' (новая версия)';if(remote.nodes?.[1])remote.nodes[1].text='Уточнение из внешней версии.';remote.revision=2;el.data=remote}else{el.controlled=true;el.requestCommit()}}
 this.feedback(mode==='ready'?'Пример сброшен. Данные локальные.':'Состояние '+mode+' показано на тех же данных.');this.refreshData()
 }
 feedback(text){const el=this.querySelector('[data-extension-feedback]');if(el){el.textContent=text;el.setAttribute('role','status')}}
 refreshData(){const out=this.querySelector('[data-extension-json]');if(out)out.textContent=JSON.stringify(this.component?.data??{value:this.component?.value,selectedOption:this.component?.selectedOption},null,2)}
}
const code={
 roadmap:`<iq-roadmap id="roadmap"></iq-roadmap>\n<script type="module">\nimport {registerIquipage} from './dist/iquipage.js';\nregisterIquipage();\nconst view = document.querySelector('#roadmap');\nview.data = {revision: 1, rows: [\n {id: 'a', title: 'Проверить прототип', start: '2026-09-01', end: '2026-09-05'},\n {id: 'b', kind: 'milestone', title: 'Выпуск', start: '2026-09-06', end: '2026-09-06'}\n], dependencies: [{id: 'ab', from: 'a', to: 'b', type: 'FS'}]};\nview.controlled = true;\nview.addEventListener('iq-change-request', async ({detail}) => {\n try { detail.accept(await savePlan(detail.value, detail.baseRevision)); }\n catch { detail.reject('Не удалось сохранить. Черновик остался на месте.'); }\n});\n// savePlan — адаптер приложения, не часть дизайн-системы.\n</script>`,
 map:`<iq-graph id="map"></iq-graph>\n<script type="module">\nimport {registerIquipage} from './dist/iquipage.js';\nregisterIquipage();\nconst map = document.querySelector('#map');\nmap.data = {revision: 1, nodes: [\n {id: 'a', kind: 'note', title: 'Гипотеза', x: 40, y: 40, width: 240, height: 160},\n {id: 'b', kind: 'task', title: 'Проверка', x: 380, y: 40, width: 240, height: 160}\n], edges: [{id:'ab',source:'a',target:'b',kind:'supports'}]};\nmap.presence = []; // Входные данные реального канала приложения.\n</script>`,
 workflow:`<iq-graph mode="workflow" id="workflow"></iq-graph>\n<script type="module">\nimport {registerIquipage, layoutGraph} from './dist/iquipage.js';\nregisterIquipage();\n// Тот же graph kit. Никакого второго расходящегося визуального API.\ndocument.querySelector('#workflow').data = layoutGraph(processData);\n// processData — nodes / edges приложения; циклы в авторазмещении запрещены.\n</script>`,
 remote:`<iq-remote-combobox id="assignee" label="Ответственный"></iq-remote-combobox>\n<script type="module">\nimport {registerIquipage} from './dist/iquipage.js';\nregisterIquipage();\nconst input = document.querySelector('#assignee');\ninput.provider = ({query, cursor, signal}) => searchPeople({query, cursor, signal});\n// Promise<{options: {value, label, description?}[], nextCursor: string|null}>\ninput.selectedOption = {value:'person-42',label:'Анна Волкова'};\n// Или реагируйте на iq-query и передавайте setResult(result, requestId).\n</script>`,
 tags:`<iq-tag-input id="tags" label="Метки" max="5" maxlength="28"></iq-tag-input>\n<script type="module">\nimport {registerIquipage} from './dist/iquipage.js';\nregisterIquipage();\nconst tags = document.querySelector('#tags');\ntags.controlled = true;\ntags.value = [];\ntags.addEventListener('iq-change-request', ({detail}) => {\n tags.value = detail.value; // Принятие владельцем.\n});\n</script>`,
 chart:`<iq-data-chart id="chart" type="line"></iq-data-chart>\n<script type="module">\nimport {registerIquipage} from './dist/iquipage.js';\nregisterIquipage();\ndocument.querySelector('#chart').data = {\n title:'Завершено задач', labels:['Апр','Май','Июн'],\n series:[{id:'done',label:'Завершено',values:[31,49,null]}]\n};\n// null, NaN и Infinity — разрывы, не нули.\n</script>`
};
function installAdvancedStories(){registerAdvanced();if(!customElements.get('iq-extension-demo'))customElements.define('iq-extension-demo',IqExtensionDemo);const {stories,categories}=require('./stories.js'),edition=require('./edition.js');if(stories.some(s=>s.id==='roadmap'))return;categories.push({id:'advanced',name:'Планирование и связи',icon:'link'});
 const specs=[['roadmap','roadmap','Roadmap','Длительности, вехи и зависимости','План начала и завершения работы. Календарь сроков остаётся отдельным компонентом.','Даты включительны; FS/SS/FF/SF и lagDays. Изменения проходят preview → request → accept/reject. Связи не перепланируют задачи автоматически.','Выберите интервал. Стрелки сдвигают на день, Shift — на неделю, Alt — завершение. Enter применяет черновик; Escape отменяет. Точный ввод дат доступен без перетаскивания.'],['idea-map','map','Idea map','Карта идей','Заметки, задачи, проверки и материалы сохраняют пространственный контекст.','Общий graph kit: пять типов узлов, порты, направленные связи, архив, миникарта и входные данные присутствия. Совместный сервер не имитируется.','Tab — объекты и действия; Enter — свойства. Стрелки — соседний объект. Alt + стрелки — положение, Alt + Shift + стрелки — размер. Связи доступны формой и через порты.'],['workflow-graph','workflow','Workflow graph','Граф процесса','Порядок работы и отношения в том же визуальном языке карты.','Один компонент iq-graph с режимом workflow. Семантика relates/depends/supports, подписи и состояния связей. Авторазмещение — только для DAG; текстовая альтернатива сохраняет направления.','Выбор узлов и связей с клавиатуры. Изменение в свойствах, без drag. На мобильном — список отношений.'],['remote-combobox','remote','Remote combobox','Поиск по источнику','Постраничный выбор с отменой устаревших запросов и сохранением выбранной опции.','Источник задаётся provider либо событиями iq-query/setResult. Loading/error/retry/no-results, AbortSignal, requestId и nextCursor. Ни URL, ни сетевого клиента внутри DS нет.','Стрелки — варианты, Enter — выбрать, Escape — закрыть. Ввод сохраняет фокус; загрузить ещё и повторить доступны отдельными кнопками.'],['tag-input','tags','Controlled tags','Управляемые метки','Пустое значение, внешняя замена, ограничения и отключение — без демонстрационных значений внутри компонента.','value — массив уникальных строк. В controlled-режиме владелец принимает iq-change-request через setter. Предусмотрены max/maxlength/disabled/readonly.','Enter или запятая — добавить. Backspace в пустом поле — удалить последнюю метку. Кнопки удаления имеют собственные подписи.'],['data-chart','chart','Data chart','Диаграмма данных','Ряды, оси, легенда и таблица строятся из переданных чисел.','Линии и сгруппированные столбцы, отрицательные значения, разрывы nonfinite, легенда, tooltip и таблица. Единый контракт диаграммы из раздела «Данные».','Стрелки в графике выбирают период и ряд; Enter сообщает выбранную точку приложению. Таблица доступна независимо от графического вида.']];
 for(const[id,kind,canonical,title,description,usage,keyboard]of specs){stories.push({id,category:'advanced',title,description,usage,keyboard,demo:()=>`<iq-extension-demo kind="${kind}"></iq-extension-demo>`,code:code[kind],states:`<table class="extension-state-table"><thead><tr><th>Состояние</th><th>Контракт</th></tr></thead><tbody>${[['Ready','Входные данные получены. Изменения разрешены отдельно.'],['Loading / pending','Ожидание данных и ожидание принятия изменений — разные состояния.'],['Empty / no-results','Нет данных не означает сбой.'],['Error / retry','Повторный запрос передаётся приложению.'],['Readonly / disabled / blocked','Нельзя менять значение; данные остаются читаемыми.'],['Conflict','Черновик не затирается новой версией. Владелец выбирает разрешение.']].map(([a,b])=>`<tr><th>${a}</th><td>${b}</td></tr>`).join('')}</tbody></table><p class="spec-note">Применимые состояния можно включить в селекторе над живым примером. Полные различия контрактов перечислены в docs/EXTENSION-API.md.</p>`});edition.originalNames.set(id,canonical)}
 const unified=stories.find(s=>s.id==='data-chart'),legacy=stories.find(s=>s.id==='chart');
 if(unified&&legacy){Object.assign(legacy,unified,{id:'chart',category:'data',title:'Диаграмма'});stories.splice(stories.indexOf(unified),1);edition.originalNames.set('chart','Data chart')}
 stories.push({id:'image-crop',category:'files',title:'Кадрирование изображения',description:'Ручной выбор области, масштаб и точное положение кадра. Оригинал остаётся неизменным.',usage:'Публичный iq-image-crop принимает File / Blob. Квадратный кадр задаётся в пикселях источника; export() возвращает Blob. Серверная загрузка остаётся в приложении.',keyboard:'Стрелки перемещают кадр на 1 пиксель, Shift — на 10. Масштаб и положение доступны ползунками. Escape отменяет текущий жест.',demo:()=>'<iq-image-crop></iq-image-crop>',code:'<iq-image-crop id="crop"></iq-image-crop>\n<script type="module">\nimport { registerIquipage } from "./dist/iquipage.js";\nregisterIquipage();\n// crop.source = file; await crop.export({size:512});\n</script>',states:'Загрузка, пустое состояние, ошибка файла, только чтение, ожидание принятия и отмена. Экспорт не считается загрузкой на сервер.'});edition.originalNames.set('image-crop','Image crop');
 const original=edition.examplesView;edition.examplesView=()=>{const footer=edition.siteFooter();return original().replace(footer,`<section class="page-shell extension-scenarios"><div class="section-intro"><span class="sample-overline">05.2 / РАСШИРЕНИЕ</span><h2>План, контекст и проверяемые данные.</h2><p>Новые поверхности работают на управляемых данных и не заменяют существующие сценарии.</p></div><div class="extension-example-links">${specs.filter(s=>s[0]!=='data-chart').map(([id,,canonical,title])=>`<a href="#components/${id}"><span>${canonical}</span><h3>${title}</h3>${icon('arrow',18)}</a>`).join('')}</div></section>`+footer)};
}
Object.assign(exports,{registerAdvanced,installAdvancedStories,roadmapDemo,graphDemo,workflowDemo,chartDemo});

