"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.installRevision = installRevision;
const stories_js_1 = require("./stories.js");
const components_js_1 = require("./components.js");
const ui_js_1 = require("./ui.js");
function installRevision() {
    const set = (id, demo) => {
        const story = stories_js_1.stories.find(s => s.id === id);
        if (story)
            story.demo = demo;
    };
    const metric = (withChart) => `<div class="iq-metric refined-metric metric-042"><header><h3>Закрыто задач</h3>${ui_js_1.badge('Образец', '', false)}</header><div class="metric-measure"><strong>128</strong><div><span>из 160</span><small>за сентябрь</small></div></div>${withChart ? `<figure class="metric-chart"><figcaption class="sr-only">Демонстрация динамики завершённых задач за сентябрь.</figcaption>${ui_js_1.sparkline()}<div><span>1 сентября</span><span>30 сентября</span></div></figure>` : ''}${!withChart ? `<div class="metric-track"><span>Выполнено 80%</span>${ui_js_1.progress(80, 'Закрыто 128 из 160 задач')}</div>` : ''}<footer class="metric-foot"><span class="metric-delta positive">${components_js_1.icon('arrowUp', 16)}18 больше</span><span>чем в прошлом периоде</span></footer></div>`;
    set('metric', () => `<div class="metric-variants">${ui_js_1.tabs([{ key: 'number', label: 'Показатель', body: metric(false) }, { key: 'chart', label: 'С динамикой', body: metric(true) }], 'label="Вариант показателя"')}</div>`);
    set('timeline', () => `<div class="activity-panel activity-042" data-activity><header><h3>История работы</h3>${ui_js_1.badge('Образец', '', false)}</header><div class="activity-filters" role="group" aria-label="Тип событий">${[['all', 'Все'], ['decisions', 'Решения'], ['materials', 'Материалы'], ['system', 'Изменения']].map(([id, label]) => `<button type="button" data-event-filter="${id}" aria-pressed="${id === 'all'}">${label}</button>`).join('')}</div><div class="activity-days"><section data-event-day><h4>4 сентября</h4><div>
 <article class="activity-event" data-event-type="decisions"><span class="event-symbol decisions">${components_js_1.icon('check', 17)}</span><div><b>Макет проверен</b><p>Мария Лебедева</p></div><time>16:40</time></article>
 <article class="activity-event" data-event-type="materials"><span class="event-symbol">${components_js_1.icon('file', 17)}</span><div><details><summary><b>Добавлены 2 документа</b>${components_js_1.icon('down', 14)}</summary><div class="event-files"><span>${components_js_1.icon('file', 15)}Описание релиза.pdf</span><span>${components_js_1.icon('checklist', 15)}Критерии готовности.md</span></div></details><p>К задаче SPR-128</p></div><time>15:10</time></article>
 <article class="activity-event" data-event-type="system"><span class="event-symbol">${components_js_1.icon('sliders', 17)}</span><div><details><summary><b>Изменены срок и ответственный</b>${components_js_1.icon('down', 14)}</summary><dl class="event-changes"><div><dt>Срок</dt><dd><del>16 сентября</del>${components_js_1.icon('arrow', 12)}18 сентября</dd></div><div><dt>Ответственный</dt><dd>Мария Лебедева</dd></div><div><dt>Статус</dt><dd>На проверке</dd></div></dl></details><p>3 изменения в одной записи</p></div><time>14:20</time></article>
 </div></section><section data-event-day><h4>3 сентября</h4><div><article class="activity-event" data-event-type="decisions"><span class="event-symbol">${components_js_1.icon('message', 17)}</span><div><b>Гипотеза принята</b><p>Александр Ким</p></div><time>11:30</time></article></div></section></div><span class="sr-only" role="status" data-event-count>4 события</span></div>`);
    set('card', () => `<div class="iq-card"><div class="iq-card-head"><h3>Следующий релиз</h3>${ui_js_1.badge('В работе', 'info')}</div><p class="muted">Единый контекст, понятная цель и критерии готовности.</p><div class="iq-card-foot"><span class="card-date">${components_js_1.icon('calendar', 16)}18 сентября</span>${ui_js_1.avatars()}</div></div>`);
    set('frost-surface', () => `<div class="refined-context context-042"><div class="context-record"><div><span class="sample-overline">РАБОЧИЙ ДОКУМЕНТ</span><h3>Концепция коллекции</h3></div><span class="document-symbol">${components_js_1.icon('file', 30)}</span><dl><div><dt>Версия</dt><dd>03</dd></div><div><dt>Автор</dt><dd>Мария Лебедева</dd></div></dl><footer class="context-record-footer"><span>${components_js_1.icon('check', 16)}Сохранено локально</span><a class="iq-link" href="#workspace/tasks">Продолжить работу ${components_js_1.icon('arrow', 16)}</a></footer></div></div>`);
    const editor = { id: 'markdown-editor', category: 'fields', title: 'Редактор Markdown', description: 'Форматирование, история и предпросмотр — в одном рабочем поле.', usage: 'Полный набор для документов; компактный — для панелей; компактный по высоте, с полным набором инструментов — для комментариев. Сохраняется обычный Markdown. HTML в предпросмотре не исполняется. Изображения добавляются ссылкой, а загрузка файла остаётся отдельной операцией.', keyboard: 'Tab — группы инструментов. ←/→ — инструменты. Ctrl/⌘ B, I, K — форматирование. Ctrl/⌘ Z и Shift Z — отмена и повтор. Поле автоматически меняет высоту.', demo: () => `<div class="editor-variants">${ui_js_1.tabs([{ key: 'full', label: 'Документ', body: '<iq-markdown-editor label="Документ" value="## Следующий релиз&#10;&#10;Опишите результат и критерии готовности.&#10;&#10;- [ ] Проверить состояния&#10;- [ ] Согласовать материалы"></iq-markdown-editor>' }, { key: 'compact', label: 'В панели', body: '<iq-markdown-editor variant="compact" label="Описание задачи"></iq-markdown-editor>' }, { key: 'minimal', label: 'Комментарий', body: '<iq-markdown-editor variant="minimal" label="Комментарий" submit-label="Отправить"></iq-markdown-editor>' }], 'label="Вариант редактора Markdown"')}</div>` };
    if (!stories_js_1.stories.some(s => s.id === editor.id))
        stories_js_1.stories.push(editor);
}

