"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.stories = exports.categories = void 0;
exports.storyCard = storyCard;
const components_js_1 = require("./components.js");
const ui_js_1 = require("./ui.js");
const categories = [
    { id: 'actions', name: 'Действия', icon: 'arrow' }, { id: 'fields', name: 'Ввод данных', icon: 'text' }, { id: 'selection', name: 'Выбор', icon: 'sliders' }, { id: 'navigation', name: 'Навигация', icon: 'grid' }, { id: 'data', name: 'Данные', icon: 'chart' }, { id: 'feedback', name: 'Обратная связь', icon: 'bell' }, { id: 'overlays', name: 'Слои и контекст', icon: 'stack' }, { id: 'files', name: 'Файлы', icon: 'upload' }, { id: 'layout', name: 'Поверхности', icon: 'box' }
];
exports.categories = categories;
const S = (id, category, title, description, demo, usage, keyboard = 'Tab — переход. Enter / Space — действие.') => ({ id, category, title, description, demo, usage, keyboard });
const stories = [
S('application-header','layout','Заголовок рабочего экрана','Компактная композиция заголовка, действий и рабочего инструмента.',()=>'<div class="iq-application-layout"><iq-work-header title="План запуска коллекции" eyebrow="IQUIPAGE Studio" description="Один заголовок страницы. Инструменты планирования — на рабочей поверхности ниже."><button slot="actions" class="iq-btn primary" type="button" data-create-task>Новая задача</button></iq-work-header></div>','Один смысловой h1 и группа действий; toolbar сложного компонента остаётся ниже. Длинные названия переносятся без обрезки.','Tab — действия; заголовок сохраняет семантику h1.'),
    S('button', 'actions', 'Button', 'Пять ролей, три размера. Один оптический центр.', () => `<div class="stack lg"><div class="row">${ui_js_1.btn('Продолжить', 'primary', 'arrow')}${ui_js_1.btn('Сохранить', 'secondary', 'check')}${ui_js_1.btn('Подробнее', 'ghost', 'upRight')}</div><div class="row">${ui_js_1.btn('Создать', 'accent', 'plus')}${ui_js_1.btn('Удалить', 'danger', 'trash')}</div><div class="row">${ui_js_1.btn('Small', 'secondary sm')}${ui_js_1.btn('Medium', 'secondary')}${ui_js_1.btn('Large', 'secondary lg')}</div></div>`, 'Одна главная кнопка на локальную задачу. Loading не меняет ширину. Disabled не используется вместо объяснения причины.'),
    S('icon-button', 'actions', 'Icon button', 'Тот же материал. Компактное действие с подписью для скринридера.', () => `<div class="row">${ui_js_1.ib('plus', 'Добавить', 'primary')}${ui_js_1.ib('star', 'В избранное', 'secondary', 'data-toggle aria-pressed="false"')}${ui_js_1.ib('copy', 'Копировать', 'secondary', 'data-copy="IQUIPAGE Optics"')}${ui_js_1.ib('trash', 'Удалить', 'danger', 'data-dialog="confirm-dialog"')}${ui_js_1.ib('more', 'Дополнительные действия', 'ghost')}</div><p class="iq-helper">Область нажатия 42 × 42. В touch-режиме — не меньше 42.</p>`, 'Каждая icon-only кнопка получает конкретный aria-label. В составных группах сохраняется расстояние между целями.'),
    S('split-button', 'actions', 'Split button', 'Основное действие и его варианты не конкурируют.', () => `<div class="iq-split">${ui_js_1.btn('Экспортировать', 'primary', 'download', 'data-export-tokens')}${ui_js_1.menu(ui_js_1.ib('down', 'Формат экспорта', 'primary'), [{ label: 'Токены / JSON', glyph: 'code', action: 'export-tokens' }, { label: 'Пример данных / JSON', glyph: 'file', action: 'export-tasks' }])}</div>`, 'Дополнительное меню открывается отдельно. Основная часть запускает именно подписанное действие.', 'Tab; меню — Enter, ↑/↓, Home/End, Escape. Фокус возвращается к триггеру.'),
    S('button-group', 'actions', 'Button group', 'Группа равнозначных локальных действий.', () => `<div class="iq-btn-group">${ui_js_1.ib('list', 'Список', 'ghost sm', 'data-toggle aria-pressed="true"')}${ui_js_1.ib('board', 'Доска', 'ghost sm', 'data-toggle aria-pressed="false"')}${ui_js_1.ib('calendar', 'Календарь', 'ghost sm', 'data-toggle aria-pressed="false"')}</div><div class="divider"></div><div class="iq-btn-group">${ui_js_1.btn('Копировать', 'ghost sm', 'copy', 'data-copy="Пример текста"')}${ui_js_1.btn('Экспорт', 'ghost sm', 'download', 'data-export-tokens')}</div>`, 'Button group не подменяет Tabs. Для одного взаимоисключающего значения используйте Segmented control.'),
    S('toggle-button', 'actions', 'Toggle action', 'Выбранное состояние отделено от фокуса.', () => `<div class="row">${ui_js_1.btn('В избранное', 'secondary', 'star', 'data-toggle aria-pressed="false"')}${ui_js_1.ib('heart', 'Нравится', 'secondary', 'data-toggle aria-pressed="false"')}${ui_js_1.btn('Закреплено', 'secondary', 'pin', 'data-toggle aria-pressed="true"')}</div>`, 'Подходит для независимого бинарного действия. Состояние доступно через aria-pressed.'),
    S('async-button', 'actions', 'Async action', 'Ожидание, подтверждение и возврат без скачков.', () => `<div class="row">${ui_js_1.btn('Проверить пример', 'primary', 'checkCircle', 'data-async')}${ui_js_1.btn('Недоступно', 'secondary', '', 'disabled')}</div><p class="iq-helper">Демонстрация перехода состояний. Серверная проверка не выполняется.</p>`, 'Во время операции кнопка aria-busy, повторные нажатия блокируются. Ошибка сохраняет введённые данные.'),
    S('link-action', 'actions', 'Link action', 'Переход, а не замаскированная операция.', () => `<div class="stack sm"><a class="iq-link" href="#workspace">Открыть рабочий пример ${components_js_1.icon('arrow', 17)}</a><a class="iq-link" href="#foundations">Посмотреть основу системы ${components_js_1.icon('upRight', 17)}</a><a href="#brand" style="font-size:13px;text-underline-offset:4px">Правила айдентики</a></div>`, 'Для навигации — ссылка с реальным адресом. Для изменения данных — button.', 'Tab и Enter; поддерживаются стандартные действия браузера со ссылкой.'),
    S('copy-button', 'actions', 'Copy action', 'Подтверждение рядом с действием.', () => `<div class="copy-example"><code>--iq-accent: #4256C5</code>${ui_js_1.ib('copy', 'Скопировать токен', 'secondary sm', 'data-copy="--iq-accent: #4256C5;"')}</div>`, 'Результат зависит от разрешений браузера. Ошибка копирования не выдаётся за успех.'),
    S('text-field', 'fields', 'Text field', 'Чёткая граница. Локальная световая линия при вводе.', () => `<div class="stack">${ui_js_1.field('Название пространства', 'IQUIPAGE Studio', { help: 'Имя, которое увидит команда.', name: 'workspace' })}${ui_js_1.field('Название проекта', '', { placeholder: 'Например, новая коллекция' })}</div>`, 'Label всегда виден. Placeholder — пример, не замена имени. Поле должно переживать длинное значение.', 'Нативное редактирование, выделение, IME и автозаполнение браузера.'),
    S('field-states', 'fields', 'Field states', 'Ошибка, подтверждение, read-only и disabled.', () => `<div class="stack">${ui_js_1.field('Рабочая почта', 'alex@', { state: 'error', help: 'Укажите адрес полностью: name@company.com', type: 'email' })}${ui_js_1.field('Адрес пространства', 'iquipage', { state: 'success', help: 'Адрес доступен' })}${ui_js_1.field('Идентификатор', 'IQ-0042', { readonly: true })}${ui_js_1.field('Организация', 'IQUIPAGE', { disabled: true })}</div>`, 'Состояние передаётся текстом, семантикой и границей. Ошибка не обозначается одним цветом.'),
    S('search-field', 'fields', 'Search field', 'Поиск с очисткой и видимым результатом.', () => `<div data-filter-demo>${ui_js_1.field('Найти компонент', '', { icon: 'search', placeholder: 'Button, Field, Select…', name: 'search-components' })}<div class="demo-search-results"><span>Button</span><span>Text field</span><span>Select</span><span>Dialog</span></div><p class="iq-helper" aria-live="polite">4 компонента</p></div>`, 'В локальном поиске результат обновляется без отправки формы. Пустой результат объясняется.'),
    S('text-area', 'fields', 'Text area', 'Свободный текст с контролем длины.', () => ui_js_1.textarea('Описание', 'Собрать общий язык продуктов, не теряя характер каждого.', { maxlength: 280, help: 'Коротко опишите ожидаемый результат.' }), 'Высота меняется автоматически по содержимому. Переносы разрешены; ручного растягивания нет. Счётчик не должен зачитываться на каждую букву.'),
    S('number-field', 'fields', 'Number field', 'Числовой ввод с явными границами.', () => `<div class="number-example"><iq-number label="Количество участников" min="1" max="24" value="6" name="members" aria-describedby="members-hint"></iq-number><p class="iq-helper" id="members-hint">От 1 до 24 участников.</p></div>`, 'Текст можно редактировать напрямую. Кнопки блокируются на min/max. Значение валидируется при change.', '↑/↓ в поле — нативный шаг. Tab — к кнопкам уменьшения и увеличения.'),
    S('password-field', 'fields', 'Password field', 'Скрытие и показ без потери фокуса ввода.', () => `<div class="iq-field"><label class="iq-control-label" for="pass-example">Пароль</label><div class="iq-input-shell">${components_js_1.icon('lock', 17)}<input id="pass-example" type="password" value="Optics-example-2026" autocomplete="new-password">${ui_js_1.ib('eye', 'Показать пароль', 'ghost sm', 'data-password aria-pressed="false"')}</div><small class="iq-helper">Пример интерфейса. Это не проверка надёжности пароля.</small></div>`, 'Не блокировать вставку. Показ пароля — отдельная подписанная кнопка. Автозаполнение остаётся доступным.'),
    S('input-group', 'fields', 'Input group', 'Единица и префикс принадлежат значению.', () => `<div class="stack"><div class="iq-field"><label class="iq-control-label" for="space-url">Адрес пространства</label><div class="iq-input-shell"><span class="iq-input-prefix">iquipage /</span><input id="space-url" value="studio" aria-describedby="url-hint"></div><small class="iq-helper" id="url-hint">Префикс iquipage фиксирован.</small></div><div class="iq-field"><label class="iq-control-label" for="weight-field">Масса изделия</label><div class="iq-input-shell"><input id="weight-field" type="number" value="420" min="0" aria-describedby="weight-unit"><span class="iq-input-suffix" id="weight-unit">грамм</span></div></div></div>`, 'Префикс не должен попадать в редактируемый текст. Единица измерения имеет доступную связь с полем.'),
    S('validated-form', 'fields', 'Form validation', 'Ошибки появляются в контексте, данные сохраняются.', () => `<form data-demo-form novalidate class="stack">${ui_js_1.field('Ваше имя', '', { name: 'name', required: true, placeholder: 'Александр' })}${ui_js_1.field('Почта', '', { type: 'email', name: 'email', required: true, placeholder: 'name@company.com' })}<div data-form-message></div>${ui_js_1.btn('Проверить поля', 'primary', 'arrow', 'data-submit-demo')}</form>`, 'В демо проверяются обязательные значения и формат email. Данные не отправляются. Первый ошибочный контрол получает фокус.'),
    S('select', 'selection', 'Select', 'Собственный popup, поиск с клавиатуры, rich options.', () => `<div class="stack">${ui_js_1.select('Пространство', ui_js_1.projectOptions)}${ui_js_1.select('Роль', ['Редактор', 'Наблюдатель', 'Администратор'])}</div>`, 'Не используем стили браузерного select. Панель открывается в top layer и адаптируется к краю экрана.', '↑/↓, Home/End, поиск по первым буквам, Enter/Space — выбрать, Esc/Tab — закрыть.'),
    S('combobox', 'selection', 'Combobox', 'Редактируемый поиск по набору значений.', () => ui_js_1.combo('Назначить участника', ['Александр Ким', 'Мария Лебедева', 'Дмитрий Соколов', 'Анна Волкова', 'Иван Петров']), 'Введённый текст фильтрует список. Выбор подтверждается явно; Escape возвращает выбранную подпись.', 'Текст — фильтр; ↑/↓ — активная опция; Enter — выбор; Esc — отмена.'),
    S('multi-select', 'selection', 'Tag input', 'Несколько значений без отдельной таблицы.', () => '<iq-tags label="Направления" value="Продукт,Дизайн"></iq-tags>', 'До 8 меток, до 32 символов на метку. Повторные значения не добавляются. Для серверного каталога нужен внешний источник данных.', 'Enter / запятая — добавить. Backspace в пустом поле — удалить последнюю. Кнопки удаления доступны через Tab.'),
    S('checkbox', 'selection', 'Checkbox', 'Независимый выбор и промежуточное состояние.', () => `<div class="stack sm">${ui_js_1.check('Сохранить историю изменений', true)}${ui_js_1.check('Получать письма о релизах')}${ui_js_1.check('Часть проектов выбрана', false, 'data-indeterminate')}${ui_js_1.check('Недоступный параметр', true, 'disabled')}</div>`, 'Нативный input[type=checkbox] с собственной отрисовкой. Состояние indeterminate не равно checked.', 'Tab и Space. В form участвует как обычный checkbox.'),
    S('radio-group', 'selection', 'Radio group', 'Один выбор из видимых альтернатив.', () => ui_js_1.radioGroup('Доступ к пространству', 'access-demo', [
        {value:'invited', label:'Только приглашённые', description:'Доступ по персональному приглашению.'},
        {value:'organization', label:'Все участники организации', description:'Общее пространство вашей команды.'},
        {value:'link', label:'По ссылке', description:'Доступ для тех, у кого есть ссылка.'}
    ], 'invited'), 'Взаимоисключающие варианты объединяются нативными name и fieldset.', 'Tab — вход в группу; стрелки — выбор; Space — отметить.'),
    S('switch', 'selection', 'Switch', 'Параметр меняется сразу, без кнопки сохранения.', () => `<div class="iq-setting-row"><div><b>История версий</b><p>Сохранять изменения документа</p></div>${ui_js_1.toggle('История версий', true, '', false)}</div><div class="iq-setting-row"><div><b>Уведомления</b><p>Только важные обновления</p></div>${ui_js_1.toggle('Уведомления', false, '', false)}</div>`, 'Переключатель применяется к настройке, а не к согласию в форме. Демо меняет только локальный контрол.', 'Tab и Space, role=switch.'),
    S('segmented-control', 'selection', 'Segmented control', 'Короткий набор равнозначных режимов.', () => `<div class="stack">${ui_js_1.segment(['Список', 'Доска', 'План'])}${ui_js_1.segment(['Комфортно', 'Компактно'])}${ui_js_1.segment([components_js_1.icon('sun', 17) + ' Светлая', components_js_1.icon('moon', 17) + ' Тёмная'], 0)}</div>`, 'Используйте для 2–4 режимов. Для смены разделов с собственным содержимым — Tabs.', 'Кнопки доступны через Tab, Enter/Space меняют aria-pressed.'),
    S('slider', 'selection', 'Slider', 'Непрерывное значение с точным числовым откликом.', () => `<div class="stack lg"><iq-range label="Прозрачность поверхности" value="72" unit="%"></iq-range><iq-range label="Скругление" min="0" max="24" value="16" unit=" px"></iq-range></div>`, 'Нативный range с собственной дорожкой и thumb. Для задач, где нужно точное значение, рядом нужен числовой ввод.', 'Стрелки — шаг, Home/End — границы. Значение озвучивается нативно.'),
    S('date-picker', 'selection', 'Calendar / date picker', 'Календарь с клавиатурной сеткой и месяцами.', () => '<iq-calendar value="2026-09-18"></iq-calendar>', 'Даты демо зафиксированы в сентябре 2026, не выдаются за текущую дату. Поддерживаются min/max.', 'Стрелки — дни/недели; Home/End — неделя; PageUp/Down — месяцы; Enter — выбор.'),
    S('tabs', 'navigation', 'Tabs', 'Положение сохраняется при смене содержания.', () => ui_js_1.tabs([{ key: 'overview', label: 'Обзор', body: '<p class="muted" style="font-size:13px">Описание, цель и ожидаемый результат проекта.</p>' }, { key: 'history', label: 'История', body: '<div class="iq-inline">' + components_js_1.icon('clock', 16) + ' Сегодня / описание обновлено</div>' }, { key: 'files', label: 'Файлы', body: '<div class="iq-inline">' + components_js_1.icon('file', 16) + ' Brief.pdf-файл</div>' }], 'label="Сведения о проекте"'), 'Настоящие tablist / tab / tabpanel. Выбранная вкладка отличается от keyboard focus.', 'Стрелки, Home/End — переход между вкладками; Tab — в панель.'),
    S('breadcrumb', 'navigation', 'Breadcrumb', 'Место объекта в структуре.', () => `<nav class="iq-breadcrumb" aria-label="Путь"><a href="#overview">IQUIPAGE</a>${components_js_1.icon('chevron', 12)}<a href="#components/actions">Библиотека</a>${components_js_1.icon('chevron', 12)}<span aria-current="page">Навигация</span></nav>`, 'Текущий уровень — текст, а не фиктивная ссылка. Длинный путь должен переноситься.', 'Tab и Enter на ссылках.'),
    S('pagination', 'navigation', 'Pagination', 'Локальный просмотр страниц с явным состоянием.', () => `<div data-pagination><nav class="iq-pagination" aria-label="Страницы примера">${ui_js_1.ib('left', 'Предыдущая страница', 'ghost sm', 'data-page="prev"')} ${[1, 2, 3, 4, 5].map(n => `<button type="button" data-page="${n}" ${n === 1 ? 'aria-current="page"' : ''}>${n}</button>`).join('')} ${ui_js_1.ib('chevron', 'Следующая страница', 'ghost sm', 'data-page="next"')}</nav><p class="iq-helper" aria-live="polite">Страница 1 из 5</p></div>`, 'Демо переключает номер страницы и состояние. Подключение серверного списка — ответственность приложения.'),
    S('stepper', 'navigation', 'Stepper', 'Последовательность с возвращением к предыдущему шагу.', () => `<div data-stepper><ol class="iq-stepper"><li class="current"><span class="iq-step-index">1</span>Данные</li><li><span class="iq-step-index">2</span>Доступ</li><li><span class="iq-step-index">3</span>Готово</li></ol><p class="iq-helper" style="margin:24px 0" aria-live="polite">Шаг 1 из 3</p><div class="row">${ui_js_1.btn('Назад', 'secondary sm', 'left', 'data-step="-1"')}${ui_js_1.btn('Далее', 'primary sm', 'arrow', 'data-step="1"')}</div></div>`, 'Не пропускать обязательную валидацию в реальном мастере. Шаги демонстрационные.'),
    S('sidebar', 'navigation', 'Sidebar', 'Спокойная навигация с одним активным маршрутом.', () => `<nav class="iq-side-nav preview-nav" aria-label="Навигационный пример"><button type="button" class="active">${components_js_1.icon('grid', 17)}Обзор<span class="count">12</span></button><button type="button">${components_js_1.icon('checklist', 17)}Задачи<span class="count">24</span></button><button type="button">${components_js_1.icon('folder', 17)}Проекты<span class="count">04</span></button><button type="button">${components_js_1.icon('users', 17)}Команда</button></nav>`, 'В реальном приложении пункты — ссылки с URL. В этом изолированном примере кнопки меняют активный образец.'),
    S('command', 'navigation', 'Command palette', 'Быстрый переход без скрытой навигации.', () => `<div class="stack"><div class="iq-search-small" style="max-width:none">${components_js_1.icon('search', 17)}<span class="grow">Поиск по системе</span><kbd>⌘ K</kbd></div>${ui_js_1.btn('Открыть поиск', 'secondary', 'command', 'data-command')}</div>`, 'Командное меню дополняет обычную навигацию. Работает с разделами текущего прототипа.', '⌘/Ctrl K, ввод фильтра, ↓/↑ между результатами, Enter, Escape.'),
    S('appbar', 'navigation', 'App bar', 'Идентичность, текущий контекст, редкие глобальные действия.', () => `<div class="sample-appbar"><span class="row">${components_js_1.icon('stack', 19)}<strong>IQUIPAGE</strong></span><span class="muted" style="font-size:11px">Studio / Обзор</span><div class="row">${ui_js_1.ib('search', 'Поиск', 'ghost sm', 'data-command')}${ui_js_1.avatar('АК', 1)}</div></div>`, 'Не добавлять в шапку все настройки приложения. На узком экране вторичные действия сворачиваются.'),
    S('table', 'data', 'Data table', 'Сопоставимость, сортировка, сдержанные статусы.', () => `<div class="iq-table-wrap"><table class="iq-table" data-sortable><caption class="sr-only">Демонстрационные проекты</caption><thead><tr><th><button type="button" data-sort="0">Проект ${components_js_1.icon('sort', 12)}</button></th><th>Статус</th><th class="num"><button type="button" data-sort="2">Задачи ${components_js_1.icon('sort', 12)}</button></th></tr></thead><tbody><tr><td>Sprintique</td><td>${ui_js_1.badge('В работе', 'info')}</td><td class="num">24</td></tr><tr><td>IQUIPAGE Objects</td><td>${ui_js_1.badge('На проверке', 'warning')}</td><td class="num">12</td></tr><tr><td>IQUIPAGE Core</td><td>${ui_js_1.badge('Завершён', 'success')}</td><td class="num">36</td></tr></tbody></table></div>`, 'HTML table для табличных данных. В demo сортировка клиентская, без виртуализации. Длинные таблицы требуют отдельной стратегии.'),
    S('list', 'data', 'List item', 'Один объект, одна строка, вторичные сведения ниже.', () => `<div class="iq-list"><div class="iq-list-item"><span class="sample-icon">${components_js_1.icon('folder', 21)}</span><div class="grow"><b>Библиотека материалов</b><small>12 документов / обновлено сегодня</small></div>${ui_js_1.ib('chevron', 'Открыть библиотеку', 'ghost sm', 'data-go="components/files"')}</div><div class="iq-list-item"><span class="sample-icon">${components_js_1.icon('file', 21)}</span><div class="grow"><b>Принципы дизайна</b><small>Версия 02 / IQUIPAGE</small></div>${ui_js_1.ib('chevron', 'Открыть принципы', 'ghost sm', 'data-go="foundations"')}</div></div>`, 'Строка не должна иметь несколько конкурирующих зон перехода. Иконка подсказывает тип, подпись объясняет содержание.'),
    S('avatar', 'data', 'Avatar & group', 'Человек, команда, присутствие.', () => `<div class="stack lg"><div class="row">${ui_js_1.avatar('АК', 1, 'sm')}${ui_js_1.avatar('МЛ', 2)}${ui_js_1.avatar('ДС', 3, 'lg online')}${ui_js_1.avatar('АВ', 4, 'lg')}</div>${ui_js_1.avatars()}<p class="iq-helper">Инициалы демонстрационных участников, не фотографии реальных людей.</p></div>`, 'Не передавать присутствие одним цветом в рабочем сценарии. Группе нужна общая подпись, фото — осмысленный alt.'),
    S('badge', 'data', 'Badge & status', 'Цвет поддерживает смысл, но не заменяет подпись.', () => `<div class="row">${ui_js_1.badge('В работе', 'info')}${ui_js_1.badge('Готово', 'success')}${ui_js_1.badge('Требует решения', 'warning')}${ui_js_1.badge('Ошибка', 'danger')}${ui_js_1.badge('Черновик')}${ui_js_1.badge('Версия 02', 'outline', false)}</div>`, 'Короткие слова, спокойная заливка. Не использовать все статусы как крупные светящиеся карточки.'),
    S('metric', 'data', 'Metric', 'Число как информация, не декоративный счётчик.', () => `<div class="iq-metric"><div class="metric-label"><span>Закрыто задач</span>${components_js_1.icon('chart', 17)}</div><div class="metric-value">128<span style="font-size:17px;color:var(--iq-muted);margin-left:7px">/ 160</span></div><div class="metric-change"><span class="positive">+18</span> к прошлому периоду</div><div style="margin-top:20px">${ui_js_1.sparkline()}</div></div>`, 'Демонстрационные числа явно помечены. Точность и период принадлежат данным приложения, не дизайн-системе.'),
    S('chart', 'data', 'Chart', 'График с дублирующим текстовым рядом.', () => ui_js_1.chart(), 'График построен SVG без внешнего chart-kit. В комплекте только этот простой столбчатый вид, не универсальная chart-библиотека.', 'Сам график имеет текстовую альтернативу. Интерактивные фильтры реализуются отдельными контролами.'),
    S('timeline', 'data', 'Timeline', 'Происхождение результата читается по порядку.', () => `<ol class="iq-timeline"><li class="done"><b>Гипотеза принята</b><p>03 сентября / Александр Ким</p></li><li class="done"><b>Макет проверен</b><p>04 сентября / Мария Лебедева</p></li><li><b>Подготовить реализацию</b><p>Следующий шаг</p></li></ol>`, 'События должны различать человека, агента и системное действие. Не имитировать автоматически подтверждённый результат.'),
    S('tree', 'data', 'Disclosure tree', 'Иерархия через раскрытие, без сложного редактора.', () => `<div class="iq-tree"><details open><summary>${components_js_1.icon('chevron', 12)}${components_js_1.icon('folder', 17)}IQUIPAGE</summary><div><details open><summary>${components_js_1.icon('chevron', 12)}${components_js_1.icon('folder', 17)}Foundations</summary><div><span class="iq-tree-file">${components_js_1.icon('file', 16)}colors.json</span><span class="iq-tree-file">${components_js_1.icon('file', 16)}typography.json</span></div></details><details><summary>${components_js_1.icon('chevron', 12)}${components_js_1.icon('folder', 17)}Components</summary><div><span class="iq-tree-file">${components_js_1.icon('file', 16)}button.ts</span><span class="iq-tree-file">${components_js_1.icon('file', 16)}select.ts</span></div></details></div></details></div>`, 'Это disclosure hierarchy на details, не ARIA treeview с выбором/drag-and-drop. Контракт не обещает несуществующие операции.', 'Tab между summary. Enter/Space — раскрытие.'),
    S('alert', 'feedback', 'Alert', 'Смысловое сообщение в месте проблемы.', () => `<div class="stack sm">${ui_js_1.alert('Изменения сохранены', 'Можно продолжить работу.', 'success')}${ui_js_1.alert('Нужно ваше решение', 'Уточните дату перед публикацией.', 'warning')}${ui_js_1.alert('Не удалось подключиться', 'Черновик сохранён локально. Повторите позже.', 'danger')}${ui_js_1.alert('Доступна новая версия', 'Посмотрите изменения перед обновлением.')}</div>`, 'Статические примеры не объявляются assertive. Для новых ошибок приложения выбирайте подходящий live-region.'),
    S('toast', 'feedback', 'Toast', 'Короткий результат с возможностью отмены.', () => `<div class="row">${ui_js_1.btn('Сохранено', 'secondary sm', 'checkCircle', 'data-toast="success"')}${ui_js_1.btn('Информация', 'secondary sm', 'info', 'data-toast="info"')}${ui_js_1.btn('Предупреждение', 'secondary sm', 'warning', 'data-toast="warning"')}${ui_js_1.btn('Ошибка', 'secondary sm', 'xCircle', 'data-toast="danger"')}</div>`, 'Таймер приостанавливается при hover и фокусе. Важная ошибка дополнительно остаётся рядом с действием.', 'Tab к отмене и закрытию. Фокус не перехватывается при появлении.'),
    S('progress', 'feedback', 'Progress', 'Линейное и кольцевое представление одного значения.', () => `<div class="stack" data-progress-demo><div class="row between"><span class="muted" style="font-size:12px">Демонстрация прогресса</span><b class="demo-progress-value" style="font-size:12px">68%</b></div>${ui_js_1.progress(68, 'Демонстрация прогресса', 'optical')}<div class="row between">${ui_js_1.ring(68)}${ui_js_1.btn('Повторить', 'secondary sm', 'refresh', 'data-progress-play')}</div></div>`, 'Не показывать выдуманные проценты загрузки в production. Демо явно запускает визуальную симуляцию.'),
    S('skeleton', 'feedback', 'Skeleton', 'Контур будущего содержания без декоративного мигания.', () => `<div class="stack" aria-label="Визуальный образец загрузки"><div class="row"><div class="iq-skeleton circle" style="width:40px;height:40px"></div><div class="grow stack sm"><div class="iq-skeleton" style="width:55%;height:12px"></div><div class="iq-skeleton" style="width:35%;height:9px"></div></div></div><div class="iq-skeleton" style="height:90px;border-radius:10px"></div><div class="iq-skeleton" style="width:72%;height:10px"></div></div>`, 'При reduced motion перелив отключён. В реальной загрузке aria-busy принадлежит контейнеру, не каждой полоске.'),
    S('empty-state', 'feedback', 'Empty state', 'Понятная причина пустоты и следующий шаг.', () => ui_js_1.empty('Задач пока нет', 'Создайте задачу. Она появится в демонстрационном рабочем пространстве.'), 'Различайте отсутствие данных, отсутствие результатов поиска и ошибку загрузки.'),
    S('inline-message', 'feedback', 'Inline message', 'Небольшое сообщение без отдельного контейнера.', () => `<div class="stack sm"><div class="iq-inline success">${components_js_1.icon('checkCircle', 16)}Адрес доступен</div><div class="iq-inline danger">${components_js_1.icon('xCircle', 16)}Заполните название проекта</div><div class="iq-inline">${components_js_1.icon('lock', 16)}Видно только участникам</div></div>`, 'Подсказка остаётся рядом с полем. aria-describedby связывает её с контролом.'),
    S('banner', 'feedback', 'Banner', 'Уведомление уровня страницы с ясным действием.', () => `<div class="iq-banner">${components_js_1.icon('info', 19)}<p>Это локальный интерактивный макет.</p>${ui_js_1.btn('О системе', 'ghost sm', 'arrow', 'data-go="foundations"')}</div>`, 'Не перекрывает основной контент. Для постоянной системной проблемы нужен устойчивый статус.'),
    S('dialog', 'overlays', 'Dialog', 'Отдельная задача с возвратом в исходный контекст.', () => `<div class="overlay-preview"><div class="mini-dialog"><span class="mini-line"></span><span class="mini-line short"></span><div class="mini-actions"><span></span><span></span></div></div></div>${ui_js_1.btn('Открыть диалог', 'secondary', 'expand', 'data-dialog="demo-dialog"')}`, 'Нативный dialog: top layer, modal background, focus trap. Собственные geometry, backdrop, вход и действия.', 'Tab/Shift Tab остаются внутри. Escape закрывает. После закрытия фокус возвращается.'),
    S('drawer', 'overlays', 'Drawer', 'Деталь объекта, не потерянный список.', () => `<div class="overlay-preview"><div class="mini-drawer"><span class="mini-line"></span><span class="mini-line short"></span><span class="mini-line"></span></div></div>${ui_js_1.btn('Открыть панель', 'secondary', 'arrow', 'data-dialog="demo-drawer"')}`, 'На широком экране панель справа, на узком почти во всю ширину. Рабочая задача использует тот же компонент.', 'Нативная модальность. Escape и возвращение фокуса.'),
    S('dropdown-menu', 'overlays', 'Dropdown menu', 'Действия собраны в собственном меню.', () => ui_js_1.menu(ui_js_1.btn('Действия с проектом', 'secondary', 'down'), [{ label: 'Копировать название', glyph: 'copy', action: 'copy-name', shortcut: '⌘ C' }, { label: 'Скачать токены', glyph: 'download', action: 'export-tokens' }, { label: 'Открыть рабочий пример', glyph: 'upRight', action: 'workspace' }, { label: 'Удалить пример', glyph: 'trash', action: 'confirm', danger: true }]), 'Меню предназначено для действий, не выбора значения формы. Для значения используйте Select.', '↑/↓, Home/End, Escape. Tab закрывает меню.'),
    S('popover', 'overlays', 'Context popover', 'Небольшой выбор рядом с источником.', () => `<div class="popover-example"><div class="row"><span class="muted" style="font-size:12px">Ответственный</span>${ui_js_1.select('Ответственный', [{ value: 'alex', label: 'Александр Ким', icon: 'user' }, { value: 'maria', label: 'Мария Лебедева', icon: 'user' }, { value: 'none', label: 'Не назначен', icon: 'minus' }], 'class="compact-select"')}</div><p class="iq-helper">Выбор открывается около триггера, а не в центре экрана.</p></div>`, 'В этой поставке anchored popover реализован через select и menu. Универсальный rich-content popover не заявлен.'),
    S('tooltip', 'overlays', 'Tooltip', 'Уточнение, которое не прячет необходимый смысл.', () => `<div class="row"><iq-tooltip text="Скопировать в буфер">${ui_js_1.ib('copy', 'Копировать', 'secondary', 'data-copy="IQUIPAGE"')}</iq-tooltip><iq-tooltip text="История изменений">${ui_js_1.ib('clock', 'История изменений', 'secondary')}</iq-tooltip><iq-tooltip text="Доступно только участникам">${ui_js_1.ib('lock', 'Ограниченный доступ', 'secondary')}</iq-tooltip></div><p class="iq-helper">Наведите указатель или перейдите Tab.</p>`, 'Критичная информация не должна существовать только в tooltip. aria-describedby связывает подсказку с контролом.', 'Появляется при focus/hover. Escape скрывает.'),
    S('accordion', 'overlays', 'Accordion', 'Дополнительные сведения без потери структуры.', () => `<details class="iq-accordion" open><summary>Из чего состоит система? ${components_js_1.icon('plus', 16)}</summary><div>Токены, стили, интерактивные контролы, примеры, контракты и проверочные сценарии.</div></details><details class="iq-accordion"><summary>Что доступно без сети? ${components_js_1.icon('plus', 16)}</summary><div>Вся логика макета. Внешний шрифт при отсутствии сети заменяется системным.</div></details><details class="iq-accordion"><summary>Есть ли сервер? ${components_js_1.icon('plus', 16)}</summary><div>Нет. Сохранение работает локально, а серверные операции должны быть подключены в приложении.</div></details>`, 'Нативные details/summary, собственная типографика и раскрытие. Заголовок остаётся полностью видимым.', 'Tab и Enter/Space.'),
    S('dropzone', 'files', 'Dropzone', 'Собственная сцена выбора файлов и drag-and-drop.', () => '<iq-upload></iq-upload>', 'До 10 файлов, до 10 МБ на файл; расширения проверяются в клиенте. Проверка безопасности MIME и содержимого нужна на сервере.', 'Tab к выбору файлов, системный диалог. Drag-and-drop — дополнительный путь.'),
    S('file-item', 'files', 'File item', 'Имя, размер и достоверный статус.', () => `<div class="iq-file-item"><span class="iq-file-icon">${components_js_1.icon('file', 21)}</span><div><b>Interface-guidelines.pdf</b><small>2,4 МБнстрационный образец</small></div>${ui_js_1.badge('Образец', 'outline', false)}</div><div class="iq-file-item"><span class="iq-file-icon">${components_js_1.icon('file', 21)}</span><div><b>Очень-длинное-название-документа-с-описанием-результата.zip</b><small>8,1 МБнстрационный образец</small></div>${ui_js_1.badge('Образец', 'outline', false)}</div>`, 'Длинное имя визуально обрезается, полный текст остаётся в DOM. Никаких фиктивных кнопок скачивания несуществующего файла.'),
    S('upload-feedback', 'files', 'File validation', 'Отказ объясняется до отправки.', () => `<div class="stack">${ui_js_1.alert('Файл больше 10 МБ', 'Уменьшите размер или разделите файл.', 'danger')}${ui_js_1.alert('Формат не поддерживается', 'Выберите PDF, PNG, JPG, SVG, ZIP или TXT.', 'danger')}<p class="iq-helper">Эти ошибки воспроизводятся и в живом Dropzone.</p></div>`, 'Клиентская проверка помогает пользователю, но не заменяет серверную валидацию и ограничения хранения.'),
    S('card', 'layout', 'Card', 'Контейнер появляется только у самостоятельного объекта.', () => `<div class="iq-card"><div class="iq-card-head"><h3>Следующий релиз</h3>${ui_js_1.badge('В работе', 'info')}</div><p class="muted" style="font-size:12px">Единый контекст, понятная цель и доказательства готовности.</p><div class="iq-card-foot">${ui_js_1.avatars()}<span>18 сентября</span></div></div>`, 'Карточка не должна многократно вкладываться сама в себя. Статус и действия не конкурируют с названием.'),
    S('signature-surface', 'layout', 'Signature surface', 'Свет принадлежит смысловой поверхности, а не каждому контролу.', () => `<div class="signature material-sample"><div class="row between"><span class="mono">RELEASE / 02</span>${components_js_1.icon('upRight', 18)}</div><h3>Следующий шаг<br>уже ясен.</h3><p>От замысла — к проверенному результату.</p>${ui_js_1.btn('Открыть пример', 'white pill sm', 'arrow', 'data-go="workspace"')}</div>`, 'Принцип света из Revenue is accelerating применён к одному акцентному материалу. Семантические статусы остаются спокойными.'),
    S('frost-surface', 'layout', 'Frosted surface', 'Контекстная прозрачность с непрозрачным текстовым слоем.', () => `<div class="frost-stage"><div class="frost"><div class="row between"><span class="sample-icon">${components_js_1.icon('checkCircle', 20)}</span>${ui_js_1.badge('Локально', 'outline', false)}</div><h3>Контекст сохранён.</h3><p>Можно вернуться к работе с того же места.</p></div></div>`, 'Фоновое размытие — необязательный эффект. Компонент должен оставаться понятным без backdrop-filter.'),
    S('layout-primitives', 'layout', 'Grid / Stack / Divider', 'Ритм и выравнивание вместо случайных отступов.', () => `<div class="layout-demo"><div class="layout-span">12 колонок</div><span>4</span><span>4</span><span>4</span><span style="grid-column:span 2">8</span><span>4</span></div><p class="iq-helper">Шаг 4 px / интервалы 8 / 12 / 16 / 24 / 32 / 48</p>`, 'Стандартные utility-классы .grid-2, .grid-3, .stack, .row, .divider. Для конкретного экрана правила задаются явно, не генератором произвольных utility.'),
];
exports.stories = stories;
function storyCard(s) { return `<article class="story-card" id="story-${s.id}" data-component="${s.id}"><header class="story-head"><div><span class="story-kicker">${s.category.toUpperCase()} / ${s.id}</span><h2>${s.title}</h2><p>${s.description}</p></div><button class="story-code" type="button" data-story-code="${s.id}" aria-label="Код ${s.title}">${components_js_1.icon('code', 17)}</button></header><div class="story-body">${s.demo()}</div><details class="story-spec"><summary>Поведение и использование ${components_js_1.icon('plus', 14)}</summary><div><p>${s.usage}</p><p><b>Клавиатура.</b> ${s.keyboard}</p></div></details></article>`; }

