'use strict';
const components_js_1=require('./components.js');
function sparkline() { return `<svg class="iq-sparkline" viewBox="0 0 330 68" fill="none" role="img" aria-label="Иллюстративная динамика прогресса: рост"><path d="M2 61C28 61 33 48 51 51S78 33 102 37 141 42 161 24 193 35 215 19 236 25 259 12 293 19 327 3" stroke="currentColor" stroke-width="2"/><path d="M2 61C28 61 33 48 51 51S78 33 102 37 141 42 161 24 193 35 215 19 236 25 259 12 293 19 327 3V68H2Z" fill="currentColor" opacity=".07"/><circle cx="327" cy="3" r="4" fill="currentColor" stroke="var(--iq-raised)" stroke-width="2"/></svg>`; }
function chart() {
 const values = [31,49,41,70,60,81], months = ['Апр','Май','Июн','Июл','Авг','Сен'];
 return `<figure class="iq-chart-demo"><svg class="iq-chart" viewBox="0 0 720 230" role="img" aria-label="Количество задач по месяцам: апрель 31, май 49, июнь 41, июль 70, август 60, сентябрь 81"><g class="iq-chart-grid">${[0,25,50,75,100].map(n=>`<path d="M36 ${210-n*1.9}H716"/>`).join('')}</g>${[0,25,50,75,100].map(n=>`<text x="2" y="${214-n*1.9}" class="chart-axis-label">${n}</text>`).join('')}${values.map((n,i)=>`<rect x="${66+i*111}" y="${210-n*1.9}" width="52" height="${n*1.9}" rx="5" fill="currentColor" opacity="${i===5?1:.28+i*.1}"/>`).join('')}</svg><div class="chart-month-labels" aria-hidden="true">${months.map(m=>`<span>${m}</span>`).join('')}</div><figcaption class="iq-helper chart-caption">Пример за апрель — сентябрь: 31, 49, 41, 70, 60, 81 задача</figcaption></figure>`;
}

exports.install=()=>{const U=require('./ui.js');Object.assign(U,{sparkline,chart,projectOptions:[{ value: 'sprintique', label: 'Sprintique', description: 'Рабочее пространство команды', icon: 'bolt' }, { value: 'objects', label: 'IQUIPAGE Objects', description: 'Предметы и сервис', icon: 'box' }, { value: 'core', label: 'IQUIPAGE Core', description: 'Система и инфраструктура', icon: 'stack' }]});require('./structured.js').configureTreeDefaults({nodes:[{ id: 'work', label: 'Рабочее пространство', children: [{ id: 'design', label: 'Дизайн-система', children: [{ id: 'principles', label: 'Принципы и тон общения' }, { id: 'components', label: 'Компоненты интерфейса' }, { id: 'motion', label: 'Движение и состояния' }] }, { id: 'release', label: 'Выпуск 2.4', children: [{ id: 'brief', label: 'Описание релиза' }, { id: 'materials', label: 'Рабочие материалы' }] }, { id: 'objects', label: 'Цифровые паспорта', children: [{ id: 'module', label: 'MODULE 01' }] }] }],expanded:['work','design','release'],selected:['components'],focus:'work',current:'components'});require('./side-navigation.js').configureNavigationDefaults({sections:[
 {label:'Работа',items:[{id:'inbox',label:'Входящие',icon:'bell',count:3,href:'#workspace/tasks'},{id:'tasks',label:'Мои задачи',icon:'checklist',count:6,href:'#workspace/tasks'},{id:'plan',label:'План',icon:'calendar',href:'#workspace/plan'}]},
 {label:'Проекты',items:[{id:'release',label:'Выпуск 2.4',icon:'folder',href:'#workspace/board',children:[{id:'release-board',label:'Доска',icon:'board',href:'#workspace/board'},{id:'release-files',label:'Материалы',icon:'file',href:'#components/file-item'}]},{id:'system',label:'Дизайн-система',icon:'stack',href:'#components/button'},{id:'objects',label:'Коллекция',icon:'box',href:'#objects'}]}
],opened:['release'],workspace:'IQUIPAGE Studio',person:'Александр',initials:'АК',active:'tasks'});components_js_1.configureTagDefaults('Дизайн,Разработка');};
