'use strict';
/** Pure scene operations. No DOM, rendering, network or sample data. */
const TYPES=['sticky','text','shape','frame','task','image','drawing'];
const COLORS=['sand','lavender','mint','sky','rose','neutral'];
const SHAPES=require('./whiteboard-shapes.js').SHAPES;
const LIMIT=600, EDGE_LIMIT=1600, COORD_LIMIT=100000;
const clone=v=>structuredClone(v);
const bounded=(n,lo,hi)=>Math.max(lo,Math.min(hi,n));
function finite(n,label,lo=-COORD_LIMIT,hi=COORD_LIMIT){if(!Number.isFinite(n)||n<lo||n>hi)throw new TypeError(`${label}: значение вне допустимого диапазона`);return n}
function id(v){if(typeof v!=='string'||!v||v.length>100||!/^[-\w:.]+$/.test(v))throw new TypeError('Некорректный идентификатор');return v}
function str(v,max=10000){if(v==null)return '';if(typeof v!=='string'||v.length>max)throw new TypeError('Некорректный текст или превышен лимит');return v}
function safeImage(v){if(!v)return '';if(typeof v!=='string'||v.length>8000000||!/^data:image\/(png|jpeg|webp);base64,[a-zA-Z0-9+/=]+$/.test(v))throw new TypeError('Изображение: нужен локальный PNG, JPEG или WebP');return v}
function validateBoard(value){
 if(!value||!Array.isArray(value.objects)||!Array.isArray(value.connections))throw new TypeError('Нужны objects и connections');
 if(value.objects.length>LIMIT||value.connections.length>EDGE_LIMIT)throw new RangeError(`Лимит доски: ${LIMIT} объектов, ${EDGE_LIMIT} связей`);
 const seen=new Set();
 const objects=value.objects.map(v=>{id(v.id);if(seen.has(v.id))throw new TypeError('Повторный id');seen.add(v.id);if(!TYPES.includes(v.type))throw new TypeError('Неизвестный тип объекта');
  const o={id:v.id,type:v.type,x:finite(v.x,'x'),y:finite(v.y,'y'),width:finite(v.width,'width',40,10000),height:finite(v.height,'height',32,10000),text:str(v.text),color:COLORS.includes(v.color)?v.color:'neutral',locked:!!v.locked};
  if(v.parentId)o.parentId=id(v.parentId);if(v.author)o.author=str(v.author,100);if(v.shape)o.shape=SHAPES.includes(v.shape)?v.shape:'rectangle';
  o.align=['left','center','right'].includes(v.align)?v.align:(v.type==='shape'?'center':'left');
  o.valign=['top','middle','bottom'].includes(v.valign)?v.valign:(v.type==='shape'?'middle':'top');
  o.autoHeight=v.autoHeight!==false;o.minHeight=Number.isFinite(v.minHeight)?finite(v.minHeight,'minHeight',32,4000):Math.min(v.height,v.type==='shape'?120:v.type==='text'?64:160);
  if(v.type==='frame'){if(v.layout==='column')o.layout='column';if(v.headerHeight!=null)o.headerHeight=finite(v.headerHeight,'headerHeight',56,4000);}if(v.type==='image'&&v.captionHeight!=null)o.captionHeight=finite(v.captionHeight,'captionHeight',24,4000);
  if(v.type==='image')o.src=safeImage(v.src);
  if(v.type==='task'){o.done=!!v.done;if(v.owner)o.owner=str(v.owner,100);if(v.externalTaskId)o.externalTaskId=id(v.externalTaskId)}
  if(v.type==='drawing'){if(!Array.isArray(v.points)||v.points.length<2||v.points.length>4000)throw new TypeError('Рисунку нужны от 2 до 4000 точек');o.points=v.points.map(p=>{if(!Array.isArray(p)||p.length!==2)throw new TypeError('Некорректная точка');return [finite(p[0],'point x',0,10000),finite(p[1],'point y',0,10000)]});}
  return o;
 });
 const by=new Map(objects.map(o=>[o.id,o]));
 for(const o of objects){let cur=o,parents=new Set([o.id]);while(cur.parentId){const p=by.get(cur.parentId);if(!p||p.type!=='frame'||parents.has(p.id))throw new TypeError('Некорректная рамка или цикл вложенности');parents.add(p.id);cur=p;}}
 const edgeIds=new Set();
 const connections=value.connections.map(e=>{id(e.id);if(seen.has(e.id)||edgeIds.has(e.id))throw new TypeError('Повторный id связи');edgeIds.add(e.id);if(!by.has(e.from)||!by.has(e.to)||e.from===e.to)throw new TypeError('Недопустимые концы связи');return {id:e.id,from:e.from,to:e.to,label:str(e.label,240),style:['curve','straight','elbow'].includes(e.style)?e.style:'curve',arrow:e.arrow!==false,arrowStart:!!e.arrowStart,fromPort:require('./whiteboard-routing.js').SIDES.includes(e.fromPort)?e.fromPort:'auto',toPort:require('./whiteboard-routing.js').SIDES.includes(e.toPort)?e.toPort:'auto',dashed:!!e.dashed,color:['neutral','accent','success','warning','error'].includes(e.color)?e.color:'neutral',labelPosition:Number.isFinite(e.labelPosition)?bounded(e.labelPosition,.15,.85):.5,bend:Number.isFinite(e.bend)?bounded(e.bend,-500,500):0};});
 return {schema:'iquipage.whiteboard/1',revision:Number.isInteger(value.revision)&&value.revision>=0?value.revision:0,title:str(value.title||'Доска идей',160),objects,connections};
}
const blank=()=>({schema:'iquipage.whiteboard/1',revision:0,title:'Доска идей',objects:[],connections:[]});
function newId(prefix='o'){return prefix+'-'+(globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`)}
function bounds(objects){if(!objects.length)return {x:0,y:0,width:0,height:0};const x=Math.min(...objects.map(o=>o.x)),y=Math.min(...objects.map(o=>o.y));return{x,y,width:Math.max(...objects.map(o=>o.x+o.width))-x,height:Math.max(...objects.map(o=>o.y+o.height))-y}}
function family(scene,ids){const all=new Set(ids);let changed=true;while(changed){changed=false;for(const o of scene.objects)if(o.parentId&&all.has(o.parentId)&&!all.has(o.id)){all.add(o.id);changed=true;}}return all}
function isLocked(scene,object){let n=object,i=0;while(n&&i++<scene.objects.length+1){if(n.locked)return true;n=scene.objects.find(o=>o.id===n.parentId)}return false}
function mutableFamily(scene,ids){const result=new Set();for(const id of ids){const branch=family(scene,[id]);if([...branch].some(k=>{const o=scene.objects.find(n=>n.id===k);return o&&isLocked(scene,o)}))continue;for(const key of branch)if(scene.objects.some(o=>o.id===key))result.add(key)}return result}
function translate(scene,ids,dx,dy){finite(dx,'dx');finite(dy,'dy');const next=clone(scene),set=mutableFamily(scene,ids);for(const o of next.objects)if(set.has(o.id)){o.x=bounded(o.x+dx,-COORD_LIMIT,COORD_LIMIT);o.y=bounded(o.y+dy,-COORD_LIMIT,COORD_LIMIT);}return next}
function assignFrames(scene,ids){const next=clone(scene),set=new Set(ids);for(const o of next.objects){if(!set.has(o.id)||o.type==='frame'||isLocked(scene,o))continue;const candidates=next.objects.filter(f=>f.type==='frame'&&!f.locked&&o.x+o.width/2>f.x&&o.x+o.width/2<f.x+f.width&&o.y+o.height/2>f.y+(f.headerHeight||56)&&o.y+o.height/2<f.y+f.height).sort((a,b)=>a.width*a.height-b.width*b.height);if(candidates[0])o.parentId=candidates[0].id;else delete o.parentId;}return next}
function duplicate(scene,ids,dx=32,dy=32){const set=family(scene,ids),map=new Map([...set].map(k=>[k,newId()])),items=scene.objects.filter(o=>set.has(o.id)).map(o=>({...clone(o),id:map.get(o.id),x:bounded(o.x+dx,-COORD_LIMIT,COORD_LIMIT),y:bounded(o.y+dy,-COORD_LIMIT,COORD_LIMIT),parentId:map.get(o.parentId)||o.parentId,locked:false}));const connections=scene.connections.filter(e=>set.has(e.from)&&set.has(e.to)).map(e=>({...e,id:newId('e'),from:map.get(e.from),to:map.get(e.to)}));return{value:validateBoard({...scene,objects:[...scene.objects,...items],connections:[...scene.connections,...connections]}),ids:ids.map(k=>map.get(k)).filter(Boolean)}}
function remove(scene,ids){const set=mutableFamily(scene,ids),next=clone(scene);next.objects=next.objects.filter(o=>!set.has(o.id));next.connections=next.connections.filter(e=>!set.has(e.from)&&!set.has(e.to)&&!ids.includes(e.id));return next}
function enclose(scene,ids,title='Новая группа'){const selected=scene.objects.filter(o=>ids.includes(o.id)&&!isLocked(scene,o));if(!selected.length)return{value:scene,id:null};const b=bounds(selected),key=newId('frame'),next=clone(scene);next.objects.unshift({id:key,type:'frame',text:title,x:b.x-28,y:b.y-68,width:b.width+56,height:b.height+96,color:'neutral',locked:false});next.objects.forEach(o=>{if(ids.includes(o.id)&&!selected.some(p=>p.id!==o.id&&family(scene,[p.id]).has(o.id)))o.parentId=key});return{value:validateBoard(next),id:key}}
function tidy(scene,ids,columns){const selected=scene.objects.filter(o=>ids.includes(o.id)&&o.type!=='frame'&&!isLocked(scene,o));if(!selected.length)return clone(scene);const b=bounds(selected),next=clone(scene),cols=bounded(columns||Math.ceil(Math.sqrt(selected.length)),1,selected.length),cellW=Math.max(...selected.map(o=>o.width)),cellH=Math.max(...selected.map(o=>o.height));selected.sort((a,b)=>Math.round(a.y/50)-Math.round(b.y/50)||a.x-b.x).forEach((o,i)=>{const n=next.objects.find(n=>n.id===o.id);n.x=b.x+(i%cols)*(cellW+24);n.y=b.y+Math.floor(i/cols)*(cellH+24)});return assignFrames(next,selected.map(o=>o.id))}
function align(scene,ids,axis='left'){const chosen=scene.objects.filter(o=>ids.includes(o.id)&&o.type!=='frame'&&!isLocked(scene,o));const b=bounds(chosen);const next=clone(scene);for(const o of next.objects)if(chosen.some(n=>n.id===o.id)){if(axis==='left')o.x=b.x;if(axis==='top')o.y=b.y;if(axis==='center')o.x=b.x+(b.width-o.width)/2}return next}
function connectorGeometry(a,b,edge='curve'){return require('./whiteboard-routing.js').route(a,b,edge)}
function fitTargets(scene,ids){const chosen=ids?.length?family(scene,ids):new Set(scene.objects.map(o=>o.id));const targets=scene.objects.filter(o=>chosen.has(o.id)).map(o=>({...o}));const byId=new Map(scene.objects.map(o=>[o.id,o]));for(const e of scene.connections){if(!chosen.has(e.from)||!chosen.has(e.to))continue;const g=require('./whiteboard-routing.js').route(byId.get(e.from),byId.get(e.to),e,scene.objects);const half=Math.max(12,Array.from(e.label||'').length*3.8);targets.push({x:g.x-half,y:g.y-16,width:half*2,height:32});for(const p of g.points||[])targets.push({x:p.x,y:p.y,width:1,height:1});}return targets}
function fitViewport(objects,width,height,padding=64){if(!objects.length)return {x:padding,y:padding,zoom:1};const b=bounds(objects),zoom=bounded(Math.min((width-padding*2)/Math.max(1,b.width),(height-padding*2)/Math.max(1,b.height),1),.2,2.5);return{x:(width-b.width*zoom)/2-b.x*zoom,y:(height-b.height*zoom)/2-b.y*zoom,zoom}}
function zoomAt(v,zoom,x,y){zoom=bounded(zoom,.2,2.5);return{x:x-(x-v.x)/v.zoom*zoom,y:y-(y-v.y)/v.zoom*zoom,zoom}}
function createObject(type,x,y,text='',color='sand'){const sizes={sticky:[208,164],text:[360,64],shape:[232,96],frame:[520,400],task:[248,144],image:[320,240],drawing:[80,80]};if(!TYPES.includes(type))throw new TypeError('Неизвестный тип');const[w,h]=sizes[type];return{id:newId(type),type,x,y,width:w,height:h,text,color:['sticky'].includes(type)?color:'neutral',shape:type==='shape'?'rectangle':undefined,locked:false}}
function bulkObjects(text,x,y,color='sand'){const lines=String(text).split(/\r?\n|\t/).map(s=>s.trim()).filter(Boolean);if(lines.length>100)throw new RangeError('Вставляйте не больше 100 заметок за раз');return lines.map((s,i)=>createObject('sticky',x+(i%4)*232,y+Math.floor(i/4)*188,s.slice(0,10000),color))}
function exportSelection(scene,ids){const set=family(scene,ids);return{...clone(scene),objects:scene.objects.filter(o=>set.has(o.id)).map(o=>{const n=clone(o);if(!set.has(n.parentId))delete n.parentId;return n}),connections:scene.connections.filter(e=>set.has(e.from)&&set.has(e.to))}}
function insertScene(scene,incoming,x,y){incoming=validateBoard(incoming);if(!incoming.objects.length)return{value:scene,ids:[]};const b=bounds(incoming.objects);const map=new Map(incoming.objects.map(o=>[o.id,newId(o.type)]));const objects=incoming.objects.map(o=>({...o,id:map.get(o.id),x:bounded(o.x-b.x+x,-COORD_LIMIT,COORD_LIMIT),y:bounded(o.y-b.y+y,-COORD_LIMIT,COORD_LIMIT),parentId:map.get(o.parentId)}));return{value:validateBoard({...scene,objects:[...scene.objects,...objects],connections:[...scene.connections,...incoming.connections.map(e=>({...e,id:newId('e'),from:map.get(e.from),to:map.get(e.to)}))]}),ids:objects.filter(o=>!o.parentId).map(o=>o.id)}}
Object.assign(exports,{TYPES,COLORS,SHAPES,LIMIT,EDGE_LIMIT,clone,bounded,validateBoard,blank,newId,bounds,family,isLocked,mutableFamily,translate,assignFrames,duplicate,remove,enclose,tidy,align,connectorGeometry,fitTargets,fitViewport,zoomAt,createObject,bulkObjects,exportSelection,insertScene});

