import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {referenceServer} from './server-fixture.mjs';
import {createTask} from '../src/tasks.js';
const cleanup=[],checks=[],errors=[],api=await referenceServer({after:fn=>cleanup.push(fn)}),projectId='ux-v3',out='output/playwright/ux-v3';
await mkdir(out,{recursive:true});
for(const [i,name] of ['Дизайн','Исследование','Web','Android','iOS','Доступность','Аналитика','Документация','Интерфейс'].entries())await api.put('tags',{id:'tag-'+i,projectId,name,tone:'neutral',revision:0});
await api.put('tasks',{...createTask({projectId,title:'Новый онбординг',description:'## Результат\n\nПонятный первый шаг.'}),id:'base',displayId:'SPR-241',tagIds:['tag-0','tag-1','tag-2','tag-3','tag-4','tag-5','tag-6','tag-7','tag-8'],checklists:[{id:'c1',title:'Критерии',items:[{id:'i1',text:'Проверить клавиатуру',done:false}]}]});
await api.put('tasks',{...createTask({projectId,title:'Минимальная задача'}),id:'minimal',displayId:'SPR-242'});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
const panel=()=>page.locator('.task-edit-dialog dialog[open]'),modal=()=>page.locator('dialog[open]').last();
const gone=()=>page.locator('.task-edit-dialog').waitFor({state:'detached'});
const open=async()=>{await page.locator('[data-drag-id=base]').click({position:{x:15,y:48}});await panel().getByLabel('Название',{exact:true}).waitFor();};
const close=async()=>{await panel().locator('.iq-dialog-head [data-close]').click();await gone();await page.waitForURL(/#tasks$/);};
const mark=s=>{checks.push(s);console.log('PASS',s);};
const shot=async name=>{await page.waitForFunction(()=>document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).every(a=>a.playState!=='running'));await page.screenshot({path:out+'/'+name+'.png'});};
let failure;
try{
 await page.goto(api.base+'/?project='+projectId+'#tasks');await page.locator('[data-drag-id=base]').waitFor();
 const centers=await page.locator('.platform-brand,.platform-context>iq-menu>button,.platform-navigation>a,.platform-search-trigger').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect();return r.y+r.height/2;}));
 assert.ok(Math.max(...centers)-Math.min(...centers)<2,JSON.stringify(centers));
 assert.equal(await page.locator('.platform-nav-row,[data-refresh-tasks],.iq-drag-handle,[data-board-help]').count(),0);
 assert.equal(await page.locator('[data-drag-id=minimal]').evaluate(el=>getComputedStyle(el).userSelect),'none');
 const minimalBox=await page.locator('[data-drag-id=minimal]').boundingBox(),emptyBox=await page.locator('.board-empty-slot:visible').first().boundingBox();assert.equal(Math.round(minimalBox.height),Math.round(emptyBox.height));
 assert.ok(await page.locator('[data-drag-id=base] [data-tags-overflow]').count());
 mark('One aligned header; non-selectable compact cards and tag overflow');
 await open();await page.waitForURL(/#\/task\/SPR-241$/);
 assert.match(await panel().locator('.iq-dialog-head').innerText(),/SPR-241/);
 await context.grantPermissions(['clipboard-read','clipboard-write']);await panel().locator('[data-copy-task-link]').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),page.url());
 await panel().locator('[data-task-fullscreen]').click();assert.equal(await page.locator('.task-edit-dialog').getAttribute('data-fullscreen'),'true');await panel().locator('[data-task-fullscreen]').click();
 assert.equal(await panel().locator('[data-checklists],[data-choose-tags],[data-reload-threads],[data-edit-description],[data-description] iq-markdown-viewer').count(),0);
 const geometry=await panel().evaluate(el=>{const rect=s=>el.querySelector(s).getBoundingClientRect().toJSON();return {cover:rect('[data-task-cover]'),title:rect('[name=title]'),props:rect('.task-editor-properties'),supplements:rect('.task-editor-supplements'),layout:rect('.task-editor-layout')};});
 assert.ok(geometry.cover.bottom<=geometry.title.y);assert.ok(geometry.cover.right<=geometry.props.x);
 assert.ok(geometry.supplements.y>=geometry.props.bottom);assert.ok(Math.abs(geometry.supplements.width-geometry.layout.width)<1);
 await panel().getByRole('checkbox',{name:'Проверить клавиатуру',exact:true}).click();
 assert.equal(await panel().locator('[data-description]').getAttribute('data-mode'),'preview');
 assert.equal(await panel().getByRole('checkbox',{name:'Проверить клавиатуру',exact:true}).getAttribute('aria-checked'),'true');
 await panel().locator('[data-inline-tag="tag-3"]').click();
 assert.equal(await panel().locator('[data-inline-tag="tag-3"]').getAttribute('aria-pressed'),'false');
 await panel().getByRole('button',{name:'Сохранить задачу',exact:true}).click();await gone();
 let saved=await api.get('/records/tasks/base?projectId='+projectId);assert.match(saved.description,/- \[x\] Проверить клавиатуру/);assert.equal(saved.checklists.length,0);assert.equal(saved.legacyChecklists[0].items[0].done,false);assert.ok(!saved.tagIds.includes('tag-3'));
 mark('Inline chips and Markdown checklists save once with legacy recovery copy');
 await open();await panel().locator('[data-task-threads]').scrollIntoViewIfNeeded();
 assert.match(await panel().locator('.thread-empty').innerText(),/Начните обсуждение/);assert.doesNotMatch(await panel().innerText(),/Сообщения публикуются отдельно/);
 await panel().locator('.thread-compose iq-markdown-editor').getByRole('textbox').fill('- [ ] Проверить тексты\n\nКомментарий команды');await panel().locator('.thread-compose iq-markdown-editor').getByRole('button',{name:'Опубликовать',exact:true}).click();await panel().locator('.thread-message').waitFor();
 await shot('task-content');await close();await open();await panel().locator('.task-thread').waitFor();assert.match(await panel().locator('.task-thread summary').innerText(),/Комментарий команды/);await close();mark('Full-width discussion empty state; Markdown checklist post and automatic load on reopen');
 await open();await panel().locator('[data-add-cover]').click();await modal().getByRole('button',{name:'Исследование',exact:true}).click();await page.waitForFunction(()=>document.querySelector('iq-image-crop')?.source);await modal().locator('[data-crop-action=apply]').click();await panel().locator('.task-detail-cover[data-state=ready]').waitFor();
 await panel().locator('[data-recrop-cover]').click();const cropper=modal().locator('iq-image-crop');await cropper.waitFor();
 await page.waitForFunction(()=>[...document.querySelectorAll('iq-image-crop')].at(-1)?.value);
 const cropState=await cropper.evaluate(el=>({ratio:el.aspectRatio,value:el.value,type:el.source.type,size:el.source.size}));assert.equal(cropState.ratio,2.4);assert.ok(Math.abs(cropState.value.width/cropState.value.height-2.4)<.001);
 await cropper.evaluate(el=>el.value={...el.value,width:el.value.width/2,height:el.value.height/2});
 await shot('cover-crop');
 await cropper.locator('[data-crop-action=apply]').click();await cropper.waitFor({state:'detached'});
 await panel().getByRole('button',{name:'Сохранить задачу',exact:true}).click();await gone();
 saved=await api.get('/records/tasks/base?projectId='+projectId);assert.ok(saved.coverCrop.width<1);const crop=saved.coverCrop;
 await open();await panel().locator('.task-detail-cover[data-state=ready]').waitFor();
 const detail=await panel().locator('.task-detail-cover').boundingBox();assert.ok(Math.abs(detail.width/detail.height-2.4)<.02);
 await panel().locator('[data-recrop-cover]').click();await page.waitForFunction(()=>[...document.querySelectorAll('iq-image-crop')].at(-1)?.value);
 assert.equal(await modal().locator('iq-image-crop').evaluate(el=>el.source.size),cropState.size);await modal().locator('.iq-dialog-head [data-close]').click();
 await shot('task-cover');await close();assert.deepEqual((await api.get('/records/tasks/base?projectId='+projectId)).coverCrop,crop);
 mark('Shared rectangular crop; re-open retains original bytes and normalized frame');
 await open();await panel().getByLabel('Название',{exact:true}).fill('Несохранённый ввод');await page.goBack();
 await page.getByRole('heading',{name:'Закрыть без сохранения?',exact:true}).waitFor();await modal().getByRole('button',{name:'Отмена',exact:true}).click();assert.equal(await panel().getByLabel('Название',{exact:true}).inputValue(),'Несохранённый ввод');
 await panel().locator('.iq-dialog-head [data-close]').click();await modal().getByRole('button',{name:'Не сохранять',exact:true}).click();await gone();
 await page.goto(api.base+'/?project='+projectId+'#/task/SPR-242');await panel().getByLabel('Название',{exact:true}).waitFor();assert.equal(await panel().getByLabel('Название',{exact:true}).inputValue(),'Минимальная задача');
 await page.evaluate(()=>location.hash='/task/SPR-241');await page.waitForFunction(()=>document.querySelector('.task-edit-dialog [name=title]')?.value==='Новый онбординг');
 await close();mark('Human direct URLs, task-to-task navigation and dirty Back guard');
 for(const width of [1440,390])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:width===390?844:1000});await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  for(const label of ['Выбрать пространство','Выбрать проект'])assert.ok(await page.getByRole('button',{name:label,exact:true}).isVisible());
  if(width===390){await page.getByRole('button',{name:'Разделы приложения',exact:true}).click();assert.ok(await page.getByRole('menuitem',{name:'Горячие клавиши',exact:true}).isVisible());await page.keyboard.press('Escape');}
  await shot('board-'+width+'-'+theme);await page.getByRole('button',{name:'Новая задача',exact:true}).click();await panel().getByLabel('Название',{exact:true}).waitFor();assert.ok(await panel().evaluate(el=>el.scrollWidth<=el.clientWidth));await shot('new-task-'+width+'-'+theme);await close();
 }
 mark('1440 / 390 light and dark: alignment, accessible menus and no horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});await page.goto(api.base+'/?project=ux-v3-no-tags#tasks');await page.getByRole('button',{name:'Новая задача',exact:true}).click();await panel().getByLabel('Название',{exact:true}).fill('Сохранить мой черновик');
 await panel().getByRole('button',{name:'Добавить в настройках проекта',exact:true}).click();await modal().getByRole('button',{name:'Новый тег',exact:true}).click();await modal().getByLabel('Название',{exact:true}).fill('Т'.repeat(33));assert.equal(await modal().getByLabel('Название',{exact:true}).evaluate(el=>el.checkValidity()),false);await modal().getByLabel('Название',{exact:true}).fill('Новый тег');await modal().getByRole('button',{name:'Сохранить',exact:true}).click();await modal().getByRole('button',{name:'Вернуться к задаче',exact:true}).click();
 await panel().locator('[data-inline-tag]').waitFor();assert.equal(await panel().getByLabel('Название',{exact:true}).inputValue(),'Сохранить мой черновик');await panel().locator('[data-inline-tag]').click();await panel().getByRole('button',{name:'Сохранить задачу',exact:true}).click();await gone();mark('Empty tags open actual settings; name limit works; returning preserves the task draft');
 await page.setViewportSize({width:1440,height:1000});await page.goto(api.base+'/?storage=browser&uxPreview=1&project=ux-v3-canvas#maps');await page.locator('iq-whiteboard').waitFor();
 const board=page.locator('iq-whiteboard');const state=await board.evaluate(el=>({viewport:el.viewport,data:el.data})),object=state.data.objects.find(o=>o.type==='sticky');assert.ok(object);
 const stageBefore=await board.locator('.wb-stage').boundingBox();await board.evaluate((el,id)=>el.select([id],false),object.id);await page.locator('[data-canvas-inspector]').waitFor();await shot('canvas-inspector');
 assert.deepEqual(await board.locator('.wb-stage').boundingBox(),stageBefore);assert.deepEqual(await board.evaluate(el=>el.viewport),state.viewport);
 await page.locator('[data-canvas-inspector] input[name=x]').fill(String(object.x+30));await page.getByRole('button',{name:'Сохранить изменения',exact:true}).click();await page.locator('[data-canvas-inspector]').waitFor({state:'detached'});
 assert.equal(await board.evaluate((el,id)=>el.data.objects.find(o=>o.id===id).x,object.id),object.x+30);
 await board.evaluate(el=>el.command('undo'));
 await page.waitForFunction(({id,x})=>{const b=document.querySelector('iq-whiteboard');return !b.dirty&&b.data.objects.find(o=>o.id===id).x===x;},{id:object.id,x:object.x});
 const sessionBefore=await board.evaluate(el=>({viewport:el.viewport,revision:el.data.revision}));await page.locator('.map-session-toggle').click();await page.locator('.map-session-content').waitFor();await shot('canvas-session');await page.getByRole('button',{name:'Скрыть сессию',exact:true}).click();await page.locator('.map-session-content').waitFor({state:'detached'});assert.deepEqual(await board.evaluate(el=>({viewport:el.viewport,revision:el.data.revision})),sessionBefore);
 await board.evaluate(el=>el.select([],false));await page.mouse.move(stageBefore.x+80,stageBefore.y+80);const beforeZoom=await board.evaluate(el=>({viewport:el.viewport,revision:el.data.revision}));await page.keyboard.down('Control');await page.mouse.wheel(0,-200);await page.keyboard.up('Control');await page.waitForFunction(old=>document.querySelector('iq-whiteboard').viewport.zoom!==old,beforeZoom.viewport.zoom);
 assert.equal(await board.evaluate(el=>el.data.revision),beforeZoom.revision);await board.evaluate(el=>el.fit());await shot('canvas');mark('Overlay inspector keeps canvas geometry; save/undo, session hide/show and view-only cursor zoom work');
 assert.deepEqual(errors,[]);
}catch(e){failure=e;console.error(e);await page.screenshot({path:out+'/failure.png'});}
finally{await writeFile(out+'/report.json',JSON.stringify({status:failure?'FAIL':'PASS',checks,errors,error:failure?.stack},null,2));await browser.close();for(const fn of cleanup.reverse())await fn();}
if(failure)process.exitCode=1;
