import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import sharp from 'sharp';
import {referenceServer} from './server-fixture.mjs';
const cleanup=[],checks=[],errors=[];let browser,page,failure;
const api=await referenceServer({after:fn=>cleanup.push(fn)});
const {chromium}=await import(process.env.MAPS_PLAYWRIGHT_MODULE?pathToFileURL(process.env.MAPS_PLAYWRIGHT_MODULE).href:'playwright');
const png=await sharp({create:{width:1200,height:600,channels:3,background:'#387188'}}).png().toBuffer();
const jpeg=await sharp({create:{width:600,height:900,channels:3,background:'#bf8670'}}).jpeg().toBuffer();
const mark=name=>{checks.push({name,status:'PASS'});console.log('PASS',name);};
const panel=()=>page.locator('.task-edit-dialog dialog[open]').last();
const last=()=>page.locator('dialog[open]').last();
const save=async()=>{await panel().getByRole('button',{name:'Сохранить задачу',exact:true}).click();await page.locator('.task-edit-dialog').waitFor({state:'detached'});};
const records=()=>page.evaluate(async()=>window.mapsDemo.repository.list('tasks',window.mapsDemo.project.id));
await mkdir('artifacts/board-covers',{recursive:true});
try{
  browser=await chromium.launch({headless:true,...(process.env.MAPS_CHROMIUM_PATH?{executablePath:process.env.MAPS_CHROMIUM_PATH}:{})});
  for(const mode of ['server','browser']){
    const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true});
    await context.route('**/*',route=>new URL(route.request().url()).origin===api.base?route.continue():route.abort());
    await context.addInitScript(()=>{
      const active=new Set(),create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);
      URL.createObjectURL=blob=>{const url=create(blob);active.add(url);return url;};
      URL.revokeObjectURL=url=>{active.delete(url);revoke(url);};
      window.coverURLAudit=active;
    });
    page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`${api.base}/?project=covers-${mode}-${Date.now()}&storage=${mode}#tasks`);
    await page.getByRole('button',{name:'Новая задача',exact:true}).click();
    await panel().getByLabel('Название',{exact:true}).fill('Без обложки');await save();
    assert.equal(await page.locator('.task-card-cover').count(),0);mark(mode+': optional cover adds no empty media slot');
    await page.getByRole('button',{name:'Новая задача',exact:true}).click();
    await panel().getByLabel('Название',{exact:true}).fill('Обложка и документ');
    await panel().locator('[data-cover-input]').setInputFiles({name:'landscape.png',mimeType:'image/png',buffer:png});
    await panel().locator('[data-file-row][data-state=ready]').waitFor();
    await panel().locator('.task-detail-cover[data-state=ready]').waitFor();
    assert.equal((await records()).length,1,'Staging must not create a task');
    await panel().locator('[data-file-input]').setInputFiles({name:'acceptance.md',mimeType:'text/plain',buffer:Buffer.from('## Проверка\n\n- [ ] Сохранить')});
    await page.waitForFunction(()=>document.querySelectorAll('.task-edit-dialog [data-file-row][data-state=ready]').length===2);
    await save();let task=(await records()).find(task=>task.title==='Обложка и документ');
    assert.ok(task.coverAttachmentId);assert.equal(task.attachmentIds.length,2);const firstCover=task.coverAttachmentId;
    await page.locator('.task-card-cover[data-state=ready]').waitFor();
    await page.waitForFunction(()=>document.querySelector('.task-card-cover img')?.naturalWidth>0);
    await page.reload();await page.locator('.task-card-cover[data-state=ready]').waitFor();
    assert.equal((await records()).find(item=>item.id===task.id).coverAttachmentId,firstCover);
    mark(mode+': staged image and document commit once and the board cover survives reload');
    await page.getByRole('button',{name:task.title,exact:true}).click();
    await panel().locator('.task-detail-cover[data-state=ready]').waitFor();
    await panel().locator('[data-file-download]').first().waitFor();
    const downloading=page.waitForEvent('download');await panel().locator('[data-file-download]').first().click();
    const downloaded=await downloading;assert.deepEqual(await readFile(await downloaded.path()),png);
    await panel().locator('[data-preview-cover]').click();await last().locator('[data-cover-full]').waitFor();
    await last().locator('.iq-dialog-head [data-close]').click();
    mark(mode+': task cover preview and original-file download use real saved bytes');
    await panel().locator('[data-remove-cover]').click();await save();
    task=(await records()).find(item=>item.id===task.id);assert.equal(task.coverAttachmentId,null);assert.equal(task.attachmentIds.length,2);
    assert.equal(await page.locator('.task-card-cover').count(),0);mark(mode+': removing the cover retains both attachments');
    await page.getByRole('button',{name:task.title,exact:true}).click();
    await panel().locator(`[data-file-cover="${firstCover}"]`).click();
    await panel().locator('.task-detail-cover[data-state=ready]').waitFor();
    await panel().getByLabel('Название',{exact:true}).fill('Черновик не теряется');
    await panel().locator('[data-cover-input]').setInputFiles({name:'portrait.jpg',mimeType:'image/jpeg',buffer:jpeg});
    await page.waitForFunction(()=>document.querySelectorAll('.task-edit-dialog [data-file-row][data-state=ready]').length===3);
    assert.equal(await panel().getByLabel('Название',{exact:true}).inputValue(),'Черновик не теряется');await save();
    task=(await records()).find(item=>item.id===task.id);assert.notEqual(task.coverAttachmentId,firstCover);assert.equal(task.attachmentIds.length,3);
    await page.locator('.task-card-cover[data-state=ready]').waitFor();
    await page.screenshot({path:`artifacts/board-covers/board-${mode}-light.png`});
    mark(mode+': replacement preserves original attachment and authored task text');
    await page.getByRole('button',{name:task.title,exact:true}).click();
    await panel().locator(`[data-file-remove="${task.coverAttachmentId}"]`).waitFor();
    await panel().locator(`[data-file-remove="${task.coverAttachmentId}"]`).click();await save();
    task=(await records()).find(item=>item.id===task.id);assert.equal(task.coverAttachmentId,null);assert.equal(task.attachmentIds.length,2);
    mark(mode+': removing the selected cover attachment clears both references');
    await page.getByRole('button',{name:task.title,exact:true}).click();
    await panel().locator(`[data-file-cover="${firstCover}"]`).click();await save();
    await page.getByRole('button',{name:task.title,exact:true}).click();
    await panel().locator('[data-cover-input]').setInputFiles({name:'spoof.png',mimeType:'image/png',buffer:Buffer.from('not an image')});
    await panel().locator('[data-file-row][data-state=failed]').waitFor();
    assert.ok(await panel().locator('.task-detail-cover').isVisible());
    await panel().getByRole('button',{name:'Сохранить задачу',exact:true}).click();
    await panel().locator('.map-dialog-form > .map-form-error:not([hidden])').waitFor();
    await panel().locator('[data-file-row][data-state=failed] [data-file-remove]').click();
    await panel().locator('.iq-dialog-head [data-close]').click();await page.locator('.task-edit-dialog').waitFor({state:'detached'});
    assert.equal((await records()).find(item=>item.id===task.id).coverAttachmentId,firstCover);
    mark(mode+': invalid upload keeps the prior cover and cannot silently disappear during save');
    if(mode==='server'){
      let lose=true;await context.route('**/api/files/**',async route=>{
        if(lose&&route.request().method()==='PUT'){lose=false;await route.fetch();await route.abort('failed');}
        else await route.continue();
      });
      await page.getByRole('button',{name:task.title,exact:true}).click();
      await panel().locator('[data-file-input]').setInputFiles({name:'retry.md',mimeType:'text/plain',buffer:Buffer.from('Повтор без дубля')});
      const failed=panel().locator('[data-file-row][data-state=failed]');await failed.waitFor();const retryId=await failed.getAttribute('data-file-row');
      await failed.getByRole('button',{name:'Повторить',exact:true}).click();
      await panel().locator(`[data-file-row="${retryId}"][data-state=ready]`).waitFor();await save();
      task=(await records()).find(item=>item.id===task.id);assert.equal(task.attachmentIds.filter(id=>id===retryId).length,1);
      mark('server: lost upload response can be retried without duplicating the attachment');
    }
    await page.getByRole('button',{name:task.title,exact:true}).click();
    await panel().locator('[data-cover-input]').setInputFiles({name:'discard.png',mimeType:'image/png',buffer:png});
    await page.waitForFunction(()=>[...document.querySelectorAll('.task-edit-dialog [data-file-row]')].some(row=>row.textContent.includes('discard.png')&&row.dataset.state==='ready'));
    await panel().locator('.iq-dialog-head [data-close]').click();
    await last().getByRole('button',{name:'Не сохранять',exact:true}).click();await page.locator('.task-edit-dialog').waitFor({state:'detached'});
    assert.equal((await records()).find(item=>item.id===task.id).coverAttachmentId,firstCover);
    mark(mode+': discarding an uploaded replacement retains the committed cover');
    const handle=page.getByRole('button',{name:'Переместить задачу: '+task.title,exact:true});
    await handle.focus();await page.keyboard.press('Enter');await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');
    await page.waitForFunction(id=>document.querySelector(`[data-drop-status]:nth-child(2) [data-drag-id="${id}"]`),task.id);
    await page.locator(`[data-drag-id="${task.id}"] .task-card-cover[data-state=ready]`).waitFor();
    assert.equal((await records()).find(item=>item.id===task.id).coverAttachmentId,firstCover);
    mark(mode+': moving a covered card preserves file references and mixed-height layout');
    await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Переключить тему',exact:true}).click();
    await page.getByRole('button',{name:task.title,exact:true}).click();await panel().locator('.task-detail-cover[data-state=ready]').waitFor();
    const rect=await panel().boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=391);
    await page.screenshot({path:`artifacts/board-covers/task-${mode}-dark.png`});
    await panel().locator('[data-task-files]').scrollIntoViewIfNeeded();
    assert.equal(await panel().locator('[data-file-row]').count(),task.attachmentIds.length);
    await page.screenshot({path:`artifacts/board-covers/files-${mode}-dark.png`});
    await panel().locator('.iq-dialog-head [data-close]').click();await page.locator('.task-edit-dialog').waitFor({state:'detached'});
    mark(mode+': cover and attachment actions remain bounded in narrow dark task view');
    await page.getByRole('link',{name:'Карты',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#host-view').hidden);
    await page.waitForFunction(()=>window.coverURLAudit.size===0);
    mark(mode+': leaving the board releases every owned object URL');
    await context.close();
  }
  assert.deepEqual(errors,[]);mark('no JavaScript errors in cover or attachment workflows');
}catch(error){failure=error;console.error(error);await page?.screenshot({path:'artifacts/board-covers/failure.png'}).catch(()=>{});}
finally{
  await writeFile('artifacts/board-covers/browser.json',JSON.stringify({status:failure?'FAIL':'PASS',checks,errors,error:failure?.message,browser:browser?.version()},null,2));
  await browser?.close();for(const fn of cleanup.reverse())await fn();
}
if(failure)process.exitCode=1;
