import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from '../../maps/node_modules/playwright/index.mjs';
import {startServer} from '../scripts/server.mjs';
const server=await startServer(0),out=new URL('../evidence/',import.meta.url);await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}});
page.setDefaultTimeout(10000);const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const mark=label=>{checks.push(label);console.log('PASS',label);};let failure;
try{
 await page.goto(server.url+'/?fixture='+crypto.randomUUID());
 await page.getByRole('heading',{name:'Планирование',exact:true}).waitFor();
 await page.locator('[data-select]').first().waitFor();

 assert.deepEqual(errors,[]);mark('Mounted actual DS, release groups and task rows');
 await page.screenshot({path:new URL('initial-light.png',out).pathname});
 const loaded=()=>page.waitForFunction(()=>{const c=window.planningFixture.view?.controller;return c&&!c.loading&&!c.error&&c.groups.every(g=>!g.busy);});
 const scroller=page.locator('.pn-scroll');const firstHeader=page.locator('.pn-group-header').first();
 await scroller.evaluate(el=>el.scrollTop=200);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const containerBox=await scroller.boundingBox(),headerBox=await firstHeader.boundingBox();assert.ok(Math.abs(containerBox.y-headerBox.y)<2);
 await scroller.evaluate(el=>el.scrollTop=0);
 const disclosure=page.getByRole('button',{name:'Скрыть подзадачи SPR-1',exact:true});await disclosure.focus();
 assert.ok(await disclosure.evaluate(el=>el.matches(':focus-visible')));await page.keyboard.press('Enter');await loaded();
 await page.getByRole('button',{name:'Показать подзадачи SPR-1',exact:true}).focus();await page.keyboard.press('Enter');await loaded();
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.ok(await page.getByRole('button',{name:'Новая задача',exact:true}).evaluate(el=>getComputedStyle(el).transitionDuration.split(',').every(v=>parseFloat(v)<=0.001)));
 await page.emulateMedia({reducedMotion:'no-preference'});mark('Group heading is sticky in shared scroll; keyboard disclosure and reduced-motion contract work');
 const task=n=>page.locator(`[data-select="pn-task-${n}"]`);
 await task(1).check();assert.equal(await page.locator('[data-select]:checked').count(),1);
 await page.getByRole('button',{name:'Скрыть подзадачи SPR-1',exact:true}).click();await loaded();
 assert.equal(await task(2).count(),0);assert.equal(await task(3).count(),0);
 assert.equal(await page.locator('.pn-group').first().locator('.pn-count').textContent(),'4');
 await page.getByRole('button',{name:'Показать подзадачи SPR-1',exact:true}).click();await loaded();await task(2).waitFor();
 assert.equal(await task(1).isChecked(),true);assert.equal(await task(2).isChecked(),false);
 await page.getByRole('button',{name:'Снять выделение',exact:true}).click();
 mark('Parent selection does not cascade; collapse preserves count and selection; children expand by default');
 await task(2).check();await page.getByRole('button',{name:'Скрыть подзадачи SPR-1',exact:true}).click();await loaded();
 assert.match(await page.locator('[data-selection-summary]').textContent(),/скрыто: 1/);
 await page.getByRole('searchbox',{name:'Найти задачу или релиз',exact:true}).fill('пригласить');
 await page.waitForFunction(()=>window.planningFixture.view.controller.filters.query==='пригласить');await loaded();
 await page.locator('[data-open="pn-task-7"]').waitFor();assert.equal(await page.locator('[data-bulk]').isVisible(),false);
 assert.ok(await page.locator('[data-context=true]').count());
 await page.getByRole('searchbox',{name:'Найти задачу или релиз',exact:true}).fill('');
 await page.waitForFunction(()=>window.planningFixture.view.controller.filters.query==='');await loaded();
 mark('Filtered children retain parent context; filter change clears hidden selection');
 await page.evaluate(()=>window.planningFixture.adapter.failNextRead=true);
 await page.getByRole('button',{name:'Обновить список',exact:true}).click();
 await page.getByText('Тестовый сбой чтения. Повторите загрузку.',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Новая задача',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Повторить загрузку',exact:true}).click();await loaded();
 mark('Failed read keeps context, disables mutations, retries without replacing user data');


 await page.locator('[data-group="pn-release-next"] [data-start]').click();
 const start=page.getByRole('dialog',{name:'Начать релиз',exact:true});
 await start.getByText('Нужно уточнение',{exact:true}).first().waitFor();
 assert.equal(await start.getByRole('button',{name:'Подтвердить',exact:true}).isDisabled(),true);
 await start.getByRole('button',{name:'Отмена',exact:true}).click();await start.waitFor({state:'hidden'});
 await task(5).check();await task(9).check();
 await page.getByRole('button',{name:'Подготовить',exact:true}).click();
 const prepare=page.getByRole('dialog',{name:'Подготовить задачи',exact:true});
 await prepare.getByRole('button',{name:'Подтвердить',exact:true}).click();await prepare.waitFor({state:'hidden'});await loaded();
 assert.equal(await page.evaluate(async()=> (await window.planningFixture.repository.read('tasks','pn-task-9','pn-project')).preparation),'ready');
 mark('Draft work blocks launch; explicit preparation retains task identity and workflow status');
 await page.locator('[data-group="pn-release-next"] [data-start]').click();
 await start.getByRole('button',{name:'Подтвердить',exact:true}).click();await start.waitFor({state:'hidden'});await loaded();
 assert.equal(await page.locator('[data-group="pn-release-next"] .pn-group-header').getByText('В работе',{exact:true}).isVisible(),true);
 await page.locator('[data-group="pn-release-next"] [data-board]').click();
 await page.getByRole('heading',{name:'Доска задач',exact:true}).waitFor();
 assert.equal(await page.locator('.kanban-column').count(),6);
 await page.locator('[data-drag-id="pn-task-9"]').waitFor();
 await page.locator('[data-route=planning]').click();await page.getByRole('heading',{name:'Планирование',exact:true}).waitFor();await loaded();
 mark('Launch exposes the same tasks on the existing six-column board without changing workflow states');
 await task(10).check();await page.getByRole('button',{name:'В релиз…',exact:true}).click();
 const picker=page.getByRole('dialog',{name:'Перенести в релиз',exact:true});
 const combo=picker.getByRole('combobox',{name:'Релиз назначения',exact:true});
 await combo.fill('Что сделаем');await picker.getByRole('option',{name:/Что сделаем дальше/}).click();
 await picker.getByRole('button',{name:'Проверить перенос',exact:true}).click();
 const transfer=page.getByRole('dialog',{name:'Изменение состава',exact:true});
 await transfer.getByRole('button',{name:'Подтвердить',exact:true}).waitFor();
 await transfer.getByRole('button',{name:'Отмена',exact:true}).click();await transfer.waitFor({state:'hidden'});await loaded();
 assert.equal(await page.evaluate(async()=> (await window.planningFixture.repository.read('tasks','pn-task-10','pn-project')).releaseId),null);
 mark('DS remote destination picker and transfer preview cancel have no write side effects');

 await page.getByRole('button',{name:'В релиз…',exact:true}).click();
 await picker.getByRole('combobox',{name:'Релиз назначения',exact:true}).fill('Что сделаем');
 await picker.getByRole('option',{name:/Что сделаем дальше/}).click();await picker.getByRole('button',{name:'Проверить перенос',exact:true}).click();
 await page.evaluate(()=>window.planningFixture.adapter.loseNextAck=true);
 await transfer.getByRole('button',{name:'Подтвердить',exact:true}).click();
 await transfer.getByRole('button',{name:'Проверить результат',exact:true}).waitFor();
 assert.equal(await transfer.getByRole('button',{name:'Отмена',exact:true}).isDisabled(),true);
 const once=await page.evaluate(async()=>{const s=await window.planningFixture.repository.fixtureSnapshot();return {receipts:s._pnFixture.filter(x=>x.token).length,task:s.tasks.find(x=>x.id==='pn-task-10')};});
 assert.equal(once.task.releaseId,'pn-release-later');
 await transfer.getByRole('button',{name:'Проверить результат',exact:true}).click();await transfer.waitFor({state:'hidden'});await loaded();
 assert.equal(await page.evaluate(async()=> (await window.planningFixture.repository.fixtureSnapshot())._pnFixture.filter(x=>x.token).length),once.receipts);
 mark('Lost response preserves committed data; receipt recovery closes once and creates no duplicate effect');
 await page.locator('[data-open="pn-task-10"]').click();
 const detail=page.locator('.task-edit-dialog');await detail.getByRole('textbox',{name:/^Название/}).fill('Перенесённая задача с сохранённым документом');
 await detail.getByRole('button',{name:'Сохранить задачу',exact:true}).click();await detail.waitFor({state:'hidden'});await loaded();
 await page.getByRole('button',{name:'Перенесённая задача с сохранённым документом',exact:true}).waitFor();
 await page.reload();await page.getByRole('button',{name:'Перенесённая задача с сохранённым документом',exact:true}).waitFor();await loaded();
 assert.equal(await page.evaluate(async()=> (await window.planningFixture.repository.read('tasks','pn-task-10','pn-project')).releaseId),'pn-release-later');
 mark('Original v3.4 task document saves and reloads with unchanged ID, Markdown and release membership');
 await page.getByRole('button',{name:'Новый релиз',exact:true}).click();
 const create=page.getByRole('dialog',{name:'Новый релиз',exact:true});await create.getByRole('textbox',{name:/^Название релиза/}).fill('Проверяемый релиз без дат');
 await create.getByRole('button',{name:'Создать релиз',exact:true}).click();await create.waitFor({state:'hidden'});await loaded();
 await page.getByRole('heading',{name:'Проверяемый релиз без дат',exact:true}).waitFor();
 await page.getByRole('button',{name:'Новая задача',exact:true}).click();
 const draft=page.getByRole('dialog',{name:'Новая задача',exact:true});await draft.getByRole('textbox',{name:/^Название задачи/}).fill('Новый черновик планирования');
 await draft.getByRole('button',{name:'Создать задачу',exact:true}).click();await draft.waitFor({state:'hidden'});await loaded();
 await page.getByRole('button',{name:'Новый черновик планирования',exact:true}).waitFor();
 const newTask=await page.evaluate(async()=> (await window.planningFixture.repository.list('tasks','pn-project')).find(x=>x.title==='Новый черновик планирования'));
 assert.equal(newTask.preparation,'draft');assert.equal(newTask.planningAdmission,false);
 mark('Create flexible release without dates and shared task draft into backlog');
 for(const width of [1440,768,390,320])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await loaded();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('.pn-scroll').evaluate(el=>el.scrollTop=0);
  await page.screenshot({path:new URL(`planning-${theme}-${width}.png`,out).pathname});
 }
 mark('Current DS themes and responsive 1440/768/390/320 layouts without document overflow');
 await page.setViewportSize({width:1440,height:900});
 await page.locator('[data-route=maps]').click();await page.waitForFunction(()=>!!window.planningFixture.view&&!window.planningFixture.view.controller);await page.getByRole('link',{name:'Планирование',exact:true}).click();await loaded();
 assert.deepEqual(errors,[]);mark('Navigation to the existing map and back cleans up without JavaScript errors');

 await page.locator('[data-select=pn-task-11]').check();await page.getByRole('button',{name:'Подготовить',exact:true}).click();
 const stale=page.getByRole('dialog',{name:'Подготовить задачи',exact:true});await stale.getByRole('button',{name:'Подтвердить',exact:true}).waitFor();
 await page.evaluate(async()=>{const repo=window.planningFixture.repository,item=await repo.read('tasks','pn-task-11','pn-project');await repo.write('tasks',{...item,title:item.title+' — обновлено другим клиентом'},item.revision);});
 await stale.getByRole('button',{name:'Подтвердить',exact:true}).click();await stale.getByRole('button',{name:'Проверить снова',exact:true}).waitFor();
 assert.equal(await stale.getByRole('button',{name:'Подтвердить',exact:true}).isDisabled(),true);
 assert.equal(await page.evaluate(async()=> (await window.planningFixture.repository.read('tasks','pn-task-11','pn-project')).preparation),'draft');
 await stale.getByRole('button',{name:'Отмена',exact:true}).click();await stale.waitFor({state:'hidden'});await loaded();
 await page.getByRole('button',{name:'Снять выделение',exact:true}).click();mark('Changed scope invalidates preview; rejected confirm remains disabled and draft is untouched');
 await page.evaluate(async()=>{const repo=window.planningFixture.repository;const template=await repo.read('tasks','pn-task-12','pn-project');await repo.fixtureTransaction((_s,put)=>{for(let i=0;i<110;i++)put('tasks',{...template,id:'pn-big-'+i,displayId:undefined,number:undefined,revision:0,title:'Пакетная проверка '+i,parentId:null,releaseId:null,releaseAssignment:'none',planningAdmission:false,planningRank:100000+i},0);});});
 const backlog=page.locator('[data-group=backlog]');await backlog.scrollIntoViewIfNeeded();await backlog.locator('[data-select]').first().waitFor();await loaded();
 assert.equal(await backlog.locator('[data-row]').count(),50);
 const countBefore=await backlog.locator('.pn-count').textContent();
 await backlog.getByRole('button',{name:'Показать ещё задачи',exact:true}).click();await loaded();
 assert.equal(await backlog.locator('[data-row]').count(),100);assert.equal(await backlog.locator('.pn-count').textContent(),countBefore);
 await backlog.locator('[data-select]').first().check();await page.getByRole('checkbox',{name:'Все показанные',exact:true}).check();
 const selection=await page.evaluate(()=>{const c=window.planningFixture.view.controller;return {selected:c.selection.ids.size,visible:c.visibleRows().length};});assert.equal(selection.selected,selection.visible);assert.ok(selection.selected<123);
 mark('Cursor paging keeps canonical counts; select-all affects loaded rows only, not the whole backlog');
 await page.getByRole('button',{name:'Снять выделение',exact:true}).click();
 await page.evaluate(async()=>{const port=window.planningFixture.adapter,original=port.listGroups;port.listGroups=async opts=>({...await original(opts),capabilities:{}});await window.planningFixture.view.reload();});await loaded();
 assert.equal(await page.getByRole('button',{name:'Новая задача',exact:true}).isDisabled(),true);
 assert.equal(await page.getByRole('button',{name:'Новый релиз',exact:true}).isDisabled(),true);assert.equal(await page.locator('[data-start]').count(),0);
 mark('Missing host capabilities fail closed for creation and launch, without claiming backend authorization');
 assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>window.planningFixture.routeError||null),null);
}catch(error){failure=error;console.error(error);console.error(await page.evaluate(()=>window.planningFixture?.routeError));await page.screenshot({path:new URL('failure.png',out).pathname});}
finally{await writeFile(new URL('browser.json',out),JSON.stringify({status:failure?'FAIL':'PASS',checks,errors,error:failure?.stack},null,2));await browser.close();await server.close();}
if(failure)process.exitCode=1;
