import {bindBoard,taskEmphasis,taskSignal,normalizeTaskKind,normalizePriority,ui,registerCore} from '../dist/vendor/core.js';
import {TASK_COLUMNS,taskColumn,taskOrder,placeTask,createTask} from '../src/tasks.js';
import {icon,esc,dialog,input,textarea,select,button} from '../src/ui.js';

/** Composition taken from IQUIPAGE's workspace board example. Only the host persists tasks. */
export async function mountTaskBoard(root,{repository,project,onOpenMap,canEdit=true}) {
  registerCore();let items=[],disposeBoard,loading=0,closed=false,busy=false;
  const abort=new AbortController(),signal=abort.signal;
  root.innerHTML=`<div class="host-task-page"><header class="host-task-heading"><div><h1>Доска задач</h1><p class="host-task-count" role="status">Загружаем задачи…</p></div><button type="button" class="iq-btn primary sm" data-create-task ${canEdit?'':'disabled'}>${icon('plus',17)}<span>Новая задача</span></button></header><div class="host-task-tools"><label class="iq-search-small">${icon('search',17)}<input type="search" aria-label="Поиск задач" placeholder="Найти задачу…"></label><span class="map-explanation">${repository.capabilities?.storage==='browser'?'Сохранение в этом браузере':'Локальный стенд · сохранение на диск'}</span><button type="button" class="iq-btn ghost sm" data-refresh-tasks>${icon('refresh',17)}<span>Обновить</span></button></div><p class="host-task-error" role="alert" hidden></p><div class="host-board-mount"></div><p class="iq-helper board-drag-help" id="board-drag-help">За ручку — перетащить. С клавиатуры: Enter — взять, стрелки — переместить, Enter — подтвердить, Escape — отменить. Статус также доступен в меню задачи.</p><span class="sr-only" role="status" data-task-live></span></div>`;
  const mount=root.querySelector('.host-board-mount'),error=root.querySelector('.host-task-error'),count=root.querySelector('.host-task-count');
  const fail=e=>{error.hidden=false;error.textContent=e.message||'Задача не сохранена. Повторите действие.';};
  const ownerAvatar=owner=>{const name=owner?.trim();return name?`<span class="iq-avatar v1" title="${esc(name)}" aria-label="${esc(name)}">${esc(name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span>`:`<span class="task-owner-empty" title="Без ответственного">${icon('user',17)}</span>`;};
  const card=t=>`<article class="task-card" data-task-surface="${t.id}" data-task-emphasis="${taskEmphasis(t)}" data-task-kind="${normalizeTaskKind(t.type)}" data-drag-id="${t.id}" data-priority="${normalizePriority(t.priority)}"><div class="task-card-top"><div class="task-identity"><button type="button" class="iq-drag-handle" data-drag-handle aria-label="Переместить задачу: ${esc(t.title)}" aria-pressed="false" aria-describedby="board-drag-help" ${!canEdit||busy?'disabled':''}>${icon('grip',16)}</button><span class="task-card-id">${esc(t.displayId||t.id.slice(-7).toUpperCase())}</span>${taskSignal(t)}</div>${ui.menu(ui.ib('more','Действия задачи: '+t.title,'ghost sm'),[{label:'Открыть задачу',glyph:'expand',action:'open:'+t.id},...(canEdit?TASK_COLUMNS.map(c=>({label:c.label,glyph:c.icon,action:'move:'+t.id+':'+c.id})):[])])}</div><button type="button" class="task-card-title" data-open-task="${t.id}">${esc(t.title)}</button><div class="task-card-footer"><span class="task-due">${icon(t.sourceMapId?'link':'calendar',15)}<span>${t.sourceMapId?'Из карты':'Без срока'}</span></span>${ownerAvatar(t.owner)}</div>${t.status==='done'?'<span class="host-legacy-status">Прежний статус: выполнено</span>':''}</article>`;
  function render(focusId){
    if(closed)return;disposeBoard?.();const scroll=mount.querySelector('.iq-board');const position={x:scroll?.scrollLeft||0,y:scroll?.scrollTop||0};
    const query=root.querySelector('input[type=search]').value.trim().toLocaleLowerCase('ru');
    const visible=items.filter(t=>!query||[t.title,t.description,t.owner,t.displayId].join(' ').toLocaleLowerCase('ru').includes(query)).sort(taskOrder);
    count.textContent=`Задач: ${items.length}${query?' · найдено: '+visible.length:''}`;
    mount.innerHTML=`<div class="kanban iq-board host-task-board" role="region" aria-label="Доска задач. Шесть столбцов." tabindex="0" ${busy?'aria-busy="true" inert':''}>${TASK_COLUMNS.map(c=>`<section class="kanban-column" data-drop-status="${c.id}" aria-label="${c.label}"><div class="kanban-column-header">${icon(c.icon,18)}<h3>${c.label}</h3><span class="kanban-count">${visible.filter(t=>taskColumn(t)===c.id).length}</span></div><div class="column-cards" data-column-cards>${visible.filter(t=>taskColumn(t)===c.id).map(card).join('')}<div class="board-empty-slot" aria-hidden="true">Пока нет задач</div></div>${canEdit?`<button type="button" class="iq-btn ghost sm host-column-add" data-column-create="${c.id}">${icon('plus',16)}<span>Добавить задачу</span></button>`:''}</section>`).join('')}</div>`;
    const board=mount.querySelector('.iq-board');board.scrollLeft=position.x;board.scrollTop=position.y;
    if(canEdit&&!busy)disposeBoard=bindBoard(board,({id,status,beforeId})=>move(id,status,beforeId));
    if(focusId)mount.querySelector(`[data-drag-id="${focusId}"] [data-drag-handle]`)?.focus({preventScroll:true});
  }
  async function reload(){const token=++loading;try{const all=await repository.list('tasks',project.id);if(closed||token!==loading)return;items=all;render();}catch(e){if(!closed)fail(e);}}
  async function move(id,status,beforeId=null){
    if(!canEdit||busy||closed)return;busy=true;error.hidden=true;render();
    try{const task=items.find(t=>t.id===id);const saved=await repository.write('tasks',placeTask(task,items,status,beforeId),task.revision);items=items.map(t=>t.id===id?saved:t);root.querySelector('[data-task-live]').textContent=`Задача перемещена: ${TASK_COLUMNS.find(c=>c.id===status).label}`;}
    catch(e){fail(e);await reload();}finally{busy=false;render(id);}
  }
  function edit(task=null,status='ready'){
    const editable=canEdit;return dialog({title:task?'Задача':'Новая задача',description:task?.sourceMapId?'Создана из карты. Ссылка на исходное обсуждение сохранена.':'Задача относится к проекту, а не к модулю карт.',body:`${input('title','Название',task?.title||'',{required:true})}${textarea('description','Описание',task?.description||'',4)}${select('status','Статус',task?taskColumn(task):status,TASK_COLUMNS.map(c=>[c.id,c.label]))}${input('owner','Ответственный',task?.owner||'',{maxlength:120,placeholder:'Можно назначить позже'})}${select('priority','Приоритет',task?.priority||'normal',[['normal','Обычный'],['high','Высокий'],['critical','Критический'],['low','Низкий']])}${task?.sourceMapId?button('task-map','Открыть исходную карту','link','secondary'):''}`,submitLabel:editable?'Сохранить задачу':'',onSubmit:editable?async values=>{
      const changes=Object.fromEntries(values);const value=task?{...task,...changes}:createTask({projectId:project.id,...changes});await repository.write('tasks',value,task?.revision||0);await reload();
    }:undefined,mount:el=>{if(!editable)el.querySelectorAll('input,textarea,iq-select').forEach(x=>{if(x.tagName==='IQ-SELECT')x.setAttribute('disabled','');else x.readOnly=true;});el.querySelector('[data-map-action=task-map]')?.addEventListener('click',()=>{el.close(true);onOpenMap?.(task.sourceMapId);});}});
  }
  root.addEventListener('click',e=>{const open=e.target.closest('[data-open-task]'),add=e.target.closest('[data-create-task],[data-column-create]');if(open)edit(items.find(t=>t.id===open.dataset.openTask));if(add&&canEdit)edit(null,add.dataset.columnCreate||'ready');if(e.target.closest('[data-refresh-tasks]'))reload();},{signal});
  root.addEventListener('iq-action',e=>{const [action,id,status]=String(e.detail.action||'').split(':');if(action==='open')edit(items.find(t=>t.id===id));if(action==='move')move(id,status);},{signal});
  root.querySelector('input[type=search]').addEventListener('input',()=>render(),{signal});
  await reload();return {reload,destroy(){closed=true;loading++;abort.abort();disposeBoard?.();}};
}
